---
title: "원자력안전법 시행령"
description: |
  [시행 2024. 11. 1.] [대통령령 제34975호, 2024. 10. 29., 일부개정]<br><br>
  <div style="text-align: right;">
  원자력안전위원회(안전정책과), 02-397-7264<br>
  원자력안전위원회(방사선안전과), 02-397-7273<br>
  원자력안전위원회(안전기준과), 02-397-7315<br>
  원자력안전위원회(생활방사선안전과), 02-397-7334</div>
date: "2024-11-01"
date-modified: "2024-11-01"
categories: [시행령]
---

# 제1장 총칙

### 제8조 방사선발생장치

::: {.callout-note title="제8조(방사선발생장치)" collapse="open" appearance="minimal"}
법 제2조제9호에서 “대통령령으로 정하는 것”이란 다음 각 호의 것을 말한다. 다만, 위원회가 정하는 용도의 것과 위원회가 정하는 용량 이하의 것은 제외한다.

1.  엑스선발생장치

2.  사이클로트론(cyclotron)

3.  신크로트론(synchrotron)

4.  신크로사이클로트론(synchro-cyclotron)

5.  선형가속장치

6.  베타트론(betatron)

7.  반ㆍ데 그라프형 가속장치

8.  콕크로프트ㆍ왈톤형 가속장치

9.  변압기형 가속장치

10. 마이크로트론(microtron)

11. 방사광가속기

12. 가속이온주입기

13. 그 밖에 위원회가 정하여 고시하는 것
:::

# 제9장 규제ㆍ감독 등

### 제131조 측정

::: {.callout-note title="제131조(측정)" collapse="open" appearance="minimal"}
① 원자력관계사업자(신고사용자는 제외한다. 이하 이 조, 제132조, 제133조, 제148조 및 제148조의3에서 같다)는 법 제91조제1항제1호에 따라 총리령으로 정하는 방사선장해의 우려가 있는 장소에 대한 방사선량 및 방사성물질등에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16., 2017. 3. 20.>

② 법 제91조제1항제1호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설에 출입하는 사람의 피폭방사선량 및 방사성물질에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16.>

③ 원자력관계사업자는 제1항 및 제2항의 측정 결과에 관하여 기록의 작성, 보존, 그 밖의 총리령으로 정하는 조치를 하여야 한다. <개정 2013. 3. 23.>
:::

### 제132조 건강진단

::: {.callout-note title="제132조(건강진단)" collapse="open" appearance="minimal"}
① 법 제91조제1항제2호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설의 방사선작업종사자 및 수시출입자에 대하여 건강진단을 실시하여야 한다. <개정 2013. 3. 23., 2013. 8. 16., 2016. 4. 12.>

② 원자력관계사업자는 제1항의 건강진단의 결과에 관하여 기록의 작성ㆍ보존 그 밖에 총리령으로 정하는 조치를 하여야 한다. <개정 2013. 3. 23.>
:::


# 제10장 보칙

### 제148조 방사선작업종사자 및 수시출입자 교육

::: {.callout-note title="제148조(방사선작업종사자 및 수시출입자 교육)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 법 제106조제1항에 따라 방사선작업종사자에 대해서는 신규교육과 정기교육을 실시하여야 한다. 이 경우 신규교육은 작업 종사 전에 실시하여야 한다.

② 제1항에 따른 교육은 기본교육과 직장교육으로 구분하여 실시한다. 이 경우 직장교육은 방사선안전관리자 외의 방사선작업종사자를 대상으로 한다. \<개정 2014. 11. 19.\>

③ 원자력관계사업자는 수시출입자에 대하여 기본교육 또는 직장교육을 실시할 수 있다. \<신설 2016. 4. 12.\>

④ 제2항 및 제3항에 따른 기본교육은 안전재단에서 받도록 하여야 하며, 직장교육은 해당 원자력관계사업자가 자체적으로 실시하되 위원회가 지정하여 고시하는 기관에 위탁하여 실시할 수 있다. \<개정 2014. 11. 19., 2016. 4. 12., 2016. 6. 21.\>

⑤ 제1항부터 제3항까지의 규정에 따른 교육의 과정 및 시간 등은 총리령으로 정한다. \<개정 2016. 4. 12.\>

⑥ 제149조제1항에 따른 보수교육을 받은 자는 제1항에 따른 해당 연도의 정기교육을 받은 것으로 본다. \<신설 2014. 11. 19., 2016. 4. 12.\>

\[전문개정 2013. 8. 16.\] \[제목개정 2016. 4. 12.\]
:::

### 별표1. 선량한도

-   [선량한도(제2조제4호 관련)](/archive/별표1_선량한도_제2조제4호_관련_원자력안전법_시행령.pdf)
