---
title: "시행규칙"
description: |
  [시행 2024. 12. 24.] [총리령 제2000호, 2024. 12. 24., 타법개정]"<br><br>
  <div style="text-align: right;">
  원자력안전위원회(안전정책과), 02-397-7264<br>  
  원자력안전위원회(안전기준과), 02-397-7315<br>  
  원자력안전위원회(생활방사선안전과), 02-397-7334<br>
  원자력안전위원회(방사선안전과), 02-397-7273</div>
date: "2024-12-24"
date-modified: "2024-12-24"
categories: [시행규칙]
---

# 제5장 방사성동위원소등, 방사성폐기물 및 방사성물질의 관리



### 제58조(방사성동위원소등의 생산허가 신청 등)

::: {.callout-note title="제58조(방사성동위원소등의 생산허가 신청 등)" collapse="open" appearance="minimal"}
① 영 제79조제1항, 제2항 및 제3항에 따른 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)의 생산허가신청은 별지 제41호서식 또는 별지 제42호서식의 신청서에 따른다. <개정 2019. 12. 3.>

② 법 제53조제3항에 따라 제1항의 신청서에는 다음 각 호의 서류를 첨부하여야 한다. <개정 2014. 11. 24.>

1. 안전성분석보고서

2. 품질보증계획서

3. 방사선안전보고서

4. 안전관리규정

5. 영 별표 2에 따른 장비의 구입을 증명하는 서류

6. 영 별표 3에 따른 인력의 재직을 입증하는 서류

7. 영 제152조제1호에 따른 보상기준

③ 제2항제1호에 따른 안전성분석보고서에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다.

1. 방사성동위원소등의 개요 및 제원

2. 방사성동위원소등의 재질ㆍ구조 및 안전성평가

3. 방사성동위원소등의 성능시험계획서

④ 제2항제3호에 따른 방사선안전보고서에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다. 다만, 허가대상과 관련이 없는 사항은 기재하지 아니할 수 있다.

1. 시설 개요

2. 시설주변의 환경

3. 운영계획 개요

4. 방사선원의 특성ㆍ위치 및 제원

5. 안전시설 개요

6. 방사선취급방법 및 방사선안전관리계획

7. 예상피폭선량의 평가에 관한 절차ㆍ방법 및 결과

8. 주변환경에 대한 방사선 영향

9. 사고의 위험 및 그 대책

10. 방사성폐기물의 발생 및 처리계획

11. 방사선안전보고서의 작성자의 인적사항 및 자격

⑤ 제2항제4호에 따른 안전관리규정에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다. 다만, 허가대상과 관련이 없는 사항은 적지 아니할 수 있다. <개정 2016. 8. 8.>

1. 방사성동위원소등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항

2. 방사성동위원소등의 구매ㆍ사용 및 판매에 관한 사항

3. 방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항

4. 방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질(이하 “방사성물질등”이라 한다)에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항

5. 방사선안전관리 장비의 보관ㆍ관리 및 교정에 관한 사항

6. 방사선작업종사자 및 수시출입자에 대한 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항

7. 방사선작업종사자 및 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항

8. 방사선장해 발생 여부를 발견하기 위하여 필요한 조치에 관한 사항

9. 방사선장해를 받았거나 받을 우려가 있는 사람에 대하여 필요한 보건상 조치에 관한 사항

10. 법 제58조에 따른 기록과 그 비치에 관한 사항

11. 위험 시 조치에 관한 사항

12. 방사성동위원소등의 분실ㆍ도난 등 사고 시의 조치 및 사고예방에 관한 사항

13. 방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항

14. 그 밖에 방사선장해의 방어에 필요한 사항

⑥ 영 제79조에 따른 신청서를 제출받은 위원회는 「전자정부법」 제36조제1항에 따른 행정정보의 공동이용을 통하여 신청인의 사업자등록증을 확인하여야 한다. 다만, 신청인이 확인에 동의하지 아니하는 경우에는 사업자등록증 사본을 첨부하도록 하여야 한다.

⑦ 위원회는 법 제53조제1항 본문에 따른 방사성동위원소등의 생산허가를 하였을 때에는 별지 제43호서식 또는 별지 제44호서식의 허가증을 신청인에게 발급하여야 한다. 이 경우 생산허가의 대상이 특수형방사성물질인 경우에는 별지 제45호서식의 특수형방사성물질설계승인서를 함께 발급하여야 한다.


:::



