---
title: "원자력안전법"
author: "Radiation Safety Committee"
description: "「원자력안전법」[시행 2024. 11. 1.] [법률 제19826호, 2023. 10. 31., 일부개정]"
date: "2024-11-01"
date-modified: "2024-12-07"
categories: [원자력안전법]
---

## 제5장 RIㆍRG

### RIㆍRG 사용 등의 허가 등
::: {.callout-note title="제53조(방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등)" collapse="open" appearance="minimal"}
① 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)를 생산ㆍ판매ㆍ사용(소지ㆍ취급을 포함한다. 이하 같다) 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회의 허가를 받아야 한다. 허가받은 사항을 변경하려는 때에도 또한 같다. 다만, 총리령으로 정하는 일시적인 사용 장소의 변경과 그 밖의 경미한 사항을 변경하려는 때에는 이를 신고하여야 한다. \<개정 2013. 3. 23.\>

② 제1항에도 불구하고 총리령으로 정하는 용도 또는 수량 이하의 밀봉된 방사성동위원소 또는 총리령으로 정하는 용도 또는 용량 이하의 방사선발생장치를 사용 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회에 신고하여야 한다. 신고한 사항을 변경하려는 때에도 또한 같다. \<개정 2013. 3. 23.\>

③ 제1항에 따른 허가를 받으려는 자는 허가신청서에 안전성분석보고서, 품질보증계획서, 방사선안전보고서 및 안전관리규정과 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 하며, 제2항에 따른 신고를 하려는 자는 신고서에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다. 다만, 안전성분석보고서 및 품질보증계획서의 제출은 생산허가를 받으려는 자에 한한다. \<개정 2013. 3. 23.\>

④ 위원회는 제1항 단서 또는 제2항에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다. \<신설 2022. 6. 10.\>

⑤ 제1항에 따라 허가를 받은 자(이하 “허가사용자”라 한다) 및 제2항에 따라 신고를 한 자(이하 “신고사용자”라 한다)의 결격사유에 관하여는 제14조를 준용한다. 이 경우 제14조 본문 중 “제10조제1항의 허가를 받을 수 없다”는 “제53조제1항ㆍ제2항의 허가를 받거나 신고를 할 수 없다”로, 같은 조 제3호 중 “제17조에 따라 허가가 취소된 후”는 “제57조에 따라 허가취소ㆍ사용금지된 후”로, 같은 조 제4호 중 “임원 중에”는 “대표자가”로 본다. \<개정 2022. 6. 10.\>
:::

### 허가기준 등
::: {.callout-note title="제55조(허가기준 등)" collapse="open" appearance="minimal"}
① 제53조제1항에 따른 허가기준은 다음과 같다.

1.  생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비가 위원회규칙으로 정하는 기술기준에 적합할 것

2.  방사성동위원소 또는 그에 따라 오염된 물질 또는 방사선발생장치에 따라 발생한 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니할 것

3.  생산하려는 방사성동위원소등의 성능 및 품질보증계획서의 내용이 위원회가 정하여 고시하는 기준에 적합할 것

4.  대통령령으로 정하는 장비 및 인력을 확보할 것

② 제54조제1항에 따른 등록기준은 다음 각 호와 같다. \<개정 2013. 3. 23.\>

1.  총리령으로 정하는 대행업무 수행에 필요한 기술능력을 확보하고 있을 것

2.  대통령령으로 정하는 장비 및 인력을 확보할 것

3.  대행업무의 범위 및 업무대행규정이 총리령으로 정하는 기준에 적합할 것
:::

### 기준준수의무 등
::: {.callout-note title="제59조(기준준수의무 등)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 다음 사항에 관하여 위원회규칙으로 정하는 기술기준을 준수하여야 한다.

1. 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비

2. 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리 및 배출

3. 방사성동위원소등의 이동사용 및 판매

② 위원회는 사업소 안에서의 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설 또는 사용시설등의 위치ㆍ구조 및 설비, 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ처리 및 배출과 방사성동위원소등의 이동사용이나 판매가 제1항에 따른 기술기준에 적합하지 아니하다고 인정하면 허가사용자 및 신고사용자에게 해당 시설의 수리ㆍ개선ㆍ이전 또는 생산ㆍ사용의 정지, 취급방법의 변경과 그 밖의 안전에 필요한 조치를 명할 수 있다.

③ 허가사용자 및 그 종업원은 제53조제3항에 따른 안전관리규정을 준수하여야 하며, 업무대행자와 그 종업원은 제54조제3항에 따른 업무대행규정을 준수하여야 한다.
:::
