---
title: "기술기준"
author: "Radiation Safety Committee"
description: "「방사선 안전관리 등의 기술기준에 관한 규칙」[시행 2023. 9. 25.] [원자력안전위원회규칙 제50호, 2023. 9. 25., 일부개정]"
date: "2023-09-25"
date-modified: "2024-12-06"
categories: [시행규칙, 기술기준]
---

# 제1장 총 칙

### 방사선관리구역

::: {.callout-note title="제3조 (방사선관리구역)" collapse="open" appearance="minimal"}
① 법 제2조제16호에서 "원자력안전위원회규칙으로 정하는 값"이라 함은 다음 각호와 같다.

1.  외부방사선량률 : 1주당 400마이크로시버트

2.  공기중의 방사성물질의 농도 : 유도공기중농도

3.  물체표면의 오염도 : 허용표면오염도

② 외부방사선량률 등이 제1항의 규정에 의한 값을 초과할 우려가 있는 곳에 대하여는 사람의 출입을 관리하고 출입자에 대한 방사선의 장해를 방지하기 위하여 다음 각호의 조치를 하여야 한다.

1.  방사선관리구역의 설정

2.  벽ㆍ울타리 등의 구획물로 구획하여 별표 1에 의한 표지를 부착함으로써 다른 장소와 구별하고 방사선작업종사자외의 사람이 당해 구역에 출입하는 경우에는 방사선작업종사자의 지시에 따르도록 할 것

3.  바닥ㆍ벽 기타 사람이 접촉할 우려가 있는 물체의 표면이 방사성물질에 오염된 경우 그 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  방사선관리구역으로부터 사람이 퇴거하거나 물품을 반출하는 경우에는 인체 및 의복ㆍ신발 등 인체에 착용하고 있는 물품과 반출하는 물품(그 물품이 용기에 들어있거나 포장한 경우에는 그 용기 또는 포장)표면의 방사성물질의 오염도가 허용표면오염도의 10분의 1을 초과하지 아니하도록 할 것\
:::

# 제3장 RIㆍRG 안전관리

## 제1절 RIㆍRG 시설기준

### 제1관 개봉선원

### 개봉선원의 생산시설

::: {.callout-note title="제17조 (개봉선원의 생산시설)" collapse="open" appearance="minimal"}
① 개봉선원의 생산시설은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.

② 개봉선원 생산시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부는 내화구조로 하거나 불연재료를 사용할 것

2.  다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

            가.
생산시설 안의 사람이 상시 출입하는 장소에서의 방사선량

            나.
사업소의 경계에 인접하는 구역에서의 방사선량

3.  다음 각목의 기준에 따라 작업실을 설치할 것

            가.
작업실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

            나.
작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것

4.  다음 각목의 기준에 따라 오염검사실을 설치할 것

            가.
오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

            나.
오염검사실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분은 제3호 가목의 기술기준에 적합한 것으로 할 것

            다.
오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 장비를 갖출 것

5.  개봉선원을 생산하기 위한 방사선 조사시설(조사시설)에는 다음 각목의 기준에 따라 시설을 설치할 것

            가.
출입구에 방사선 조사중임을 자동적으로 표시하는 장치를 설치할 것

            나.
방사선 조사 여부에 따라 출입구가 개폐되는 연동장치를 할 것

            다.
내부를 상시 감시할 수 있는 장치를 할 것

            라.
사람의 출입을 제한하는 장치를 할 것

6.  시설의 경계에는 울타리 그 밖에 사람의 출입을 제한하는 시설을 할 것.
    다만, 제2호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7.  생산시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 그 밖에 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 사용시설등의 위치

::: {.callout-note title="제18조 (사용시설등의 위치)" collapse="open" appearance="minimal"}
개봉선원(개봉선원)의 사용시설등은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.
:::

### 사용시설 및 분배시설

::: {.callout-note title="제19조 (사용시설 및 분배시설)" collapse="open" appearance="minimal"}
① 개봉선원의 사용시설 및 분배시설의 구조 및 설비에 관한 기술기준은 다음 각 호와 같다.

1.  주요구조부는 내화구조로 하거나 불연재료를 사용할 것.
    다만, 원자력안전위원회가 정하여 고시하는 것은 그러하지 아니하다.

2.  사용시설은 개봉선원을 취급하기 위한 장비의 설치 및 작업 수행에 필요한 공간을 확보할 것

3.  다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

            가.
사용시설안 및 분배시설안의 사람이 상시 출입하는 장소에서의 방사선량

            나.
사업소의 경계에 인접하는 구역에서의 방사선량

4.  다음 각목과 같은 작업실을 설치할 것

            가.
작업실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

            나.
작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것.
다만, 원자력안전위원회가 정하는 것은 그러하지 아니하다.

5.  다음 각목의 1에 해당하는 오염검사실을 설치할 것. 다만, 인체 및 작업복ㆍ신발등 인체에 착용하는 물건의 표면이 방사성동위원소에 의하여 오염될 우려가 없도록 밀폐된 장치안에서 개봉선원을 사용 또는 분배하는 경우와 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

            가.
오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

            나.
오염검사실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분은 제4호 가목의 기술기준에 적합한 것으로 할 것

            다.
오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 기재(기재)를 갖출 것

6.  경계에는 울타리 기타 사람의 출입을 제한하는 시설을 할 것.
    다만, 제3호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7.  사용시설ㆍ분배시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

② 제1항의 규정은 누수의 조사, 곤충의 역학적 조사 또는 원료물질의 생산공정중 이동상황의 조사 등을 위하여 개봉선원을 광범위하게 분산ㆍ이동시키는 경우 또는 일시적으로 사용ㆍ분배하는 경우에는 이를 적용하지 아니한다.
:::

### 저장시설

::: {.callout-note title="제20조 (저장시설)" collapse="open" appearance="minimal"}
개봉선원 저장시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  저장시설의 구조는 다음 각목과 같이 할 것

            가.
저장실의 주요 구조부 및 출입문은 내화구조로 하거나 불연재료를 사용할 것

            나.
저장함은 내화구조로 하거나 불연재료를 사용할 것

2.  저장시설에는 제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  저장시설에 비치하는 용기는 다음 각목의 기준에 적합할 것

            가.
외부의 공기를 오염시킬 우려가 있는 개봉선원을 넣는 용기는 기밀구조일 것

            나.
액체상의 개봉선원을 넣는 용기의 구조는 액체가 누출되지 아니하도록 하고, 그 재료는 액체가 침투할 수 없는 것으로 할 것

            다.
액체상 또는 기체상의 개봉선원을 넣는 용기가 균열 또는 파손될 우려가 있는 때에는 밑받이ㆍ흡수재 기타 개봉선원에 의한 오염의 확산을 방지하기 위한 시설 또는 기구를 설치할 것

4.  저장시설의 문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 시설 또는 기구를 설치할 것

5.  저장시설의 경계에는 울타리 기타 사람의 출입을 제한하는 시설을 설치할 것

6.  저장실ㆍ저장함, 제3호의 용기 및 저장시설의 경계에 설치하는 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것\
:::

### 보관시설

::: {.callout-note title="제21조 (보관시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 보관시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조로 하거나 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  다음 각목의 기준에 적합한 보관설비를 갖출 것

            가.
외부와 구획된 구조로 할 것

            나.
문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 설비 또는 기구를 설치할 것

            다.
제20조제3호의 기술기준에 적합한 용기를 비치할 것.
다만, 방사성동위원소에 의하여 오염된 대형기계 등으로서 용기에 넣기가 곤란하여 오염확산을 방지하기 위한 조치를 취한 경우에는 그러하지 아니하다.

4.  보관설비, 제3호 다목의 용기 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 처리시설

::: {.callout-note title="제22조 (처리시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 처리시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조 또는 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  방사성동위원소 및 그에 의하여 오염된 물질을 소각하는 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 소각설비를 설치할 것

4.  방사성동위원소 및 그에 의하여 오염된 물질을 콘크리트 기타 고형화 재료에 의하여 고형화하는 경우에는 다음 각목에 정하는 바에 따라 고형화처리설비를 설치하는 외에 오염검사실 및 제23조제4호의 기준에 적합한 배기설비를 설치할 것

            가.
고형화처리설비는 방사성동위원소 및 그에 의하여 오염된 물질이 누설되거나 넘쳐 흐르지 아니하고 분진이 확산되지 아니하는 구조로 할 것

            나.
고형화처리설비는 액체가 침투하지 아니하고 부식에 강한 재료로 할 것

5.  소각로ㆍ오염검사실 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 배출시설

::: {.callout-note title="제23조 (배출시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 배출시설의 구조 및설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조 또는 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  액체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는바에 따라 배수설비를 설치할 것.
    다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

            가.
배수설비는 배수구에서 채취한 배출액의 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖추도록 할 것.
다만, 배수구에서의 배수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배수중 방사성동위원소의 농도를 감시하기 위한 배수감시설비를 하고 사업소의 경계외부에서의 수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하는 경우에는 그러하지 아니하다.

            나.
배수설비의 구조는 배출액이 누설되지 아니하도록 하고, 그 재료는 배출액이 침투할 수 없고 내식성이 강한 것으로 할 것

            다.
배수정화조는 배출액을 채취하여 배출액의 방사성동위원소 농도를 쉽게 측정할 수 있도록 이를 설치하고, 그 주위에는 울타리 등 사람의 출입을 제한하는 시설을 설치할 것

4.  기체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는 바에 따라 배기설비를 설치할 것. 다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

            가.
배기설비는 작업실안의 사람이 상시 출입하는 장소에서의 공기중 방사성동위원소의 농도를 유도공기중농도 이하로 하는 능력을 갖출 것

            나.
배기설비는 배기구의 배기중 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖출 것.
다만, 배기구에서의 배기중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배기중 방사성동위원소의 농도를 감시하기 위한 배기감시설비를 하고 사업소 등의 경계외부에서의 공기중 방사성동위원소 농도를 배출관리기준의 제한값이하로 하는 경우에는 그러하지 아니하다.

            다.
배기설비의 구조는 배기구외로 기체가 누설되지 아니하도록 하고, 그 재료는 내식성이 강한 것으로 할 것

            라.
배기설비에는 고장이 발생한 경우 방사성동위원소에 의하여 오염된 공기의 확산을 신속히 방지할 수 있는 장치를 할 것

5.  배수설비ㆍ배기설비와 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 보안관리 시설등

::: {.callout-note title="제23조의2 (개봉선원의 보안관리 시설등)" collapse="open" appearance="minimal"}
원자력안전위원회가 정하는 수량 이상의 개봉선원 생산시설 및 사용시설등에는 원자력안전위원회가 정하여 고시하는 바에 따라 보안관리 시설 또는 설비를 설치하여야 한다.
:::

## 제2절 RIㆍRG 취급기준

### 제1관 개봉선원

### 생산

::: {.callout-note title="제36조(생산)" collapse="open" appearance="minimal"}
개봉선원의 생산에 관한 기술기준은 다음 각호와 같다.\
1.
다음 각목에 해당하는 조치를 함으로써 방사선작업종사자 또는 수시출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

            가.
차폐벽이나 차폐물에 의하여 방사선을 차폐할 것

            나.
원격조작장치ㆍ집게 등을 사용하여 개봉선원과 인체 사이에 적당한 거리를 확보하고 차폐물을 이용하도록 할 것

            다.
면밀한 작업계획 및 숙달ㆍ훈련 등을 통하여 인체에 방사선이 피폭되는 시간을 단축할 것

2.  생산시설 안의 사람이 상시 출입하는 장소에서 사람이 호흡하는 공기중 방사성동위원소의 농도는 방사성동위원소에 의하여 오염된 공기를 정화하거나 배기함으로써 유도공기중농도를 초과하지 아니하도록 할 것

3.  생산시설 안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  생산시설 안에서는 작업복ㆍ신발ㆍ보호구 등을 착용하되, 이를 착용한채 작업실을 나가지 아니하도록 할 것

5.  생산시설을 나갈 때에는 인체에 착용하고 있는 물건표면에 대하여 방사성동위원소에 의한 오염상태를 검사하고 그 오염을 제거할 것

6.  생산시설에는 눈에 띄기 쉬운 장소에 방사선장해방지에 필요한 주의사항을 게시할 것
:::

### 사용 및 분배

::: {.callout-note title="제37조(사용 및 분배)" collapse="open" appearance="minimal"}
개봉선원의 사용 또는 분배에 관한 기술기준은 다음 각호와 같다.

1.  사용시설 또는 작업실에서 사용ㆍ분배할 것

2.  다음 각목에 해당하는 조치를 함으로써 방사선작업종사자 또는 수시 출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

           가.
차폐벽이나 차폐물에 의하여 방사선을 차폐할 것

           나.
원격조작장치ㆍ집게 등을 사용하여 개봉선원과 인체 사이에 적당한 거리를 확보하고 차폐물을 이용하도록 할 것

           다.
면밀한 작업계획 및 숙달ㆍ훈련 등을 통하여 인체에 방사선이 피폭되는 시간을 단축할 것

3.  작업실안의 사람이 상시 출입하는 장소에서 사람이 호흡하는 공기중 방사성동위원소의 농도는 방사성동위원소에 의하여 오염된 공기를 정화하거나 배기함으로써 유도공기중농도를 초과하지 아니하도록 할 것

4.  작업실 또는 오염검사실안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

5.  작업실안에서는 작업복ㆍ신발ㆍ보호구 등을 착용하되, 이를 착용한 채 작업실을 나가지 아니하도록 할 것

6.  작업실을 나갈 때에는 인체 및 작업복ㆍ신발ㆍ보호구 등 인체에 착용하고 있는 물건표면에 대하여 방사성동위원소에 의한 오염상태를 검사하고 그 오염을 제거할 것

7.  사용 또는 분배시설에는 눈에 띄기 쉬운 장소에 방사선장해방지에 필요한 주의사항을 게시할 것
:::

### 저장

::: {.callout-note title="38조 (저장) " collapse="open" appearance="minimal"}
개봉선원의 저장에 관한 기술기준은 다음 각호와 같다.

1.  용기에 넣어 저장시설에 저장할 것

2.  저장시설의 저장능력을 초과하여 저장하지 아니할 것

3.  제37조제2호 각목의 조치를 함으로써 방사선작업종사자 또는 수시출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

4.  저장함은 개봉선원의 보관중에는 그 운반을 제한하도록 할 것

5.  저장시설안의 사람이 호흡하는 공기중 방사성동위원소의 농도가 유도공기중 농도를 초과하지 아니하도록 할 것

6.  저장시설안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 다음 각목의 조치를 할 것

           가.
액체상의 방사성동위원소는 액체가 흘러넘치지 아니하는 구조 및 액체가 침투할 수 없는 재료로 된 용기에 넣을 것

           나.
액체상의 방사성동위원소를 넣은 용기가 균열 또는 파손될 우려가 있는 경우에는 밑받이ㆍ흡수재 기타 시설 또는 기구를 사용하여 방사성동위원소에 의한 오염의 확산을 방지할 것

7.  방사선관리구역에는 사람의 출입을 제한하는 조치를 할 것
:::

### 운반

::: {.callout-note title="39조 (운반) " collapse="open" appearance="minimal"}
① 개봉선원 및 그에 의하여 오염된 물질을 사업소 안에서 운반하는 경우의 기술기준은 다음 각호와 같다.

1.  용기에 봉입하여 운반할 것. 다만, 다음 각목의 조치를 하는 경우에는 그러하지 아니하다.

           가.
방사성동위원소에 의하여 오염된 것(당해 물질에 함유된 방사성동위원소의 농도가 허용표면오염도를 초과하지 아니하는 것에 한한다)으로서 방사성동위원소의 확산 또는 누설의 방지조치를 하거나 기타 원자력안전위원회가 정하여 고시하는 방사선장해방지를 위한 조치를 하여 운반하는 경우

           나.
방사성동위원소에 의하여 오염된 것으로서 대형기계 등 용기에 넣어 운반하기 어려운 것을 원자력안전위원회의 승인을 얻어 운반하는 경우

2.  방사성동위원소 및 그에 의하여 오염된 물질을 넣은 용기(제1호 가목 또는 나목의 규정에 의한 방사성동위원소에 의하여 오염된 것을 포함하며, 이하 이 조에서 "운반물"이라 한다) 및 이를 적재하는 차량이나 방사성동위원소 및 그에 의하여 오염된 물질을 운반하는 기계ㆍ기구(이하 이 조에서 "차량등"이라 한다)의 표면으로부터 10센티미터 및 차량의 외부표면으로부터 2미터 떨어진 위치의 방사선량률이 각각 원자력안전위원회가 정하여 고시하는 방사선량률을 초과하지 아니하도록 하고 운반물표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

3.  운반물을 차량등에 실을 때에는 운반중에 이동ㆍ전도 또는 전락 등에 의하여 운반물의 안전성이 손상되지 아니하도록 할 것

4.  동일한 차량등에 제98조의 규정에 의한 위험물과 운반물을 혼재하지 아니하도록 할 것

5.  운반물의 운반경로에는 표지를 설치하거나 감시인을 배치하는 등의 방법으로 운반에 종사하지 아니하는 자와 운반에 사용되지 아니하는 차량등의 출입을 제한할 것

6.  운반물을 운반하는 차량등은 서행하도록 할 것

7.  방사성동위원소의 취급에 관하여 지식과 경험을 갖춘 자를 동행하게 하거나 방사선장해방지를 위하여 필요한 감독을 하도록 할 것

8.  운반물 및 차량등에는 눈에 띄기 쉬운 곳에 별표 2에 의한 표지를 부착할 것

9.  방사선작업종사자외의 사람이 운반물의 운반에 종사하는 경우에는 그의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

10. 용기 밖의 운반물 등을 오염시킬 우려가 있는 방사성동위원소 및 그에 의하여 오염된 물질은 기밀구조의 용기에 넣어 운반할 것

11. 액체상태의 방사성동위원소 및 그에 의하여 오염된 물질은 그 액체의 침투나 부식이 잘 되지 아니하는 재료로 만들어지고 전복되기 어려운 구조로 된 용기에 넣어 운반할 것

② 제1항제3호의 조치의 전부 또는 일부를 하기가 곤란한 경우에는 원자력안전위원회의 승인을 얻은 조치로 이를 갈음할 수 있다.
이 경우 당해 운반물의 표면으로부터 10센티미터 및 2미터 떨어진 위치의 방사선량률은 각각 원자력안전위원회가 정하여 고시하는 방사선량률을 초과하여서는 아니된다.

③ 제1항제1호ㆍ제2호 및 제5호부터 제8호까지는 방사선관리구역안에서의 운반에 관하여는 이를 적용하지 아니한다.

④ 제1항의 규정은 방사성동위원소 및 그에 의하여 오염된 물질을 사용시설등의 안에서 운반하는 경우와 운반시간이 짧고 방사선장해의 우려가 없는 경우에는 이를 적용하지 아니한다.
:::

### 보관ㆍ처리 및 배출

::: {.callout-note title="제40조 (보관ㆍ처리 및 배출)" collapse="open" appearance="minimal"}
사업소안에서 방사성동위원소 또는 그에 의하여 오염된 물질을 보관ㆍ처리 및 배출하는 경우에는 다음 각호의 기술기준에 따르는 외에 제37조 각호(제1호를 제외한다)의 규정을 준용한다.
이 경우 동조제7호중 "사용 또는 분배시설"은 "보관ㆍ처리 및 배출시설"로 본다.

1.  기체상의 방사성동위원소 또는 그에 의하여 오염된 물질은 이를 배기설비로 정화하거나 배출할 것

2.  제1호의 방법으로 배출하는 경우에는 배기설비의 배기구에서의 배기중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 할 것.
    다만, 제23조제4호 나목 단서에 해당하는 경우에는 그러하지 아니하다.

3.  배기설비에 부착한 방사성동위원소를 제거하는 때에는 깔개ㆍ밑받이 또는 흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설ㆍ기구 및 보호구를 사용할 것

4.  액체상의 방사성동위원소 또는 그에 의하여 오염된 물질은 다음 각목의 1의 방법으로 보관ㆍ처리 또는 배출할 것

           가.
배수설비로 정화하거나 배출할 것

           나.
용기에 넣거나 고형화처리설비안에서 콘크리트 기타 고형화재료로 고형화하여 보관할 것

           다.
방사선장해방지를 위하여 원자력안전위원회가 정하여 고시하는 기준에 따라 소각할 것

5.  제4호 가목의 방법으로 배출하는 경우에는 배수설비의 배수구에 있어서의 배출액중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 할 것.
    다만, 제23조제3호 가목 단서에 해당하는 경우에는 그러하지 아니하다.

6.  제4호 가목의 방법으로 배출하는 경우 배출액을 처리하는 때 또는 동목의 배수설비의 부착물 또는 침전물 등의 방사성동위원소를 제거하는 때에는 깔개ㆍ밑받이 또는 흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설ㆍ기구 또는 보호구를 사용할 것

7.  제4호 나목의 방법으로 보관하는 경우 액체상의 방사성동위원소 및 그에 의하여 오염된 물질을 넣는 용기는 액체가 흘러 넘치지 아니하는 구조 및 액체가 침투할 수 없는 재료로 된 용기에 넣을 것

8.  제4호 나목의 방법중 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질을 용기에 넣어 보관하는 경우 당해 용기가 균열 또는 파손될 우려가 있는 때에는 밑받이ㆍ흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설 또는 기구를 사용하여 방사성동위원소의 오염의 확산을 방지할 것

9.  제4호 나목의 방법중 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질을 고형화하는 경우에는 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질의 확산 또는 누설을 방지할 수 있을 것
:::

### 개봉선원의 보안관리등

::: {.callout-note title="제40조의2 (개봉선원의 보안관리등)" collapse="open" appearance="minimal"}
원자력안전위원회가 정하는 수량 이상의 개봉선원을 생산ㆍ사용ㆍ분배ㆍ보관ㆍ저장 또는 운반하는 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 보안관리 및 그에 관련된 계획 등을 수립하여 이행하여야 한다.
:::

## 제3절 의료분야의 안전관리

### 의료방사선 방호 및 관리

::: {.callout-note title="제50조 (의료방사선 방호 및 관리) " collapse="open" appearance="minimal"}
① 방사성동위원소등을 인체에 사용함에 따른 방사선피폭(이하 "의료피폭"이라 한다)의 관리 대상 및 범위는 다음 각 호와 같다.

1.  진료 목적으로 받는 개인의 피폭

2.  진료를 받은 임산부의 태내 배태아 또는 모유 수유하는 환자의 유아가 받는 피폭

3.  진료 환자를 간병하는 가족이나 친지가 받는 피폭

4.  방사선을 이용한 의생명 연구 대상으로 참여하는 연구 자원자가 받는 피폭

② 방사성동위원소등을 인체에 사용하는 자는 방사선피폭으로 인한 해로움보다 이로움이 크도록 하여야 한다.

③ 제2항에 따른 사용자는 방사선 피폭이 경제적, 사회적 인자를 고려해 합리적으로 달성할 수 있는 범위에서 낮게 유지되도록 하여야 한다.
:::

### 사용자의 책임

::: {.callout-note title="제51조 (사용자의 책임)" collapse="open" appearance="minimal"}
① 방사성동위원소등을 인체에 사용하는 자는 의료방사선 방호에 충분한 전문성을 가진 의사가 의료방사선을 사용하도록 하여야 한다.

② 방사성동위원소등을 인체에 사용하는 자는 의사의 의뢰와 함께 방사선방호 대책 수립을 확인하고 원자력안전위원회가 정하여 고시하는 바에 따라 의료피폭을 받는 사람 또는 법적 보호자가 적절하게 이해하고 동의한 경우가 아니면 의료피폭을 받지 않도록 하여야 한다.

③ 제1항에 따른 사용자는 의도되지 아니한 또는 사고에 의한 의료피폭 가능성을 최소화하기 위한 모든 가용한 수단을 강구해야 하며, 이러한 의료피폭이 있는 경우 즉시 조사를 수행하고 시정조치를 하여야 한다.

④ 제1항에 따른 사용자는 방사선 사용시설에서 이행하는 의료피폭의 정당화와 최적화에 대하여 원자력안전위원회가 정하여 고시하는 바에 따라 주기적으로 검토하여야 하며 의료피폭 기록을 유지하여야 한다.
:::

### 의료방사선 품질관리

::: {.callout-note title="제52조 (의료방사선 품질관리) " collapse="open" appearance="minimal"}
① 진료의 목적으로 방사성동위원소등을 인체에 사용하는 자는 환자의 피폭방사선량 또는 투여 방사능량을 의사의 처방대로 유지하여야 한다.

② 제1항에 따른 사용자는 원자력안전위원회가 고시하는 바에 따라 방사선 진료장비를 유지ㆍ관리하여야 하며, 방사선안전관리자와 별도로 의료방사선 품질관리를 위한 전문인력을 두어야 한다.
:::

### RI 투여환자 안전관리

::: {.callout-note title="제53조 (방사성동위원소 투여환자 안전관리)" collapse="open" appearance="minimal"}
① 진료의 목적으로 방사성동위원소를 인체에 사용하는 자는 체내에 잔류하는 방사능 또는 인체표면 1m 거리에서의 방사선량률이 원자력안전위원회가 정하여 고시하는 수량을 초과하는 환자를 일반환자와 격리하여 입원시켜야 한다.

② 제1항에 따른 사용자는 환자의 입원실에 전용 화장실을 설치하여야 한다.

③ 제1항에 따른 사용자가 진료환자의 배설물을 배출하는 경우에는 원자력안전위원회가 정하여 고시하는 방법에 따라야 한다.
:::

### 임신 또는 모유 수유중인 여성

::: {.callout-note title="제54조 (임신 또는 모유 수유중인 여성)" collapse="open" appearance="minimal"}
진료의 목적으로 방사성동위원소등을 인체에 사용하는 자는 방사선 진료를 받는 여성 환자가 임신했거나 임신 했을 가능성이 있는 경우, 또는 모유 수유중인 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 적합한 방사선방호 절차를 수립하여 이행하여야 한다.
:::

# 제5장 방사성물질등의 포장 및 운반의 안전관리

## 제1절 운반물 및 운반용기의 기술기준

### 운반물의 종류

::: {.callout-note title="제90조 (운반물의 종류)" collapse="open" appearance="minimal"}
운반하기 위하여 제시된 방사성물질등과 그 포장(이하 "운반물"이라 한다)의 종류는 방사성물질등의 종류와 그 한도량에 따라 다음 각호와 같이 분류한다.

1.  L형 운반물

2.  IP형 운반물(IP형 운반물은 IP-1형 운반물, IP-2형 운반물 또는 IP-3형 운반물로 구분한다)

3.  A형 운반물

4.  B형 운반물{B형 운반물은 B(U)형 운반물 또는 B(M)형 운반물로 구분한다}

5.  C형 운반물

6.  핵분열성물질운반물
:::

### 운반물별 방사성물질의 한도

::: {.callout-note title="제91조 (운반물별 방사성물질의 한도량) " collapse="open" appearance="minimal"}
① L형 운반물의 방사성물질등과 그 한도량은 다음 각호와 같다.

1.  천연우라늄ㆍ감손우라늄 또는 천연토륨으로 제조된 물품인 경우로서 우라늄 또는 토륨의 외부표면이 금속 기타 견고한 물질로 된 비활성외장물로 싸여 있는 경우에는 한도량에 제한이 없음

2.  천연우라늄ㆍ감손우라늄 또는 천연토륨으로 제조된 물품 이외의 방사성물질인 경우에는 그 한도량이 다음 각목의 값을 초과하지 아니하도록 할 것

           가.
당해 방사성물질이 봉입되어 있거나 시계ㆍ전자기기 등 다른 제품의 구성부품으로 되어 있는 경우에는 각 품목 및 운반물에 대하여 별표 3의 2란 및 3란에 의한 값

           나.
당해 방사성물질이 봉입되어 있지 아니하거나 다른 제품의 구성부품으로 되어 있지 아니한 경우에는 별표 3의 4란에 의한 값

3.  원자력안전위원회가 정하여 고시하는 핵분열성물질의 면제수량 또는 그 비율에 해당하는 물질

② IP형 운반물의 방사성물질등과 그 한도량은 다음 각호와 같다.

1.  운반물의 방사성물질이 저준위 비방사능물질인 경우 저준위 비방사능물질이 차폐되지 아니한 상태에서 당해 운반물로부터 3미터 지점의 방사선량률이 시간당 10밀리시버트를 초과하지 아니하도록 할 것

2.  운반물의 방사성물질이 표면오염물체인 경우 표면오염물체가 차폐되지 아니한 상태에서 당해 운반물로부터 3미터 지점의 방사선량률이 시간당 10밀리시버트를 초과하지 아니하도록 할 것

3.  비가연성 고체상태인 제2종 저준위 비방사능물질 또는 제3종 저준위 비방사능물질이 내장된 운반물을 항공운반하는 경우 그 방사능은 특수형방사성물질 이외의 물질에 적용하는 A값(이하 "A2"라 한다.)의 3천배를 초과하지 아니하도록 할 것

4.  운반물의 방사성물질의 수량은 별표 4에서 규정하는 지정된 운반수단에 대한 방사능 제한값을 초과하지 아니하도록 할 것

③ A형 운반물의 방사성물질등과 그 한도량은 다음 각호와 같다.

1.  종류 및 방사능을 명확히 알고 있는 단일 방사성 핵종인 경우에는 그 한도량이 다음 각목의 값을 초과하지 아니하도록 할 것

           가.
특수형방사성물질 : 특수형방사성물질에 적용하는 A값(이하 "A1"이라 한다.)

           나.
특수형방사성물질 이외의 방사성물질 : A₂

2.  종류와 각각의 방사능을 알고 있는 혼합 방사성 핵종의 경우에는 각 핵종별 A₁과 A₂에 대한 비의 합계가 1을 초과하지 아니하도록 할 것

④ B형 운반물의 방사성물질등과 그 한도량은 다음 각호와 같다.

1.  해당 설계승인서에서 규정하는 제한값을 초과하지 아니하도록 할 것

2.  항공기에 의하여 운반하는 경우 제1호의 기준 및 다음 각목에 의한 값을 초과하지 아니하도록 할 것

           가.
저분산성방사성물질의 경우에는 해당 설계승인서에서 규정하는 값

           나.
특수형방사성물질의 경우에는 A₁의 3천배 또는 A₂의 10만배중에서 낮은 값

           다.
가목 및 나목 이외의 경우에는 A₂의 3천배

⑤ C형 운반물의 방사성물질등과 그 한도량은 제4항제2호 나목 및 다목에서 규정한 방사성물질등과 그 한도량을 초과하는 것으로서 당해 운반물을 항공기에 의하여 운반하는 경우 해당 설계승인서에서 규정하는 제한값을 초과하지 아니하여야 한다.

⑥ 핵분열성물질운반물은 핵분열성물질이 포함된 운반물로서 그 한도량은 다음 각호와 같다.

1.  육불화우라늄(UF6)이 들어있지 아니한 핵분열성물질운반물의 경우에는 설계승인서에서 규정하는 제한값을 초과하지 아니하도록 할 것

2.  육불화우라늄이 들어있는 핵분열성물질운반물의 방사성물질 한도량은 다음 각목의 기준에 적합하도록 할 것

           가.
제1호에서 규정하는 제한값을 초과하지 아니할 것

           나.
운반물의 육불화우라늄은 사용장소 주변의 최대온도를 감안하여 포화상태에 이르지 아니하도록 할 것

           다.
육불화우라늄은 고체상태를 유지하고 내부압력은 주위압력보다 낮게 유지할 것
:::

### 운반용기의 종류

::: {.callout-note title="제92조 (운반용기의 종류)" collapse="open" appearance="minimal"}
① 운반용기의 종류는 운반하고자 하는 운반물의 종류에 따라 구분하되, 제90조의 규정에 의한 운반물의 종류별로 각각 다음과 같이 구분한다.

1.  L형 운반용기

2.  IP형 운반용기(IP-1형 운반용기, IP-2형 운반용기 및 IP-3형 운반용기로 구분한다)

3.  A형 운반용기

4.  B형 운반용기{B(U)형 운반용기 및 B(M)형 운반용기로 구분한다}

5.  C형 운반용기

6.  핵분열성물질운반용기

② 제1항의 규정에 의한 각 운반용기의 기술기준은 원자력안전위원회가 정하여 고시한다.
:::

### 저준위 비방사능물질 및 표면오염물체의 구분

::: {.callout-note title="제93조 (저준위 비방사능물질 및 표면오염물체의 구분)" collapse="open" appearance="minimal"}
① 저준위 비방사능물질은 제1종 저준위 비방사능물질, 제2종 저준위 비방사능물질 및 제3종 저준위 비방사능물질로 구분한다.

② 표면오염물체는 제1종 표면오염물체 및 제2종 표면오염물체로 구분한다.

③ 제1항 및 제2항의 규정에 의한 저준위 비방사능물질 및 표면오염물체의 구분기준은 원자력안전위원회가 정하여 고시한다.
:::
