project:
  type: website
  output-dir: docs

website:
  title: "방사선안전관리"
  
  navbar:
    logo: KSNM_logo.png
    left:
      - text: 블로그
        href: index.qmd
      - text: "정기검사"
        href: posts/inspection/inspection.qmd   
      - text: "규제개선 제안사항"
        href: posts/regulation/index.qmd
      - text: "방사선안전 이슈"
        href: posts/issue/index.qmd
      - text: "방사선안전관리 총람"
        href: posts/compendium/index.qmd   
      - text: "관련 사이트"
        href: posts/Link.qmd           
    right:
      - posts/about.qmd
      - icon: github
        href: https://github.com/
    search: true
    
  sidebar:
    - title: "정기검사"
      collapse-level: 4
      contents:
        - posts/inspection/inspection.qmd
        - section: "지적사항"
          href: posts/comments/index.qmd
          contents:
          - section: "교육훈련"
            href: posts/inspection/education_training/education_training.qmd
            contents:
            - posts/inspection/education_training/radiation_workers_inductory.qmd    
            - posts/inspection/education_training/radiation_workers_regular.qmd               
            - posts/inspection/education_training/licensees_continuing.qmd 
          - section: "건강진단"
            href: posts/inspection/health_examination/health_examination.qmd          
            contents:
            - posts/inspection/health_examination/health_examination_new_workers.qmd
            - posts/inspection/health_examination/health_examination_workers.qmd            
            - posts/inspection/health_examination/health_examination_retired.qmd            
          - section: "선량ㆍ오염측정"
            href: posts/inspection/dose_contamination_measurement/dose_contamination_measurement.qmd                    
            contents:
            - posts/inspection/dose_contamination_measurement/surface_contamination.qmd                 
          - section: "자체처분"
            contents:
            - posts/comments/disposal/disposal.qmd
          - section: "시설검사"
            contents:
            - posts/comments/facilities/facilities.qmd
          - section: "변경신고"
            contents:
            - posts/comments/change_notification/change_notification.qmd
           
          - section: "인력기준"
            contents:
            - posts/comments/licenses_criteria/licenses_criteria.qmd
          - section: "피폭관리"
            contents:
            - posts/comments/damage_management/damage_management.qmd 
          - section: "변경허가"
            contents:
            - posts/comments/change_approval/change_approval.qmd   
          - section: "기술기준"
            contents:
            - posts/comments/technical_criteria/technical_criteria.qmd
          - section: "안전관리규정"
            contents:
            - posts/comments/management_requirement/management_requirement.qmd               
          - section: "기록비치"
            contents:
            - posts/comments/recording/recording.qmd 
          - section: "보고"
            contents:
            - posts/comments/reporting/reporting.qmd
    - title: "규제개선 제안사항"
      collapse-level: 1
      contents:
        - posts/regulation/index.qmd
        - section: "RI운송"
          contents:
          - posts/regulation/transport/transport_inside.qmd
        - section: "보고"
          contents:
          - posts/regulation/reporting/reporting_duplicated.qmd   
    - title: "방사선안전 이슈"
      collapse-level: 1
      contents:
        - posts/issue/index.qmd
        - section: "영상검사 적정성평가"
          contents:
          - posts/issue/approriate/approriate.qmd
    - title: "방사선안전관리 총람"
      collapse-level: 1
      contents:
        - posts/compendium/index.qmd
        - section: "법령·규칙·고시"
          contents:
          - posts/compendium/law/nuclear_safety_act.qmd    
          - posts/compendium/law/enforcement_decree_nuclear_safety_act.qmd        
          - posts/compendium/law/nuclear_safety_enforcement_rule.qmd
          - posts/compendium/law/technical_criteria.qmd    
          - posts/compendium/law/medical_use_criteria.qmd
          - posts/compendium/law/radiation_protection_criteria.qmd
          - posts/compendium/law/notice_establishing_safety_management_regulation.qmd   
          - posts/compendium/law/dma_radiation_safety_management_regulation.qmd      
        - section: "방사선안전관리자업무"
          contents:
          - posts/compendium/duty/duty.qmd   
        - section: "방사선안전관리자 인력"
          contents:
          - posts/compendium/resource/resource.qmd
    - title: "관련 사이트"
      contents:
        - posts/Link.qmd    

format:
  html:
    theme: cosmo
    relative-resources: true
    css: styles/tooltip.css
    # bibliography: references.bib
    csl: references/nuclear-medicine-and-molecular-imaging.csl
    toc: true
    toc-depth: 4
    date-format: "YYYY.M.D"
    date-modified-format: "YYYY.M.D"    
    include-after-body:
      - text: |
          <script src="/scripts/tooltip.js"></script>
    
    comments:
      utterances:
        repo: RadiationSafetyNM/website