project:
  type: website
  output-dir: docs

website:
  title: "헥의학 방사선안전관리"
  navbar:
    logo: KSNM_logo.png
    left:
      - text: 블로그
        href: index.qmd
      - text: 정당화
        href: posts/justification/index.qmd
      - text: 최적화
        href: posts/optimization/index.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css
    comments:
      utterances:
        repo: RadiationSafetyNM/website

editor: visual

