project:
  type: website
  output-dir: docs

website:
  title: "방사선안전관리"
  
  navbar:
    logo: KSNM_logo.png
    left:
      - text: "사이트사용법"
        href: posts/manual.qmd
      - text: "법령·규칙·고시"
        href: posts/law/law.qmd
      - text: "안전관리실무"
        href: posts/practice/index.qmd           
      - text: "규제개선·제안사항"
        href: posts/regulation/index.qmd
      - text: "블로그"
        href: index.qmd        
      - text: "관련 사이트"
        href: posts/Link.qmd           
    right:
      - icon: github
        href: https://github.com/
    search: true
    
  sidebar:
    - title: "법령·규칙·고시"
      contents:
        - posts/law/law.qmd
        - posts/law/nuclear_safety_act.qmd    
        - posts/law/enforcement_decree_nuclear_safety_act.qmd        
        - posts/law/nuclear_safety_enforcement_rule.qmd
        - posts/law/technical_criteria.qmd    
        - posts/law/medical_use_criteria.qmd
        - posts/law/radiation_protection_criteria.qmd
        - posts/law/notice_establishing_safety_management_regulation.qmd   
        - posts/law/exposure_management_regulation.qmd
        - posts/law/disposal_regulation.qmd           
        - posts/law/dma_radiation_safety_management_regulation.qmd

    - title: "안전관리실무"
      contents:
        - posts/practice/index.qmd
        - section: "방사선안전관리자업무"
          contents:
          - posts/practice/duty/duty.qmd
        - section: "정기검사 수검준비"
          href: posts/inspection/guidelines/guidelines.qmd
          contents:
          - posts/inspection/guidelines/guidelines.qmd   
          - section: "지적권고사항"
            href: posts/inspection/inspection.qmd
            contents:
            - section: "교육훈련"
              href: posts/inspection/education_training/education_training.qmd
              contents:
              - posts/inspection/education_training/radiation_workers_inductory.qmd    
              - posts/inspection/education_training/radiation_workers_regular.qmd               
              - posts/inspection/education_training/licensees_continuing.qmd              
            - section: "건강진단"
              href: posts/inspection/health_examination/health_examination.qmd          
              contents:
              - posts/inspection/health_examination/health_examination_new_workers.qmd
              - posts/inspection/health_examination/health_examination_workers.qmd            
              - posts/inspection/health_examination/health_examination_retired.qmd            
            - section: "기록비치"
              href: posts/inspection/recording_keeping/recording_keeping.qmd          
              contents:
              - posts/inspection/recording_keeping/recording_keeping_noncompliance.qmd             
            - section: "안전관리규정"
              href: posts/inspection/safety_management_regulation/safety_management_regulation.qmd          
              contents:
              - posts/inspection/safety_management_regulation/safety_management_regulation_noncompliance.qmd             
            - section: "선량ㆍ오염측정"
              href: posts/inspection/dose_contamination_measurement/dose_contamination_measurement.qmd                    
              contents:
              - posts/inspection/dose_contamination_measurement/surface_contamination.qmd                 
            - section: "기술기준"
              href: posts/inspection/technical_criteria/technical_criteria.qmd
              contents:
              - posts/inspection/technical_criteria/technical_criteria_contamination_measurement.qmd  
              - posts/inspection/technical_criteria/technical_criteria_quality_management.qmd
              - posts/inspection/technical_criteria/technical_criteria_warning.qmd   
            - section: "변경허가"
              href: posts/inspection/license_amendment/license_amendment.qmd
              contents:
              - posts/inspection/license_amendment/license_amendment_limit_over.qmd   
            - section: "자체처분"
              href: posts/inspection/self_disposal/self_disposal.qmd          
              contents:
              - posts/inspection/self_disposal/self_disposal_amount_mismatch.qmd  
            - section: "시설검사"
              href: posts/inspection/facility_inspection/facility_inspection.qmd
              contents:
              - posts/inspection/facility_inspection/facility_inspection_conducting.qmd
            - section: "변경신고"
              href: posts/inspection/alteration_reporting/alteration_reporting.qmd
              contents:
              - posts/inspection/alteration_reporting/alteration_reporting_conducting.qmd
            - section: "장비ㆍ인력"
              href: posts/inspection/equipment_human_resources/equipment_human_resources.qmd          
              contents:
              - posts/inspection/equipment_human_resources/equipment_human_resources_improper.qmd
            - section: "피폭관리"
              href: posts/inspection/exposure_control/exposure_control.qmd
              contents:
              - posts/inspection/exposure_control/exposure_control_improper.qmd 
            - section: "보고"
              href: posts/inspection/reporting/reporting.qmd
              contents:
              - posts/inspection/reporting/reporting_omission.qmd              

    - title: "규제개선·제안사항"
      contents:
        - posts/regulation/index.qmd
        - section: "검토중인 사항"
          href: posts/regulation/review/review.qmd
          contents:
            - posts/regulation/review/review1.qmd
            - posts/regulation/review/review2.qmd  
        - section: "제안된 사항"
          href: posts/regulation/suggested/suggested.qmd
          contents:
            - posts/regulation/suggested/transport_inside.qmd
            - posts/regulation/suggested/reporting_duplicated.qmd   
            - posts/regulation/suggested/approriate.qmd


    - title: "관련 사이트"
      contents:
        - posts/Link.qmd    

format:
  html:
    theme: cosmo
    relative-resources: true
    css: styles/tooltip.css
    # bibliography: references.bib
    csl: references/nuclear-medicine-and-molecular-imaging.csl
    toc: true
    toc-depth: 4
    date-format: "YYYY.M.D"
    date-modified-format: "YYYY.M.D"    
    include-after-body:
      - text: |
          <script src="/scripts/tooltip.js"></script>
    
    comments:
      utterances:
        repo: RadiationSafetyNM/website