---
title: "시설검사"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 시설검사]
---

시설검사와 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제56조(검사)

::: {.callout-note title="제56조(검사)" collapse="open" appearance="minimal"}
① 허가사용자 및 업무대행자는 방사성동위원소등의 생산ㆍ판매ㆍ사용ㆍ이동사용 또는 대행업무를 대통령령으로 정하는 바에 따라 위원회의 검사를 받아야 한다. 다만, 대통령령으로 정하는 바에 따라 검사가 면제되는 경우에는 그러하지 아니하다.

② 위원회는 제1항에 따른 검사결과 다음 각 호의 어느 하나에 해당하면 허가사용자 또는 업무대행자에게 그 시정 또는 보완을 명할 수 있다.

1. 제55조제1항에 따른 허가기준 또는 제55조제2항에 따른 등록기준에 미달될 때

2. 제53조제3항에 따른 안전관리규정 또는 제54조제3항에 따른 업무대행규정을 위반하였을 때
:::

## 원자력안전법 시행령

### 제85조(시설검사)

::: {.callout-note title="제85조(시설검사)" collapse="open" appearance="minimal"}
① 법 제56조제1항 본문에 따라 허가사용자는 방사성동위원소등의 생산시설ㆍ사용시설ㆍ분배시설ㆍ저장시설ㆍ보관시설ㆍ처리시설 및 배출시설(이하 “사용시설등”이라 한다)을 설치 또는 변경한 경우에는 해당 시설에 대하여 위원회의 검사를 받아야 한다.

② 허가사용자가 다음 각 호의 어느 하나에 해당하는 사용시설등에 대하여 총리령으로 정하는 바에 따라 자체점검을 하고, 그 자체점검결과에 대하여 위원회의 서면심사를 받아 합격한 경우에는 해당 자체점검으로 제1항에 따른 시설검사를 갈음한다. 다만, 해당 사용시설등을 최초로 검사하는 경우에는 그러하지 아니하다. <개정 2013. 3. 23.>

1. 법 제60조제1항 본문에 따라 승인을 받은 방사선기기(별도의 방사선차폐체를 설치하지 아니하고 취급할 수 있는 것만 해당한다)를 설치한 사용시설등

2. 법 제60조제1항 본문에 따라 승인을 받은 방사선발생장치로서 총리령으로 정하는 장치를 설치한 사용시설등

3. 370기가베크렐 미만의 밀봉된 방사성동위원소의 사용시설등

③ 업무대행자가 제2항 각 호의 어느 하나에 해당하는 사용시설등에 대하여 총리령으로 정하는 바에 따라 감리(監理)를 실시하고, 그 감리 결과에 대하여 위원회의 서면심사를 받아 합격한 경우에는 그 감리로 제1항에 따른 시설검사를 갈음한다. 다만, 해당 사용시설등을 최초로 검사하는 경우에는 그러하지 아니하다. <개정 2013. 3. 23.>

④ 제1항에 따른 검사, 제2항에 따른 자체점검 또는 제3항에 따른 감리 결과에 대한 서면심사 결과 그 사용시설등의 설치 또는 변경이 법 제53조제1항에 따른 허가 내용(법 제99조에 따른 조건을 포함한다)과 일치하는 경우에는 합격으로 한다.

⑤ 위원회는 제2항 또는 제3항에 따라 제출된 자체점검 결과 또는 감리 결과에 대한 서면심사 결과 불합격한 사용시설등에 대해서는 제1항에 따른 검사를 하여야 한다.
:::