---
title: "건강진단"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 건강진단]
---

건강진단과 관련된 법령ㆍ규칙ㆍ고시는 아래와 같습니다.

## 원자력안전법

### 제91조 방사선장해방지조치

::: {.callout-note title="제91조(방사선장해방지조치)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

4.  방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치

② 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.

③ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.
:::

### 제91조 방사선장해방지조치 \[시행일: 2025. 4. 23.\]

::: {.callout-note title="제91조(방사선장해방지조치) [시행일: 2025. 4. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[① 원자력관계사업자(신고사용자는 제외한다)는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

<p style="text-indent: 20px;">

[4. 삭제]{style="color:red;"} \<2024. 10. 22.\>

</p>

[② 원자력관계사업자는 대통령령으로 정하는 바에 따라 방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치를 하여야 한다.]{style="color:red;"} \<신설 2024. 10. 22.\>

[③ 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

[④ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

\[시행일: 2025. 4. 23.\] 제91조
:::

## 원자력안전법 시행령

### 제132조 건강진단

::: {.callout-note title="제132조(건강진단)" collapse="open" appearance="minimal"}
① 법 제91조제1항제2호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설의 방사선작업종사자 및 수시출입자에 대하여 건강진단을 실시하여야 한다. <개정 2013. 3. 23., 2013. 8. 16., 2016. 4. 12.>

② 원자력관계사업자는 제1항의 건강진단의 결과에 관하여 기록의 작성ㆍ보존 그 밖에 총리령으로 정하는 조치를 하여야 한다. <개정 2013. 3. 23.>
:::

## 원자력안전법 시행규칙

### 제121조 건강진단

::: {.callout-note title="제121조(건강진단)" collapse="open" appearance="minimal"}
① 영 제132조제1항에 따라 실시하는 건강진단에서는 다음 각 호의 사항을 검사해야 한다. <개정 2013. 8. 16., 2021. 10. 20.>

1. 직업력 및 노출력

2. 방사선 취급과 관련된 병력

3. 임상검사 및 진찰

가. 임상검사: 말초혈액 중의 백혈구 수, 혈소판 수 및 혈색소의 양

나. 진찰: 눈, 피부, 신경계 및 조혈계(혈구형성계통) 등의 증상

4. 말초혈액도말검사와 세극등현미경검사(제1호부터 제3호까지의 규정에 따른 검사 결과 건강수준의 평가가 곤란하거나 질병이 의심되는 경우에만 해당한다)

② 영 제132조제1항에 따른 건강진단의 실시시기는 다음 각 호와 같다. <개정 2013. 8. 16., 2016. 8. 8.>

1. 방사선작업종사자 및 수시출입자가 최초로 해당 업무에 종사하기 전

2. 해당 업무에 종사 중인 방사선작업종사자 및 수시출입자에 대하여는 매년. 다만, 전년도 건강진단을 실시한 때부터 12개월간의 피폭방사선량이 영 별표 1 제3호에 따른 선량한도를 초과하지 아니하는 경우에는 그 해의 제1항제1호 및 제2호에 대한 검사를 생략할 수 있다.

3. 방사선작업종사자 및 수시출입자의 피폭방사선량이 영 별표 1에 따른 선량한도를 초과한 때

③ 제2항에도 불구하고 「산업안전보건법」 제130조제2항 본문에 따라 방사선 유해인자에 대한 배치전건강진단을 받은 경우에는 제2항제1호의 시기에 실시하는 건강진단을 받은 것으로 보고, 같은 조 제2항 각 호 외의 부분 본문에 따라 방사선 유해인자에 대한 특수건강진단을 받은 경우에는 제2항제2호의 시기에 실시하는 건강진단을 받은 것으로 본다. <신설 2018. 5. 3., 2023. 3. 9.>
:::
