---
title: "변경신고"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 변경신고, 경미한사항]
---

변경신고와 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제53조 방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등

::: {.callout-note title="제53조(방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등)" collapse="open" appearance="minimal"}
① 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)를 생산ㆍ판매ㆍ사용(소지ㆍ취급을 포함한다. 이하 같다) 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회의 허가를 받아야 한다. 허가받은 사항을 변경하려는 때에도 또한 같다. 다만, 총리령으로 정하는 일시적인 사용 장소의 변경과 그 밖의 경미한 사항을 변경하려는 때에는 이를 신고하여야 한다.\<개정 2013.3.23.\>

② 제1항에도 불구하고 총리령으로 정하는 용도 또는 수량 이하의 밀봉된 방사성동위원소 또는 총리령으로 정하는 용도 또는 용량 이하의 방사선발생장치를 사용 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회에 신고하여야 한다. 신고한 사항을 변경하려는 때에도 또한 같다.\<개정 2013.3.23.\>

③ 제1항에 따른 허가를 받으려는 자는 허가신청서에 안전성분석보고서, 품질보증계획서, 방사선안전보고서 및 안전관리규정과 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 하며, 제2항에 따른 신고를 하려는 자는 신고서에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다. 다만, 안전성분석보고서 및 품질보증계획서의 제출은 생산허가를 받으려는 자에 한한다.\<개정 2013.3.23.\>

④ 위원회는 제1항 단서 또는 제2항에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다.\<신설 2022.6.10.\>

⑤ 제1항에 따라 허가를 받은 자(이하 “허가사용자”라 한다) 및 제2항에 따라 신고를 한 자(이하 “신고사용자”라 한다)의 결격사유에 관하여는 제14조를 준용한다. 이 경우 제14조 본문 중 “제10조제1항의 허가를 받을 수 없다”는 “제53조제1항ㆍ제2항의 허가를 받거나 신고를 할 수 없다”로, 같은 조 제3호 중 “제17조에 따라 허가가 취소된 후”는 “제57조에 따라 허가취소ㆍ사용금지된 후”로, 같은 조 제4호 중 “임원 중에”는 “대표자가”로 본다.\<개정 2022.6.10.\>
:::

## 원자력안전법 시행규칙

### 제89조(경미한 사항의 변경신고)

::: {.callout-note title="제89조(경미한 사항의 변경신고)" collapse="open" appearance="minimal"}
① 법 제63조제1항 단서에서 “총리령으로 정하는 경미한 사항”이란 다음 각 호의 어느 하나에 해당하는 사항을 말한다. <개정 2015. 7. 21., 2016. 8. 8.>

1. 허가를 받은 사람의 성명 및 주소(법인인 경우에는 그 명칭ㆍ주소 및 그 대표자의 성명)

2. 방사성폐기물관리시설등을 설치하는 사업소의 명칭

3. 방사성폐기물관리시설등의 공사일정

4. 제87조제3항에 따른 안전성분석보고서의 기재사항 중 같은 항 제1호ㆍ제4호 또는 제7호에 관한 사항

5. 제87조제5항에 따른 건설 및 운영에 관한 품질보증계획서의 기재사항 중 제4조제4항제2호부터 제18호까지에 관한 사항

6. 안전성분석보고서, 안전관리규정, 건설 및 운영에 관한 품질보증계획서, 방사성폐기물관리시설등의 건설ㆍ운영계획에 관한 서류 및 방사성폐기물관리시설등의 건설ㆍ운영에 관한 기술능력에 관한 설명서의 내용 중 품질보증체제의 조직이 아닌 일반조직 변경에 관한 사항

7. 오기(誤記), 누락 또는 그 밖에 이에 준하는 사유로서 그 변경 근거가 분명한 사항

② 법 제63조제1항 단서에 따라 변경신고를 하려는 자는 변경 후 20일 이내에 별지 제4호서식의 신고서에 다음 각 호의 서류를 첨부하여 위원회에 제출하여야 한다. <개정 2016. 8. 8.>

1. 변경사항을 증명하는 서류

2. 허가증
:::
