---
title: "변경신고 미신고"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기점검 지적사항, 변경신고, 변경신고 미신고]
bibliography: references.bib
---

한국원자력안전기술원에서 개최한 의료분야 안전관리 워크샵 (2017.10.24) 발표자료집에서 발췌 @igibog2017

-   <a href="../../law/nuclear_safety_act.qmd#제53조-방사성동위원소ㆍ방사선발생장치-사용-등의-허가-등" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기"> 원자력안전법 제53조(방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등)
    </a> 
    [1항 단서조항]{.tooltip-text-inverted 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="① 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)를 생산ㆍ판매ㆍ사용(소지ㆍ취급을 포함한다. 이하 같다) 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회의 허가를 받아야 한다. 허가받은 사항을 변경하려는 때에도 또한 같다. 다만, 총리령으로 정하는 일시적인 사용 장소의 변경과 그 밖의 경미한 사항을 변경하려는 때에는 이를 신고하여야 한다.<개정 2013.3.23.>"
    }
       및 
    <a href="../../compendium/law/nuclear_safety_enforcement_rule.qmd#제63조-경미한-사항의-변경신고" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기"> 시행규칙 63조 (경미한 사항의 변경신고)
    </a> 
    [1항 2호 가목]{.tooltip-text-inverted 
       data-bs-toggle="tooltip"
       data-bs-placement="bottom"       
       data-bs-html="true" title="① 법 제53조제1항 단서에서 “총리령으로 정하는 일시적인 사용장소의 변경과 그 밖의 경미한 사항을 변경하려는 때”란 다음 각 호의 어느 하나에 해당하는 경우를 말한다. <개정 2013. 8. 16., 2024. 4. 25.>   다음 각 목의 어느 하나에 해당하는 사항의 변경 가. 사용시설등의 변경을 요하지 아니하는 방사성동위원소등의 종류 또는 수량의 감소에 관한 사항"
    }
에 따라 방사성동위원소의 수량이 감소한 경우, 30일 이내에 신고하여야 함.

-   동 사업소는 '201X년 11월, Ge-68 83 MBq x1, 46 MBq x2를 양도하여 수량을 6개에서 3개로 감량하였으나, 그 사실을 신고하지 않았음.
