---
title: "피폭관리"
author: "대한핵의학회 방사선안전위원회"
date: "2024.11.17"
date-modified: "2024.11.17"
categories: [정기검사, 지적사항, 피폭관리]
---

피폭관리와 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제91조 방사선장해방지조치

::: {.callout-note title="제91조(방사선장해방지조치)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

4.  방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치

② 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.

③ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.
:::

### 제91조 방사선장해방지조치 \[시행일: 2025. 4. 23.\]

::: {.callout-note title="제91조(방사선장해방지조치) [시행일: 2025. 4. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[① 원자력관계사업자(신고사용자는 제외한다)는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

<p style="text-indent: 20px;">

[4. 삭제]{style="color:red;"} \<2024. 10. 22.\>

</p>

[② 원자력관계사업자는 대통령령으로 정하는 바에 따라 방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치를 하여야 한다.]{style="color:red;"} \<신설 2024. 10. 22.\>

[③ 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

[④ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

\[시행일: 2025. 4. 23.\] 제91조
:::

## 원자력안전법 시행령

### 제133조(피폭관리)

::: {.callout-note title="제133조(피폭관리)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 법 제91조제1항제3호 및 같은 조 제2항에 따라 방사선작업종사자 및 수시출입자의 개인피폭선량이 선량한도를 초과하지 아니하도록 총리령으로 정하는 바에 따라 피폭선량 평가 및 피폭관리를 하여야 한다. <개정 2013. 3. 23.>

② 법 제91조제2항에서 “대통령령으로 정하는 수시출입자”란 제2조제8호에 따른 수시출입자를, “대통령령으로 정하는 선량한도”란 제2조제4호에 따른 선량한도를 각각 말한다.
:::


## 원자력안전법 시행규칙

### 제122조(피폭방사선량 평가 및 관리)

::: {.callout-note title="제122조(피폭방사선량 평가 및 관리)" collapse="open" appearance="minimal"}
원자력관계사업자는 영 제133조제1항에 따라 방사선작업종사자 및 수시출입자에 대하여 다음 각 호에 따라 피폭방사선량을 평가하고 관리해야 한다. <개정 2016. 8. 8., 2021. 3. 4.>


1. 방사선작업종사자가 방사선관리구역에 출입하는 때에는 위원회가 정하여 고시하는 개인선량계를 착용하도록 할 것

2. 수시출입자가 방사선관리구역에 출입하는 때에는 위원회가 정하여 고시하는 개인선량계를 착용하도록 할 것

3. 제1호 및 제2호에 따른 개인선량계 중 판독이 필요한 개인선량계는 위원회가 정하여 고시하는 기간마다 교체하여 판독하도록 할 것

3의2. 방사선작업종사자가 제3호에 따른 기간 내에 「진단용 방사선발생장치의 안전관리에 관한 규칙」 제4조제5항 또는 「동물 진단용 방사선 발생장치의 안전관리에 관한 규칙」 제4조제6항에 따른 방사선 피폭선량 측정을 받은 경우에는 그 측정 내용을 포함하여 제3호에 따른 판독을 하도록 할 것

4. 제3호 및 제3호의2에 따른 개인선량계의 판독은 판독업무자가 수행하도록 할 것

5. 방사선작업종사자 또는 수시출입자 중 영 제2조제15호에 따른 판독특이자가 발생한 때에는 위원회가 정하여 고시하는 바에 따라 필요한 조치를 할 것
:::
