---
title: "장비ㆍ인력"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 장비ㆍ인력]
---

장비ㆍ인력과 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제55조 허가기준 등

::: {.callout-note title="제55조(허가기준 등)" collapse="open" appearance="minimal"}
① 제53조제1항에 따른 허가기준은 다음과 같다.

1.  생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비가 위원회규칙으로 정하는 기술기준에 적합할 것

2.  방사성동위원소 또는 그에 따라 오염된 물질 또는 방사선발생장치에 따라 발생한 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니할 것

3.  생산하려는 방사성동위원소등의 성능 및 품질보증계획서의 내용이 위원회가 정하여 고시하는 기준에 적합할 것

4.  대통령령으로 정하는 장비 및 인력을 확보할 것

② 제54조제1항에 따른 등록기준은 다음 각 호와 같다.\<개정 2013.3.23.\>

1.  총리령으로 정하는 대행업무 수행에 필요한 기술능력을 확보하고 있을 것

2.  대통령령으로 정하는 장비 및 인력을 확보할 것

3.  대행업무의 범위 및 업무대행규정이 총리령으로 정하는 기준에 적합할 것
:::

## 원자력안전법 시행령

### 제83조(허가기준)

::: {.callout-note title="제83조(허가기준)" collapse="open" appearance="minimal"}
① 법 제55조제1항제2호에서 “대통령령으로 정하는 선량한도”란 제2조제4호에 따른 선량한도를 말한다.

② 법 제55조제1항제4호에서 “대통령령으로 정하는 장비 및 인력”이란 별표 2에 따른 장비 및 별표 3에 따른 인력을 말한다. <개정 2013. 8. 16.>

③ 방사성동위원소등을 사용 또는 판매하려는 자가 법 제54조제2항에 따른 업무대행자(이하 “업무대행자”라 한다)에게 법 제54조제1항제5호에 따른 방사선안전관리업무를 대행시키는 경우에는 총리령으로 정하는 바에 따라 업무대행자의 인력으로 제2항에 따른 인력을 갈음할 수 있다. <개정 2013. 3. 23., 2014. 11. 19.>
:::

### 별표2. 방사성동위원소등 생산 등의 허가 시 장비기준

-   [방사성동위원소등 생산 등의 허가 시 장비기준(제83조제2항 관련)](/archive/[별표 2] 방사성동위원소등 생산 등의 허가 시 장비기준(제83조제2항 관련)(원자력안전법 시행령).pdf)

### 별표3. 방사성동위원소등 생산 등의 허가 시 인력기준

-   [방사성동위원소등 생산 등의 허가 시 인력기준(제83조제2항 관련)](/archive/[별표 3] 방사성동위원소등 생산 등의 허가 시 인력기준(제83조제2항 관련)(원자력안전법 시행령).pdf)