---
title: "원자력안전법 시행령"
description: |
  [시행 2025. 4. 23.] [대통령령 제35473호, 2025. 4. 22., 일부개정]<br><br>
  <div style="text-align: right;">
  원자력안전위원회(안전정책과), 02-397-7264<br>
  원자력안전위원회(방사선안전과), 02-397-7273<br>
  원자력안전위원회(안전기준과), 02-397-7315<br>
  원자력안전위원회(생활방사선안전과), 02-397-7334</div>
date: "2025-04-23"
date-modified: "2025-04-23"
categories: [시행령]
---

# 제1장 총칙

### 제1조(목적)

::: {.callout-note title="제1조(목적)" collapse="open" appearance="minimal"}
이 영은 「원자력안전법」에서 위임된 사항 및 그 시행에 필요한 사항과 「원자력 진흥법」 제17조제2항에 따른 원자력안전규제계정의 관리ㆍ운용에 필요한 사항을 규정함을 목적으로 한다. \<개정 2015.12.22.\>
:::

### 제2조(정의)

::: {.callout-note title="제2조(정의)" collapse="open" appearance="minimal"}
이 영에서 사용하는 용어의 뜻은 다음과 같다. \<개정 2014.9.11., 2016.4.12.\>

1.  “고준위방사성폐기물”이란 방사성폐기물 중 그 방사능 농도 및 열발생률이 「원자력안전위원회의 설치 및 운영에 관한 법률」 제3조에 따른 원자력안전위원회(이하 “위원회”라 한다)가 정하는 값 이상인 방사성폐기물을 말하고, “중ㆍ저준위방사성폐기물”이란 고준위방사성폐기물 외의 방사성폐기물을 말한다. 이 경우 중ㆍ저준위방사성폐기물은 위원회가 방사능 농도를 고려하여 정하는 바에 따라 구분한다.

2.  “핵연료집합체”란 원자로의 연료로 사용할 수 있는 형태를 갖춘 한 다발의 핵연료물질을 말한다.

3.  “밀봉된 방사성동위원소”란 기계적인 강도가 충분하여 파손될 우려가 없고, 부식되기 어려운 재료로 된 용기에 넣은 방사성동위원소로서 사용할 때에 방사선은 용기 외부로 방출하지만 방사성동위원소는 누출하지 못하도록 되어 있는 것을 말한다.

4.  “선량한도”(線量限度)란 외부에 피폭하는 방사선량과 내부에 피폭하는 방사선량을 합한 피폭방사선량(被曝放射線量)의 상한값으로서 그 값은 별표 1과 같다.

5.  “허용표면오염도”란 물체 또는 인체 표면의 방사성오염도로서 위원회가 정하는 허용오염도를 말한다.

6.  “보전구역”이란 원자력이용시설의 보전을 위하여 특별한 관리가 필요한 장소를 말한다.

7.  “제한구역”이란 방사선관리구역 및 보전구역의 주변 구역으로서 그 구역 경계에서의 피폭방사선량이 위원회가 정하는 값을 초과할 우려가 있는 장소를 말한다.

8.  “수시출입자”란 방사선관리구역에 청소, 시설관리 등의 업무상 출입하는 사람(방문, 견학 등을 위하여 일시적으로 출입하는 사람은 제외한다)으로서 방사선작업종사자 외의 사람을 말한다.

9.  “영구처분”이란 방사성폐기물을 회수할 의도 없이 인간의 생활권으로부터 영구히 격리하는 것을 말한다.

10. “사용후핵연료 중간저장”이란 원자로의 연료로 사용된 핵연료물질이나 그 밖의 방법으로 핵분열시킨 핵연료물질을 발생자로부터 인수하여 처리 또는 영구처분하기 전까지 일정 기간 안전하게 저장하는 것을 말한다.

11. “특수형방사성물질”이란 견고한 고체형 방사성물질 또는 캡슐에 넣고 봉한 방사성물질로서 위원회가 정하는 운반기준에 맞는 것을 말한다.

12. “배출”이란 방사성물질 또는 그로 인하여 오염된 물질(이하 “방사성물질등”이라 한다)로서 원자력이용시설에서 정상운전 중에 발생한 액체 또는 기체 상태의 방사성물질등을 위원회가 정하는 제한값 이내에서 배수시설 또는 배기시설을 통하여 계획적이고 통제된 상태에서 외부로 내보내는 것을 말한다.

13. “연간섭취한도”란 방사선작업종사자가 1년 동안 섭취할 경우 피폭방사선량이 선량한도에 이를 것으로 보이는 방사능의 양으로서 위원회가 정하는 값을 말한다.

14. “유도공기 중 농도”란 방사선작업종사자가 1년 동안 흡입할 경우 방사능 섭취량이 연간섭취한도에 이를 것으로 보이는 공기 중의 농도로서 위원회가 정하는 값을 말한다.

15. “판독특이자”란 다음 각 목의 어느 하나에 해당하는 사람을 말한다.

가. 선량한도를 초과하여 방사선에 피폭된 사람

나. 선량계의 훼손ㆍ분실 등으로 인하여 선량판독이 불가능하게 된 사람

다. 위원회가 정하는 선량계 교체주기를 2개월 이상 지난 후 선량계를 제출한 사람
:::

### 제5조(방사성동위원소)

::: {.callout-note title="제5조(방사성동위원소)" collapse="open" appearance="minimal"}
법 제2조제6호에서 “대통령령으로 정하는 것”이란 동위원소의 수량과 농도가 위원회가 정하는 수량과 농도를 초과하는 물질로서 다음 각 호의 물질을 제외한 것을 말한다.

1.  법 제2조제3호에 따른 핵연료물질

2.  법 제2조제4호에 따른 핵원료물질

3.  방사성물질 또는 이를 내장한 장치 중 방사선장해의 우려가 없는 것으로서 위원회가 정하여 고시하는 것
:::

### 제6조(방사선)

::: {.callout-note title="제6조(방사선)" collapse="open" appearance="minimal"}
법 제2조제7호에서 “대통령령으로 정하는 것”이란 다음 각 호의 것을 말한다.

1.  알파선ㆍ중양자선ㆍ양자선ㆍ베타선 및 그 밖의 중하전입자선

2.  중성자선

3.  감마선 및 엑스선

4.  5만 전자볼트 이상의 에너지를 가진 전자선
:::

### 제8조 방사선발생장치

::: {.callout-note title="제8조(방사선발생장치)" collapse="open" appearance="minimal"}
법 제2조제9호에서 “대통령령으로 정하는 것”이란 다음 각 호의 것을 말한다. 다만, 위원회가 정하는 용도의 것과 위원회가 정하는 용량 이하의 것은 제외한다.

1.  엑스선발생장치

2.  사이클로트론(cyclotron)

3.  신크로트론(synchrotron)

4.  신크로사이클로트론(synchro-cyclotron)

5.  선형가속장치

6.  베타트론(betatron)

7.  반ㆍ데 그라프형 가속장치

8.  콕크로프트ㆍ왈톤형 가속장치

9.  변압기형 가속장치

10. 마이크로트론(microtron)

11. 방사광가속기

12. 가속이온주입기

13. 그 밖에 위원회가 정하여 고시하는 것
:::

# 제5장 방사성동위원소등ㆍ방사성폐기물 및 방사성물질의 관리

### 제79조(사용허가등의 신청)

::: {.callout-note title="제79조(사용허가등의 신청)" collapse="open" appearance="minimal"}
① 법 제53조제1항 본문의 전단에 따른 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)를 생산ㆍ판매ㆍ사용(소지ㆍ취급을 포함한다. 이하 같다) 또는 이동사용하기 위하여 허가를 받으려는 자는 사업소별로 총리령으로 정하는 바에 따라 허가신청서를 위원회에 제출하여야 한다. \<개정 2013. 3. 23.\>

② 제1항에 따라 방사성동위원소의 생산허가를 받으려는 자는 사업소마다 핵종별ㆍ수량별로 총리령으로 정하는 바에 따라 허가신청서를 위원회에 제출해야 한다. \<개정 2013. 3. 23., 2019. 12. 3.\>

③ 제1항에 따라 방사선발생장치의 생산허가를 받으려는 자는 사업소마다 용량별로 총리령으로 정하는 바에 따라 허가신청서를 위원회에 제출해야 한다. 다만, 제8조제1호에 따른 엑스선발생장치의 생산허가를 받으려는 자는 사업소마다 생산하려는 엑스선발생장치의 용량 중 최대 용량을 기준으로 총리령으로 정하는 바에 따라 허가신청서를 위원회에 제출할 수 있다. \<신설 2019. 12. 3.\>
:::

### 제80조(변경허가 신청)

::: {.callout-note title="제80조(변경허가 신청)" collapse="open" appearance="minimal"}
법 제53조제1항 본문의 전단에 따라 허가를 받은 자(이하 “허가사용자”라 한다)는 같은 항 본문의 후단에 따라 그 허가사항의 변경허가를 받으려면 총리령으로 정하는 바에 따라 변경허가신청서를 위원회에 제출하여야 한다. \<개정 2013. 3. 23.\>
:::

### 제81조(사용신고)

::: {.callout-note title="제81조(사용신고)" collapse="open" appearance="minimal"}
법 제53조제2항 전단에 따라 밀봉된 방사성동위원소 또는 방사선발생장치의 사용 또는 이동사용 신고를 하려는 자는 총리령으로 정하는 바에 따라 사업소마다 사용 또는 이동사용 신고서를 작성하여 위원회에 제출하여야 한다. \<개정 2013. 3. 23.\>
:::

### 제82조(변경신고)

::: {.callout-note title="제82조(변경신고)" collapse="open" appearance="minimal"}
법 제53조제2항 전단에 따라 신고를 한 자(이하 “신고사용자”라 한다)는 같은 항 후단에 따라 그 신고한 사항을 변경하려면 총리령으로 정하는 바에 따라 변경신고서를 위원회에 제출하여야 한다. \<개정 2013. 3. 23.\>
:::

### 제82조의2(대형 방사선발생장치 사용 허가의 사전검토 대상)

::: {.callout-note title="제82조의2(대형 방사선발생장치 사용 허가의 사전검토 대상)" collapse="open" appearance="minimal"}
법 제53조의2제1항에서 “대통령령으로 정하는 종류 또는 용량 이상의 방사선발생장치”란 다음 각 호의 어느 하나에 해당하는 방사선발생장치를 말한다.

1.  가속시킨 전자(電子), 양성자(陽性子) 또는 중성자(中性子)의 입자당 에너지가 50메가전자볼트를 초과하는 방사선발생장치

2.  다음 각 목의 요건을 모두 갖춘 방사선발생장치

가. 원자핵의 질량수(質量數: 원자핵을 구성하는 양성자와 중성자 수의 합)가 4를 초과할 것

나. 가속시킨 양성자 또는 중성자의 입자당 에너지가 10메가전자볼트를 초과할 것

다. 빔 출력\[beam power: 가속시킨 입자당 에너지의 합을 초(秒)로 나눈 값\]이 50와트를 초과할 것

\[본조신설 2023. 3. 7.\]

\[종전 제82조의2는 제82조의3으로 이동 \<2023. 3. 7.\>\]
:::

### 제82조의3(방사선안전관리자의 선임 등)

::: {.callout-note title="제82조의3(방사선안전관리자의 선임 등)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 법 제53조의3제1항에 따라 사업소마다 방사선안전관리자를 선임하여야 하며, 선임한 방사선안전관리자를 변경하거나 해임한 때에는 지체 없이 새로운 방사선안전관리자를 선임하여야 한다. \<개정 2023. 3. 7.\>

② 제1항에도 불구하고 법 제53조제1항 단서에 따라 방사성동위원소등을 사업소 외에서 방사선투과검사를 목적으로 이동사용하기 위한 작업장(이하 “작업장”이라 한다) 개설 또는 변경 신고를 한 자는 작업장마다 각각 제1항에 따른 방사선안전관리자를 선임하여야 한다. 다만, 작업장이 다음 각 호의 어느 하나에 해당하는 경우에는 작업장마다 방사선안전관리자를 선임하지 아니하고 해당 각 호의 구분에 따라 방사선안전관리자를 선임할 수 있다.

1.  작업장이 같은 시ㆍ군ㆍ구(자치구를 말한다. 이하 같다)에 위치하거나 그 시ㆍ군ㆍ구 경계에서 15킬로미터 이내에 위치하는 경우: 2개 이하(전용 방사선 사용시설에서만 방사선원을 사용하는 경우에는 3개 이하)의 작업장마다 1명의 방사선안전관리자

2.  작업장이 방사선원을 1개만 사용하고, 방사선 작업기간이 1개월 미만이며, 방사선안전관리자가 방사선 작업에 항상 참여하는 경우: 5개 이하의 작업장마다 1명의 방사선안전관리자

③ 법 제53조의3제1항 및 제3항에 따라 방사선안전관리자를 선임하거나, 선임한 방사선안전관리자를 변경 또는 해임 후 선임하는 때에는 다음 각 호의 기한까지 총리령으로 정하는 바에 따라 위원회에 신고하여야 한다. \<개정 2023. 3. 7.\>

1.  법 제53조의3제1항 전단에 따라 방사선안전관리자를 선임하는 경우: 방사성동위원소등의 사용개시 전

2.  법 제53조의3제1항 후단에 따라 방사선안전관리자를 변경하려는 경우: 변경 전

3.  법 제53조의3제3항에 따라 방사선안전관리자를 해임 후 선임하는 경우: 해임한 날부터 30일 이내

\[본조신설 2014. 11. 19.\]

\[제82조의2에서 이동, 종전 제82조의3은 제82조의4로 이동 \<2023. 3. 7.\>\]
:::

### 제82조의4(방사선안전관리자의 자격요건)

::: {.callout-note title="제82조의4(방사선안전관리자의 자격요건)" collapse="open" appearance="minimal"}
① 법 제53조의3제7항에 따른 방사선안전관리자의 자격요건은 다음 각 호와 같다. \<개정 2019. 2. 8., 2023. 3. 7.\>

1.  허가사용자가 선임하는 경우에는 해당 사업소 종업원 중에서 법 제84조제2항제5호부터 제7호까지 중 어느 하나에 해당하는 면허를 소지한 사람 또는 방사선관리기술사 자격을 소지한 사람

2.  신고사용자가 선임하는 경우에는 해당 사업소 종업원 중에서 방사성동위원소등의 취급업무에 종사한 경력이 있는 사람

② 제1항에도 불구하고 법 제54조제1항제5호에 따라 방사선안전관리를 업무대행자에게 대행시키는 자는 별표 4 제3호에 따른 인력을 방사선안전관리자로 선임할 수 있다.

③ 제1항에 따른 방사선안전관리자의 자격요건에 관한 세부적인 사항은 총리령으로 정한다.

\[본조신설 2014. 11. 19.\]

\[제82조의3에서 이동, 종전 제82조의4는 제82조의5로 이동 \<2023. 3. 7.\>\]
:::

### 제82조의5(방사선안전관리자의 대리자 지정 및 자격요건 등)

::: {.callout-note title="제82조의5(방사선안전관리자의 대리자 지정 및 자격요건 등)" collapse="open" appearance="minimal"}
① 법 제53조의3제1항에 따라 방사선안전관리자를 선임한 허가사용자 또는 신고사용자는 같은 조 제6항 각 호의 어느 하나에 해당하는 사유 발생 즉시 방사선안전관리자의 대리자를 지정하고 총리령으로 정하는 바에 따라 지정서를 작성해 둬야 한다. \<개정 2023. 3. 7.\>

② 제1항에 따른 대리자의 직무대행기간은 다음 각 호의 구분에 따른다. \<개정 2023. 3. 7.\>

1.  법 제53조의3제6항제1호의 경우: 연간 30일 이내. 다만, 출산휴가로 인한 경우 연간 90일 이내로 한다.

2.  법 제53조의3제6항제2호의 경우: 해임 또는 퇴직한 날부터 30일 이내

③ 법 제53조의3제7항에 따른 대리자의 자격요건은 다음 각 호의 구분에 따른다. \<개정 2023. 3. 7.\>

1.  허가사용자가 선임하는 경우: 다음 각 목의 어느 하나에 해당하는 해당 사업소 종업원

가. 법 제84조제2항제5호부터 제7호까지의 규정 중 어느 하나에 해당하는 면허를 소지한 사람

나. 방사선관리기술사 자격을 소지한 사람

다. 방사성동위원소등의 취급업무에 종사한 경력이 있는 사람

2.  신고사용자가 선임하는 경우: 해당 사업소 종업원 중에서 방사성동위원소등의 취급업무에 종사한 경력이 있는 사람

④ 제3항에 따른 대리자의 자격요건에 관한 세부사항은 총리령으로 정한다.

\[본조신설 2019. 2. 8.\]

\[제82조의4에서 이동 \<2023. 3. 7.\>\]
:::

### 제83조(허가기준)

::: {.callout-note title="제83조(허가기준)" collapse="open" appearance="minimal"}
① 법 제55조제1항제2호에서 “대통령령으로 정하는 선량한도”란 제2조제4호에 따른 선량한도를 말한다.

② 법 제55조제1항제4호에서 “대통령령으로 정하는 장비 및 인력”이란 별표 2에 따른 장비 및 별표 3에 따른 인력을 말한다. \<개정 2013. 8. 16.\>

③ 방사성동위원소등을 사용 또는 판매하려는 자가 법 제54조제2항에 따른 업무대행자(이하 “업무대행자”라 한다)에게 법 제54조제1항제5호에 따른 방사선안전관리업무를 대행시키는 경우에는 총리령으로 정하는 바에 따라 업무대행자의 인력으로 제2항에 따른 인력을 갈음할 수 있다. \<개정 2013. 3. 23., 2014. 11. 19.\>
:::

### 제84조(등록기준)

::: {.callout-note title="제84조(등록기준)" collapse="open" appearance="minimal"}
법 제55조제2항제2호에서 “대통령령으로 정하는 장비 및 인력”이란 다음 각 호의 장비 및 인력을 말한다.

1.  장비: 등록업무를 전담하기 위한 다음 각 목의 장비

가. 방사선측정기 5대 이상

나. 방사능측정기 2대 이상

다. 전담인력마다 방사선경보기 또는 직독식 개인선량계 1대 이상

라. 방사성물질등을 운반할 수 있는 전용차량 1대 이상(법 제54조제1항제2호의 업무를 대행하려는 경우에 한정한다)

2.  인력: 등록업무를 전담하기 위한 별표 4에 따른 인력
:::

### 제85조(시설검사)

::: {.callout-note title="제85조(시설검사)" collapse="open" appearance="minimal"}
① 법 제56조제1항 본문에 따라 허가사용자는 방사성동위원소등의 생산시설ㆍ사용시설ㆍ분배시설ㆍ저장시설ㆍ보관시설ㆍ처리시설 및 배출시설(이하 “사용시설등”이라 한다)을 설치 또는 변경한 경우에는 해당 시설에 대하여 위원회의 검사를 받아야 한다.

② 허가사용자가 다음 각 호의 어느 하나에 해당하는 사용시설등에 대하여 총리령으로 정하는 바에 따라 자체점검을 하고, 그 자체점검결과에 대하여 위원회의 서면심사를 받아 합격한 경우에는 해당 자체점검으로 제1항에 따른 시설검사를 갈음한다. 다만, 해당 사용시설등을 최초로 검사하는 경우에는 그러하지 아니하다. \<개정 2013. 3. 23.\>

1.  법 제60조제1항 본문에 따라 승인을 받은 방사선기기(별도의 방사선차폐체를 설치하지 아니하고 취급할 수 있는 것만 해당한다)를 설치한 사용시설등

2.  법 제60조제1항 본문에 따라 승인을 받은 방사선발생장치로서 총리령으로 정하는 장치를 설치한 사용시설등

3.  370기가베크렐 미만의 밀봉된 방사성동위원소의 사용시설등

③ 업무대행자가 제2항 각 호의 어느 하나에 해당하는 사용시설등에 대하여 총리령으로 정하는 바에 따라 감리(監理)를 실시하고, 그 감리 결과에 대하여 위원회의 서면심사를 받아 합격한 경우에는 그 감리로 제1항에 따른 시설검사를 갈음한다. 다만, 해당 사용시설등을 최초로 검사하는 경우에는 그러하지 아니하다. \<개정 2013. 3. 23.\>

④ 제1항에 따른 검사, 제2항에 따른 자체점검 또는 제3항에 따른 감리 결과에 대한 서면심사 결과 그 사용시설등의 설치 또는 변경이 법 제53조제1항에 따른 허가 내용(법 제99조에 따른 조건을 포함한다)과 일치하는 경우에는 합격으로 한다.

⑤ 위원회는 제2항 또는 제3항에 따라 제출된 자체점검 결과 또는 감리 결과에 대한 서면심사 결과 불합격한 사용시설등에 대해서는 제1항에 따른 검사를 하여야 한다.
:::

### 제86조(시설검사의 면제)

::: {.callout-note title="제86조(시설검사의 면제)" collapse="open" appearance="minimal"}
법 제56조제1항 단서에 따라 시설검사가 면제되는 경우는 다음 각 호와 같다. \<개정 2013. 8. 16., 2018. 6. 19., 2021. 1. 5.\>

1.  밀봉된 방사성동위원소 외의 방사성동위원소(이하 “밀봉되지 아니한 방사성동위원소”라 한다)의 저장시설을 변경하는 경우

2.  방사성폐기물\[폐기선원(사용이 종료된 방사성동위원소를 말한다)은 제외한다\]의 저장시설을 변경하는 경우

3.  일시적인 사용장소에 사용시설등을 설치하는 경우

4.  법 제53조제2항에 따라 신고대상인 방사성동위원소등을 사용하기 위하여 사용시설등을 추가로 설치하거나 변경하는 경우

5.  법 제61조제1항 각 호 외의 부분 본문에 따른 제작검사에 합격한 방사선기기를 기존 시설의 변경 없이 설치하는 경우

6.  방사광가속기에 방사광빔라인을 추가로 설치하거나 구조를 변경하는 경우로서 위원회가 시설검사가 필요 없다고 인정하는 경우

7.  방사선발생장치의 보관시설을 설치하거나 변경하는 경우
:::

### 제87조(시설검사 신청)

::: {.callout-note title="제87조(시설검사 신청)" collapse="open" appearance="minimal"}
제85조제1항에 따라 사용시설등에 관하여 검사를 받아야 하는 자는 검사신청서에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다. \<개정 2013.3.23.\>
:::

### 제88조(정기검사)

::: {.callout-note title="제88조(정기검사)" collapse="open" appearance="minimal"}
① 허가사용자는 법 제56조제1항에 따라 사용시설등의 시설 및 그 운영에 관하여 총리령으로 정하는 바에 따라 정기적으로 위원회의 검사를 받아야 한다. \<개정 2013. 3. 23.\>

② 업무대행자는 법 제56조제1항 본문에 따라 대행업무의 운영 및 내용에 관하여 총리령으로 정하는 바에 따라 정기적으로 위원회의 검사를 받아야 한다. \<개정 2013. 3. 23.\>

③ 다음 각 호의 요건을 모두 갖춘 허가사용자가 사용시설등의 시설 및 그 운영에 관하여 총리령으로 정하는 바에 따라 자체점검을 하고, 그 자체점검 결과를 위원회에 제출하여 서면심사에 의한 검사(이하 이 조에서 “서면검사”라 한다)를 받아 합격한 경우에는 그 서면검사로 제1항에 따른 정기검사를 갈음한다. 다만, 처음으로 정기검사를 받아야 하는 경우와 서면검사를 받은 직후에 정기검사를 받아야 하는 경우는 예외로 한다. \<개정 2013. 3. 23., 2021. 2. 2.\>

1.  총리령으로 정하는 정기검사주기가 3년 또는 5년인 사용시설등을 설치ㆍ운영하는 자일 것

2.  직전 정기검사에서 시정 또는 보완 명령을 받지 아니하였을 것

3.  정기검사 해당 연도의 1월 1일부터 기산하여 최근 3년간 법 제98조제1항에 따른 보고(해당 사용시설등의 시설 및 그 운영에 관한 보고에 한정한다)가 누락되지 아니하였을 것

4.  정기검사 해당 연도의 1월 1일부터 기산하여 최근 3년간 판독특이자가 발생하지 아니하였을 것

5.  정기검사 해당 연도의 1월 1일부터 기산하여 최근 5년간 법 제97조에 따른 방사선발생장치 또는 방사성물질등에 관한 도난ㆍ분실ㆍ화재, 그 밖의 사고가 발생하지 아니하였을 것

④ 제1항과 제2항에 따른 검사 결과 또는 서면검사 결과 법 제55조 및 제59조제1항에 따른 기준에 맞게 유지된 경우에는 합격으로 한다. \<개정 2021. 2. 2.\>

⑤ 위원회는 서면검사 결과 불합격한 사용시설등의 시설 및 그 운영에 대해서는 제1항에 따른 검사를 해야 한다. \<개정 2021. 2. 2.\>
:::

# 제6장 폐기 및 운반 등

### 제107조 방사성폐기물 자체처분의 절차 및 방법

::: {.callout-note title="제107조(방사성폐기물 자체처분의 절차 및 방법)" collapse="open" appearance="minimal"}
① 법 제71조에 따른 원자력관계사업자(이하 “원자력관계사업자”라 한다)는 법 제70조제3항에 따라 다음 각 호의 어느 하나에 해당하는 방사성폐기물로서 법 제70조제2항에 따른 방사성폐기물 외의 방사성폐기물임을 위원회로부터 확인을 받은 방사성폐기물을 소각, 매립 또는 재활용 등의 방법으로 처분(이하 “자체처분”이라 한다)할 수 있다. \<개정 2014. 9. 11., 2015. 7. 20., 2023. 8. 1.\>

1.  원자력관계사업자가 발생시킨 방사성폐기물

2.  원자력관계사업자(방사성폐기물관리시설등건설ㆍ운영자는 제외한다)로부터 처분을 위탁받아 관리하고 있는 방사성폐기물

② 제1항에 따라 자체처분을 하려는 원자력관계사업자는 방사성폐기물을 자체처분할 때마다 총리령으로 정하는 바에 따라 자체처분계획서에 관계 서류를 첨부하여 위원회에 제출하여야 한다. 이를 변경하려는 경우에도 또한 같다. \<개정 2013. 3. 23., 2014. 9. 11.\>

③ 제2항 전단에도 불구하고 다음 각 호의 기준을 모두 만족하는 방사성폐기물을 자체처분하려는 원자력관계사업자는 제2항에 따른 자체처분계획서를 5년마다 위원회에 제출할 수 있다. \<개정 2014. 9. 11., 2020. 5. 26.\>

1.  반감기(半減期)가 5일 미만인 핵종만을 포함할 것

2.  위원회가 정하여 고시하는 자체처분 허용기준에 적합할 것

④ 위원회는 제2항 또는 제3항에 따라 제출된 자체처분계획서가 위원회가 정하여 고시하는 자체처분의 방법 및 절차에 적합한지에 대하여 검토하고, 그 결과를 총리령으로 정하는 바에 따라 원자력관계사업자에게 통지해야 한다. \<신설 2014. 9. 11., 2023. 8. 1.\>

⑤ 제4항에 따라 자체처분계획서가 적합한 것으로 통지받은 원자력관계사업자는 해당 방사성폐기물을 자체처분할 수 있다. \<신설 2014. 9. 11.\>

⑥ 제5항에 따라 자체처분을 한 자는 자체처분에 관한 기록을 자체처분일부터 5년간 보존하여야 한다. \<개정 2014. 9. 11.\>

⑦ 원자력관계사업자는 제2항에 따라 자체처분계획서를 제출하기 전에 그 자체처분계획서의 내용 중 핵종별 농도 측정 및 평가 방법에 대하여 총리령으로 정하는 바에 따라 위원회에 사전검토를 신청할 수 있다. \<신설 2023. 8. 1.\>

⑧ 위원회는 제7항에 따른 신청 내용이 위원회가 정하여 고시하는 자체처분의 방법 및 절차에 적합한지 여부를 검토하고, 그 결과를 총리령으로 정하는 바에 따라 신청인에게 통지해야 한다. \<신설 2023. 8. 1.\>

⑨ 위원회는 제4항에 따라 자체처분계획서를 검토할 때에는 제8항에 따라 통지한 사전검토 결과를 고려해야 한다. \<신설 2023. 8. 1.\>
:::

# 제9장 규제ㆍ감독 등

### 제131조 측정

::: {.callout-note title="제131조(측정)" collapse="open" appearance="minimal"}
① 원자력관계사업자(신고사용자는 제외한다. 이하 이 조, 제132조, 제133조제1항 및 제148조의3에서 같다)는 법 제91조제1항제1호에 따라 총리령으로 정하는 방사선장해의 우려가 있는 장소에 대한 방사선량 및 방사성물질등에 의한 오염상황을 측정하여야 한다. \<개정 2013. 3. 23., 2013. 8. 16., 2017. 3. 20., 2025. 4. 22.\>

② 법 제91조제1항제1호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설에 출입하는 사람의 피폭방사선량 및 방사성물질에 의한 오염상황을 측정하여야 한다. \<개정 2013. 3. 23., 2013. 8. 16.\>

③ 원자력관계사업자는 제1항 및 제2항의 측정 결과에 관하여 기록의 작성, 보존, 그 밖의 총리령으로 정하는 조치를 하여야 한다. \<개정 2013. 3. 23.\>
:::

### 제132조 건강진단

::: {.callout-note title="제132조(건강진단)" collapse="open" appearance="minimal"}
① 법 제91조제1항제2호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설의 방사선작업종사자 및 수시출입자에 대하여 건강진단을 실시하여야 한다. \<개정 2013. 3. 23., 2013. 8. 16., 2016. 4. 12.\>

② 원자력관계사업자는 제1항의 건강진단의 결과에 관하여 기록의 작성ㆍ보존 그 밖에 총리령으로 정하는 조치를 하여야 한다. \<개정 2013. 3. 23.\>
:::

### 제133조(피폭관리)

::: {.callout-note title="제133조(피폭관리)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 법 제91조제1항제3호에 따라 방사선작업종사자 및 수시출입자의 개인피폭선량이 선량한도를 초과하지 아니하도록 총리령으로 정하는 바에 따라 피폭선량 평가 및 피폭관리를 하여야 한다. \<개정 2013. 3. 23., 2025. 4. 22.\>

② 원자력관계사업자는 법 제91조제2항에 따라 원자력이용시설의 정상운전 및 비정상상태(사고의 경우는 제외한다)에서 원자력이용시설에 종사하는 방사선작업종사자 및 수시출입자와 시설 주변 주민의 방사선피폭을 최소화하기 위하여 위원회가 정하는 바에 따라 다음 각 호의 조치를 하여야 한다. \<신설 2025. 4. 22.\>

1.  방사선 작업 특성에 부합하는 방호조치

2.  방사선차폐 및 시설의 적절한 배치

3.  선량 저감에 효과적인 재료 및 기기의 사용

4.  적절한 작업공간의 확보

③ 법 제91조제3항에서 “대통령령으로 정하는 수시출입자”란 제2조제8호에 따른 수시출입자를, “대통령령으로 정하는 선량한도”란 제2조제4호에 따른 선량한도를 각각 말한다. \<개정 2025. 4. 22.\>
:::

# 제10장 보칙

### 제148조 방사선작업종사자 및 수시출입자 교육

::: {.callout-note title="제148조(방사선작업종사자 및 수시출입자 교육)" collapse="open" appearance="minimal"}
① 원자력관계사업자가 법 제106조제1항에 따라 실시하는 교육은 다음 각 호의 구분에 따른다. 이 경우 신규교육은 작업 종사 전에 실시해야 한다. \<개정 2025. 4. 22.\>

1.  법 제106조제1항제1호에 따라 원자력관계사업자(신고사용자는 제외한다)가 실시하는 방사선작업종사자에 대한 교육: 신규교육 및 정기교육

2.  법 제106조제1항제2호에 따라 신고사용자가 실시하는 방사선안전관리자에 대한 교육: 정기교육

② 제1항에 따른 교육은 기본교육과 직장교육으로 구분하여 실시한다. 이 경우 직장교육은 방사선안전관리자 외의 방사선작업종사자를 대상으로 한다. \<개정 2014. 11. 19.\>

③ 원자력관계사업자(신고사용자는 제외한다)는 법 제106조제1항제1호에 따라 수시출입자에 대하여 기본교육 또는 직장교육을 실시할 수 있다. \<신설 2016. 4. 12., 2025. 4. 22.\>

④ 제2항 및 제3항에 따른 기본교육은 안전재단에서 받도록 하여야 하며, 직장교육은 해당 원자력관계사업자가 자체적으로 실시하되 위원회가 지정하여 고시하는 기관에 위탁하여 실시할 수 있다. \<개정 2014. 11. 19., 2016. 4. 12., 2016. 6. 21.\>

⑤ 제1항부터 제3항까지의 규정에 따른 교육의 과정 및 시간 등은 총리령으로 정한다. \<개정 2016. 4. 12.\>

⑥ 제149조제1항에 따른 보수교육을 받은 자는 제1항에 따른 해당 연도의 정기교육을 받은 것으로 본다. \<신설 2014. 11. 19., 2016. 4. 12.\>

\[전문개정 2013. 8. 16.\] \[제목개정 2016. 4. 12.\]
:::

### 별표1. 선량한도

-   [선량한도(제2조제4호 관련)](/archive/별표1_선량한도_제2조제4호_관련_원자력안전법_시행령.pdf)

### 별표2. 방사성동위원소등 생산 등의 허가 시 장비기준

-   [방사성동위원소등 생산 등의 허가 시 장비기준(제83조제2항 관련)](/archive/%5B별표%202%5D%20방사성동위원소등%20생산%20등의%20허가%20시%20장비기준(제83조제2항%20관련)(원자력안전법%20시행령).pdf)

### 별표3. 방사성동위원소등 생산 등의 허가 시 인력기준

-   [방사성동위원소등 생산 등의 허가 시 인력기준(제83조제2항 관련)](/archive/%5B별표%203%5D%20방사성동위원소등%20생산%20등의%20허가%20시%20인력기준(제83조제2항%20관련)(원자력안전법%20시행령).pdf)
