---
title: "원자력안전법"
description: |
  [시행 2024. 11. 1.] [법률 제19826호, 2023. 10. 31., 일부개정]<br><br>
  <div style="text-align: right;">
  원자력안전위원회(안전정책과), 02-397-7264<br>
  원자력안전위원회(안전기준과), 02-397-7315<br>
  원자력안전위원회(방사선안전과), 02-397-7273<br>
  원자력안전위원회(생활방사선안전과), 02-397-7334</div>
date: "2024-11-01"
date-modified: "2024-11-01"
categories: [원자력안전법]
---

# 제1장 총칙

### 제1조 목적

::: {.callout-note title="제1조(목적)" collapse="open" appearance="minimal"}
이 법은 원자력의 연구ㆍ개발ㆍ생산ㆍ이용 등에 따른 안전관리에 관한 사항을 규정하여 방사선에 의한 재해의 방지와 공공의 안전을 도모함을 목적으로 한다.
\<개정 2014.5.21.\>
:::

### 제2조 정의

::: {.callout-note title="제2조(정의)" collapse="open" appearance="minimal"}
이 법에서 사용하는 용어의 뜻은 다음과 같다.
\<개정 2013.3.23., 2014.5.21., 2015.1.20., 2015.6.22., 2015.12.22., 2020.12.
22.\>

1.  “원자력”이란 원자핵 변화의 과정에 있어서 원자핵으로부터 방출되는 모든 종류의 에너지를 말한다.

2.  “핵물질”이란 핵연료물질 및 핵원료물질을 말한다.

3.  “핵연료물질”이란 우라늄ㆍ토륨 등 원자력을 발생할 수 있는 물질로서 대통령령으로 정하는 것을 말한다.

4.  “핵원료물질”이란 우라늄광ㆍ토륨광과 그 밖의 핵연료물질의 원료가 되는 물질로서 대통령령으로 정하는 것을 말한다.

5.  “방사성물질”이란 핵연료물질ㆍ사용후핵연료ㆍ방사성동위원소 및 원자핵분열생성물(原子核分裂生成物)을 말한다.

6.  “방사성동위원소”란 방사선을 방출하는 동위원소와 그 화합물 중 대통령령으로 정하는 것을 말한다.

7.  “방사선”이란 전자파 또는 입자선 중 직접 또는 간접으로 공기를 전리(電離)하는 능력을 가진 것으로서 대통령령으로 정하는 것을 말한다.

8.  “원자로”란 핵연료물질을 연료로 사용하는 장치를 말한다.
    다만, 대통령령으로 정하는 것은 제외한다.

9.  “방사선발생장치”란 하전입자(荷電粒子)를 가속시켜 방사선을 발생시키는 장치로서 대통령령으로 정하는 것을 말한다.

10. “관계시설”이란 원자로의 안전에 관계되는 시설로서 대통령령으로 정하는 것을 말한다.

11. “정련”(精鍊)이란 핵원료물질에 포함된 우라늄 또는 토륨의 비율을 높이기 위하여 물리적ㆍ화학적 방법으로 핵원료물질을 처리하는 것을 말한다.

12. “변환”이란 핵연료물질을 화학적 방법으로 처리하여 가공에 적합한 형태로 만드는 것을 말한다.

13. “가공”이란 핵연료물질을 물리적ㆍ화학적 방법으로 처리하여 원자로의 연료로서 사용할 수 있는 형태로 만드는 것을 말한다.

14. “사용후핵연료처리”란 원자로의 연료로서 사용된 핵연료물질 또는 그 밖의 방법으로 원자핵분열을 시킨 핵연료물질을 연구 또는 시험을 목적으로 취급하거나, 물리적ㆍ화학적 방법으로 처리하여 핵연료물질과 그 밖의 물질로 분리하는 것을 말한다.

15. “핵연료주기사업”이란 정련ㆍ변환ㆍ가공 또는 사용후핵연료처리 사업을 말한다.

16. “방사선관리구역”이란 외부의 방사선량율(放射線量率), 공기 중의 방사성물질의 농도 또는 방사성물질에 따라 오염된 물질의 표면의 오염도가 원자력안전위원회규칙으로 정하는 값을 초과할 우려가 있는 곳으로서 방사선의 안전관리를 위하여 사람의 출입을 관리하고 출입자에 대하여 방사선의 장해(障害)를 방지하기 위한 조치가 필요한 구역을 말한다.

17. “국제규제물자”란 원자력의 연구ㆍ개발 및 이용에 관한 조약과 그 밖의 국제약속(이하 “국제약속”이라 한다)에 따라 보장조치의 적용대상이 되는 물자로서 총리령으로 정하는 것을 말한다.

18. “방사성폐기물”이란 방사성물질 또는 그에 따라 오염된 물질(이하 “방사성물질등”이라 한다)로서 폐기의 대상이 되는 물질(제35조제4항에 따라 폐기하기로 결정한 사용후핵연료를 포함한다)을 말한다.

19. “피폭방사선량”(被曝放射線量)이란 사람의 신체의 외부 또는 내부에 피폭하는 방사선량을 말한다.
    다만, 진료를 위하여 피폭하는 방사선량과 인위적으로 증가시키지 아니하는 자연방사선량은 제외한다.
    이 경우 방사선량의 종류 및 적용기준은 원자력안전위원회가 정하여 고시한다.

20. “원자력이용시설”이란 원자력의 연구ㆍ개발ㆍ생산ㆍ이용(이하 “원자력이용”이라 한다)과 관련된 시설로서 대통령령으로 정하는 것을 말한다.

21. “방사선작업종사자”란 원자력이용시설의 운전ㆍ이용 또는 보전이나 방사성물질등의 사용ㆍ취급ㆍ저장ㆍ보관ㆍ처리ㆍ배출ㆍ처분ㆍ운반과 그 밖의 관리 또는 오염제거 등 방사선에 피폭하거나 그 염려가 있는 업무에 종사하는 자를 말한다.

22. “안전관련설비”란 원자로 및 관계시설 중에서 원자력안전위원회규칙으로 정하는 안전에 중요한 구조물ㆍ계통 및 기기로서 원자력안전위원회규칙으로 정하는 바에 따라 안전등급이 부여된 설비를 말한다.

23. “방사선투과검사”란 「비파괴검사기술의 진흥 및 관리에 관한 법률」 제2조에 따른 비파괴검사 중 방사선을 이용한 비파괴검사를 말한다.

24. “해체”란 제20조제1항에 따라 허가를 받은 자, 제30조의2제1항에 따라 허가를 받은 자, 제35조제1항 및 제2항에 따라 허가 또는 지정을 받은 자, 제63조제1항에 따라 건설ㆍ운영 허가를 받은 자가 이 법에 따라 허가 또는 지정을 받은 시설의 운영을 영구적으로 정지(이하 “영구정지”라 한다)한 후, 해당 시설과 부지를 철거하거나 방사성오염을 제거함으로써 이 법의 적용대상에서 배제하기 위한 모든 활동을 말한다.

24의2.
“폐쇄”란 제63조에 따라 방사성폐기물 처분시설 및 그 부속시설의 건설ㆍ운영 허가를 받은 자가 방사성폐기물을 처분하는 활동을 완결하고 장기 안전성을 확보하기 위하여 실시하는 관리적ㆍ기술적 조치(방사성폐기물 처분시설 지하 공간의 뒷채움, 덮개 설치 등을 포함한다)를 말한다.

25. “사고관리”란 원자로시설에 사고가 발생하였을 때 사고가 확대되는 것을 방지하고 사고의 영향을 완화하며 안전한 상태로 회복하기 위하여 취하는 제반조치를 말하며, 원자력안전위원회에서 정하는 설계기준을 초과하여 노심의 현저한 손상을 초래하는 사고(이하 “중대사고”라 한다)에 대한 관리를 포함한다.
:::

### 제2조 정의 [시행일: 2025. 10. 23.]

::: {.callout-note title="제2조(정의)[시행일: 2025. 10. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
이 법에서 사용하는 용어의 뜻은 다음과 같다.
\<개정 2013.3.23., 2014.
5.
21., 2015.
1.
20., 2015.
6.
22., 2015.
12.
22., 2020.
12.
22., 2024.
10.
22.\>

1.  “원자력”이란 원자핵 변화의 과정에 있어서 원자핵으로부터 방출되는 모든 종류의 에너지를 말한다.

2.  “핵물질”이란 핵연료물질 및 핵원료물질을 말한다.

3.  “핵연료물질”이란 우라늄ㆍ토륨 등 원자력을 발생할 수 있는 물질로서 대통령령으로 정하는 것을 말한다.

4.  “핵원료물질”이란 우라늄광ㆍ토륨광과 그 밖의 핵연료물질의 원료가 되는 물질로서 대통령령으로 정하는 것을 말한다.

5.  “방사성물질”이란 핵연료물질ㆍ사용후핵연료ㆍ방사성동위원소 및 원자핵분열생성물(原子核分裂生成物)을 말한다.

6.  “방사성동위원소”란 방사선을 방출하는 동위원소와 그 화합물 중 대통령령으로 정하는 것을 말한다.

7.  “방사선”이란 전자파 또는 입자선 중 직접 또는 간접으로 공기를 전리(電離)하는 능력을 가진 것으로서 대통령령으로 정하는 것을 말한다.

8.  “원자로”란 핵연료물질을 연료로 사용하는 장치를 말한다.
    다만, 대통령령으로 정하는 것은 제외한다.

9.  “방사선발생장치”란 하전입자(荷電粒子)를 가속시켜 방사선을 발생시키는 장치로서 대통령령으로 정하는 것을 말한다.

10. “관계시설”이란 원자로의 안전에 관계되는 시설로서 대통령령으로 정하는 것을 말한다.

11. “정련”(精鍊)이란 핵원료물질에 포함된 우라늄 또는 토륨의 비율을 높이기 위하여 물리적ㆍ화학적 방법으로 핵원료물질을 처리하는 것을 말한다.

12. “변환”이란 핵연료물질을 화학적 방법으로 처리하여 가공에 적합한 형태로 만드는 것을 말한다.

13. “가공”이란 핵연료물질을 물리적ㆍ화학적 방법으로 처리하여 원자로의 연료로서 사용할 수 있는 형태로 만드는 것을 말한다.

14. “사용후핵연료처리”란 원자로의 연료로서 사용된 핵연료물질 또는 그 밖의 방법으로 원자핵분열을 시킨 핵연료물질을 연구 또는 시험을 목적으로 취급하거나, 물리적ㆍ화학적 방법으로 처리하여 핵연료물질과 그 밖의 물질로 분리하는 것을 말한다.

15. “핵연료주기시설”이란 정련ㆍ변환ㆍ가공 또는 사용후핵연료처리를 위한 시설을 말한다.

16. “방사선관리구역”이란 외부의 방사선량율(放射線量率), 공기 중의 방사성물질의 농도 또는 방사성물질에 따라 오염된 물질의 표면의 오염도가 원자력안전위원회규칙으로 정하는 값을 초과할 우려가 있는 곳으로서 방사선의 안전관리를 위하여 사람의 출입을 관리하고 출입자에 대하여 방사선의 장해(障害)를 방지하기 위한 조치가 필요한 구역을 말한다.

17. “국제규제물자”란 원자력의 연구ㆍ개발 및 이용에 관한 조약과 그 밖의 국제약속(이하 “국제약속”이라 한다)에 따라 보장조치의 적용대상이 되는 물자로서 총리령으로 정하는 것을 말한다.

18. “방사성폐기물”이란 방사성물질 또는 그에 따라 오염된 물질(이하 “방사성물질등”이라 한다)로서 폐기의 대상이 되는 물질(제36조의2에 따라 폐기하기로 결정한 사용후핵연료를 포함한다)을 말한다.

19. “피폭방사선량”(被曝放射線量)이란 사람의 신체의 외부 또는 내부에 피폭하는 방사선량을 말한다.
    다만, 진료를 위하여 피폭하는 방사선량과 인위적으로 증가시키지 아니하는 자연방사선량은 제외한다.
    이 경우 방사선량의 종류 및 적용기준은 원자력안전위원회가 정하여 고시한다.

20. “원자력이용시설”이란 원자력의 연구ㆍ개발ㆍ생산ㆍ이용(이하 “원자력이용”이라 한다)과 관련된 시설로서 대통령령으로 정하는 것을 말한다.

21. “방사선작업종사자”란 원자력이용시설의 운전ㆍ이용 또는 보전이나 방사성물질등의 사용ㆍ취급ㆍ저장ㆍ보관ㆍ처리ㆍ배출ㆍ처분ㆍ운반과 그 밖의 관리 또는 오염제거 등 방사선에 피폭하거나 그 염려가 있는 업무에 종사하는 자를 말한다.

22. “안전관련설비”란 원자로 및 관계시설 중에서 원자력안전위원회규칙으로 정하는 안전에 중요한 구조물ㆍ계통 및 기기로서 원자력안전위원회규칙으로 정하는 바에 따라 안전등급이 부여된 설비를 말한다.

23. “방사선투과검사”란 「비파괴검사기술의 진흥 및 관리에 관한 법률」 제2조에 따른 비파괴검사 중 방사선을 이용한 비파괴검사를 말한다.

24. “해체”란 다음 각 목의 허가를 받은 자가 허가받은 시설의 운영을 영구적으로 정지(이하 “영구정지”라 한다)한 후 해당 시설과 부지를 철거하거나 방사성오염을 제거함으로써 이 법의 적용대상에서 배제하기 위한 모든 활동을 말한다.

가.
제20조제1항에 따른 발전용원자로 및 관계시설의 운영허가

나.
제30조의2제1항에 따른 연구용 또는 교육용 원자로 및 관계시설의 운영허가

다.
제39조의4제1항에 따른 핵연료주기시설의 운영허가

라.
제63조제1항에 따른 방사성폐기물관리시설등(처분시설 및 그 부속시설은 제외한다)의 건설ㆍ운영 허가

24의2.
“폐쇄”란 제63조에 따라 방사성폐기물 처분시설 및 그 부속시설의 건설ㆍ운영 허가를 받은 자가 방사성폐기물을 처분하는 활동을 완결하고 장기 안전성을 확보하기 위하여 실시하는 관리적ㆍ기술적 조치(방사성폐기물 처분시설 지하 공간의 뒷채움, 덮개 설치 등을 포함한다)를 말한다.

25. “사고관리”란 원자로시설에 사고가 발생하였을 때 사고가 확대되는 것을 방지하고 사고의 영향을 완화하며 안전한 상태로 회복하기 위하여 취하는 제반조치를 말하며, 원자력안전위원회에서 정하는 설계기준을 초과하여 노심의 현저한 손상을 초래하는 사고(이하 “중대사고”라 한다)에 대한 관리를 포함한다.

\[시행일: 2025.10.23.\] 제2조
:::

# 제5장 방사성동위원소 및 방사선발생장치

### 제53조 방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등

::: {.callout-note title="제53조(방사성동위원소ㆍ방사선발생장치 사용 등의 허가 등)" collapse="open" appearance="minimal"}
① 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)를 생산ㆍ판매ㆍ사용(소지ㆍ취급을 포함한다. 이하 같다) 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회의 허가를 받아야 한다.
허가받은 사항을 변경하려는 때에도 또한 같다.
다만, 총리령으로 정하는 일시적인 사용 장소의 변경과 그 밖의 경미한 사항을 변경하려는 때에는 이를 신고하여야 한다.\<개정 2013.3.23.\>

② 제1항에도 불구하고 총리령으로 정하는 용도 또는 수량 이하의 밀봉된 방사성동위원소 또는 총리령으로 정하는 용도 또는 용량 이하의 방사선발생장치를 사용 또는 이동사용하려는 자는 대통령령으로 정하는 바에 따라 위원회에 신고하여야 한다.
신고한 사항을 변경하려는 때에도 또한 같다.\<개정 2013.3.23.\>

③ 제1항에 따른 허가를 받으려는 자는 허가신청서에 안전성분석보고서, 품질보증계획서, 방사선안전보고서 및 안전관리규정과 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 하며, 제2항에 따른 신고를 하려는 자는 신고서에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다.
다만, 안전성분석보고서 및 품질보증계획서의 제출은 생산허가를 받으려는 자에 한한다.\<개정 2013.3.23.\>

④ 위원회는 제1항 단서 또는 제2항에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다.\<신설 2022.6.10.\>

⑤ 제1항에 따라 허가를 받은 자(이하 “허가사용자”라 한다) 및 제2항에 따라 신고를 한 자(이하 “신고사용자”라 한다)의 결격사유에 관하여는 제14조를 준용한다.
이 경우 제14조 본문 중 “제10조제1항의 허가를 받을 수 없다”는 “제53조제1항ㆍ제2항의 허가를 받거나 신고를 할 수 없다”로, 같은 조 제3호 중 “제17조에 따라 허가가 취소된 후”는 “제57조에 따라 허가취소ㆍ사용금지된 후”로, 같은 조 제4호 중 “임원 중에”는 “대표자가”로 본다.\<개정 2022.6.10.\>
:::

### 제53조의2(대형 방사선발생장치 사용 허가의 사전검토)

::: {.callout-note title="제53조의2(대형 방사선발생장치 사용 허가의 사전검토)" collapse="open" appearance="minimal"}
① 제53조제1항 전단에 따라 방사선발생장치 중 대통령령으로 정하는 종류 또는 용량 이상의 방사선발생장치(이하 “대형방사선발생장치”라 한다)의 사용 허가를 받으려는 자는 총리령으로 정하는 공사착공일 전에 해당 대형방사선발생장치가 제55조제1항에 따른 허가기준에 적합한지에 대하여 위원회에 사전검토를 신청하여야 한다.

② 위원회는 제1항에 따른 사전검토를 신청받은 경우에는 허가기준에 적합한지를 검토한 후 그 결과를 신청인에게 서면으로 통보하여야 한다.

③ 위원회는 대형방사선발생장치에 대하여 제53조제1항 전단에 따른 사용 허가 여부를 결정할 때에는 제2항에 따라 통보한 사전검토 결과를 고려하여야 한다.

④ 제1항부터 제3항까지에서 규정한 사항 외에 제1항에 따른 사전검토의 대상ㆍ범위 및 절차ㆍ방법 등에 필요한 세부 사항은 총리령으로 정한다.

\[본조신설 2022.6.10.\]<br>\
\[종전 제53조의2는 제53조의3으로 이동 \<2022.6.10.\>\]
:::

### 제53조의3(방사선안전관리자)  {#제53조의3}

::: {.callout-note title="제53조의3(방사선안전관리자)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 방사선 안전관리에 관한 다음 각 호의 업무를 수행하기 위하여 대통령령으로 정하는 바에 따라 방사선안전관리자를 선임하여 방사성동위원소등의 사용개시 전에 이를 위원회에 신고하여야 한다.
신고한 사항을 변경하려는 때에도 또한 같다.

1.  제53조제3항의 안전관리규정 및 제59조제1항의 기술기준의 준수여부 점검

2.  방사선작업종사자 또는 방사선관리구역에 출입하는 자에 대한 제91조에 따른 방사선장해방지조치

3.  허가사용자 및 신고사용자에 대한 방사선 안전관리에 관한 조치 권고

4.  그 밖에 방사선 안전관리를 위하여 필요한 조치

② 위원회는 방사선안전관리자가 제1항에 따른 업무를 게을리한 때에는 허가사용자 및 신고사용자에게 그 방사선안전관리자의 해임을 요구할 수 있다.

③ 허가사용자 및 신고사용자는 제2항에 따른 해임요구를 받은 때에는 정당한 사유가 없으면 해당 방사선안전관리자를 지체 없이 해임하고 새로운 방사선안전관리자를 선임하되, 해임한 날부터 30일 이내에 위원회에 선임신고 및 해임신고를 하여야 한다.

④ 허가사용자 및 신고사용자는 제3항에 따라 해임된 후 1년이 지나지 아니한 사람을 방사선안전관리자로 선임하여서는 아니 된다.

⑤ 허가사용자, 신고사용자, 방사선작업종사자 및 방사선관리구역출입자는 방사선 안전관리에 관한 방사선안전관리자의 조치와 권고에 따라야 한다.

⑥ 방사선안전관리자의 자격요건 등에 필요한 사항은 대통령령으로 정한다.

⑦ 방사선안전관리자 및 대리자의 자격 요건, 대리자의 직무대행기간 등에 필요한 사항은 대통령령으로 정한다.
\<개정 2018.8.14.\>

⑧ 위원회는 제1항에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다.
\<신설 2022.6.10.\>

\[본조신설 2014.5.21.\] <br>\
\[제53조의2에서 이동 \<2022.6.10.\>\]
:::

### 제54조(업무대행자의 등록)

::: {.callout-note title="제54조(업무대행자의 등록)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자를 대행하여 다음 각 호의 어느 하나의 업무를 하려는 자는 위원회에 등록하여야 한다.
\<개정 2013.3.23.\>

1.  방사선오염의 제거

2.  방사성동위원소등 및 방사성폐기물의 수거ㆍ처리 및 운반

3.  방사선안전보고서ㆍ안전관리규정의 작성

4.  사용시설등의 설치에 대한 감리

5.  방사선안전관리

6.  그 밖에 총리령으로 정하는 방사선의 안전관리 및 장해방지 관련 업무

② 제1항에 따라 등록한 자(이하 “업무대행자”라 한다)가 등록한 사항을 변경하려면 이를 위원회에 신고하여야 한다.

③ 제1항에 따른 등록을 하려는 자는 그 신청서에 업무대행규정과 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다.
\<개정 2013.3.23.\>

④ 위원회는 제2항에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다.
\<신설 2022.6.10.\>

⑤ 제1항에 따른 등록의 결격사유에 관하여는 제14조를 준용한다.
이 경우 제14조 본문 중 “제10조제1항의 허가를 받을 수 없다”는 “제54조제1항의 등록을 할 수 없다”로, 같은 조 제3호 중 “제17조에 따라 허가가 취소된 후”는 “제57조에 따라 등록이 취소된 후”로, 같은 조 제4호 중 “임원 중에”는 “대표자가”로 본다.
\<개정 2022.6.10.\>
:::

### 제55조(허가기준 등)

::: {.callout-note title="제55조(허가기준 등)" collapse="open" appearance="minimal"}
① 제53조제1항에 따른 허가기준은 다음과 같다.

1.  생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비가 위원회규칙으로 정하는 기술기준에 적합할 것

2.  방사성동위원소 또는 그에 따라 오염된 물질 또는 방사선발생장치에 따라 발생한 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니할 것

3.  생산하려는 방사성동위원소등의 성능 및 품질보증계획서의 내용이 위원회가 정하여 고시하는 기준에 적합할 것

4.  대통령령으로 정하는 장비 및 인력을 확보할 것

② 제54조제1항에 따른 등록기준은 다음 각 호와 같다.\<개정 2013.3.23.\>

1.  총리령으로 정하는 대행업무 수행에 필요한 기술능력을 확보하고 있을 것

2.  대통령령으로 정하는 장비 및 인력을 확보할 것

3.  대행업무의 범위 및 업무대행규정이 총리령으로 정하는 기준에 적합할 것
:::

### 제56조(검사)

::: {.callout-note title="제56조(검사)" collapse="open" appearance="minimal"}
① 허가사용자 및 업무대행자는 방사성동위원소등의 생산ㆍ판매ㆍ사용ㆍ이동사용 또는 대행업무를 대통령령으로 정하는 바에 따라 위원회의 검사를 받아야 한다.
다만, 대통령령으로 정하는 바에 따라 검사가 면제되는 경우에는 그러하지 아니하다.

② 위원회는 제1항에 따른 검사결과 다음 각 호의 어느 하나에 해당하면 허가사용자 또는 업무대행자에게 그 시정 또는 보완을 명할 수 있다.

1.  제55조제1항에 따른 허가기준 또는 제55조제2항에 따른 등록기준에 미달될 때

2.  제53조제3항에 따른 안전관리규정 또는 제54조제3항에 따른 업무대행규정을 위반하였을 때
:::

### 제57조(생산ㆍ판매ㆍ사용 또는 이동사용 허가 등의 취소 등)

::: {.callout-note title="제57조(생산ㆍ판매ㆍ사용 또는 이동사용 허가 등의 취소 등)" collapse="open" appearance="minimal"}
① 위원회는 허가사용자ㆍ신고사용자 또는 업무대행자가 다음 각 호의 어느 하나에 해당하면 그 허가ㆍ등록의 취소 또는 1년 이내의 기간을 정하여 그 업무를 정지하거나 사용금지(신고사용자만 해당한다)를 명할 수 있다.
다만, 제1호 또는 제4호에 해당하는 때에는 그 허가 또는 등록을 취소하여야 한다.
\<개정 2014.
5.
21.\>

1.  거짓이나 그 밖의 부정한 방법으로 허가를 받았거나 신고 또는 등록한 때

2.  정당한 사유 없이 대통령령으로 정하는 기간 안에 그 허가받은 사용 또는 사업을 개시하지 아니하거나 1년 이상 계속하여 중단한 때

3.  제53조제1항 후단, 제2항 후단 또는 제54조제2항에 따라 변경허가 또는 변경신고를 하지 아니하고 허가받은 사항이나 신고 또는 등록한 사항을 변경한 때

4.  제53조제4항 및 제54조제4항에서 준용하는 제14조제1호ㆍ제2호 및 제4호 중 어느 하나에 해당하게 된 때.
    다만, 법인의 대표자가 그 사유에 해당하게 된 경우 3개월 이내에 그 대표자를 바꾸어 선임한 때에는 그러하지 아니하다.

5.  제55조의 허가 또는 등록 기준에 미달하게 된 때

6.  제56조제2항, 제59조제2항, 제92조제2항 또는 제98조제1항 및 제3항에 따른 명령을 위반한 때

7.  제59조제3항ㆍ제70조ㆍ제94조ㆍ제96조 또는 제106조제1항을 위반한 때

8.  제99조의 허가조건을 위반한 때

② 위원회는 제1항에 따라 업무의 정지 또는 사용금지를 명하여야 할 경우에 그 업무의 정지 또는 사용금지를 갈음하여 5억원 이하의 과징금을 부과할 수 있다.
\<개정 2014.
5.
21.\>

③ 제1항에 따른 업무의 정지 또는 사용금지 처분기준과 제2항에 따른 과징금의 부과기준은 대통령령으로 정한다.
\<개정 2014.
5.
21.\>

④ 위원회는 제2항에 따른 과징금을 내야 할 자가 납부기한까지 과징금을 내지 아니하면 국세체납처분의 예에 따라 이를 징수하거나 제2항에 따른 과징금 부과처분을 취소하고 제1항에 따른 업무정지처분 또는 사용금지처분을 하여야 한다.
\<개정 2014.
5.
21.\>
:::

### 제57조(생산ㆍ판매ㆍ사용 또는 이동사용 허가 등의 취소 등) \[시행일: 2025. 10. 23.\]

::: {.callout-note title="제57조(생산ㆍ판매ㆍ사용 또는 이동사용 허가 등의 취소 등) [시행일: 2025. 10. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
① 위원회는 허가사용자ㆍ신고사용자 또는 업무대행자가 다음 각 호의 어느 하나에 해당하면 그 허가ㆍ등록의 취소 또는 1년 이내의 기간을 정하여 그 업무를 정지하거나 사용금지(신고사용자만 해당한다)를 명할 수 있다.
다만, 제1호 또는 제4호에 해당하는 때에는 그 허가 또는 등록을 취소하여야 한다.
\<개정 2014.
5.
21.\>

1.  거짓이나 그 밖의 부정한 방법으로 허가를 받았거나 신고 또는 등록한 때

2.  정당한 사유 없이 대통령령으로 정하는 기간 안에 그 허가받은 사용 또는 사업을 개시하지 아니하거나 1년 이상 계속하여 중단한 때

3.  제53조제1항 후단, 제2항 후단 또는 제54조제2항에 따라 변경허가 또는 변경신고를 하지 아니하고 허가받은 사항이나 신고 또는 등록한 사항을 변경한 때

4.  제53조제4항 및 제54조제4항에서 준용하는 제14조제1호ㆍ제2호 및 제4호 중 어느 하나에 해당하게 된 때.
    다만, 법인의 대표자가 그 사유에 해당하게 된 경우 3개월 이내에 그 대표자를 바꾸어 선임한 때에는 그러하지 아니하다.

5.  제55조의 허가 또는 등록 기준에 미달하게 된 때

6.  제56조제2항, 제59조제2항, 제92조제2항 또는 제98조제1항 및 제3항에 따른 명령을 위반한 때

7.  제59조제3항ㆍ제70조ㆍ제94조ㆍ제96조 또는 제106조제1항을 위반한 때

8.  제99조의 허가조건을 위반한 때

② 위원회는 제1항에 따라 업무의 정지 또는 사용금지를 명하여야 할 경우에 그 업무의 정지 또는 사용금지를 갈음하여 5억원 이하의 과징금을 부과할 수 있다.
\<개정 2014.
5.
21.\>

③ 제1항에 따른 업무의 정지 또는 사용금지 처분기준과 제2항에 따른 과징금의 부과기준은 대통령령으로 정한다.
\<개정 2014.
5.
21.\>

[④ 위원회는 제2항에 따른 과징금을 내야 할 자가 납부기한까지 과징금을 내지 아니하면 국세강제징수의 예에 따라 이를 징수하거나 제2항에 따른 과징금 부과처분을 취소하고 제1항에 따른 업무정지처분 또는 사용금지처분을 하여야 한다.]{style="color:red;"}
\<개정 2014.
5.
21., 2024.
10.
22.\>

\[시행일: 2025.
10.
23.\] 제57조
:::

### 제58조(기록과 비치)

::: {.callout-note title="제58조(기록과 비치)" collapse="open" appearance="minimal"}
허가사용자ㆍ신고사용자 및 업무대행자는 총리령으로 정하는 바에 따라 방사성동위원소등의 생산ㆍ사용ㆍ이동사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리ㆍ배출ㆍ판매 또는 업무대행 등에 관한 사항을 기록하여 이를 공장 또는 사업소마다 비치하여야 한다.
\<개정 2013.
3.
23.\>
:::

### 제59조(기준준수의무 등)

::: {.callout-note title="제59조(기준준수의무 등)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 다음 사항에 관하여 위원회규칙으로 정하는 기술기준을 준수하여야 한다.

1.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비

2.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리 및 배출

3.  방사성동위원소등의 이동사용 및 판매

② 위원회는 사업소 안에서의 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설 또는 사용시설등의 위치ㆍ구조 및 설비, 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ처리 및 배출과 방사성동위원소등의 이동사용이나 판매가 제1항에 따른 기술기준에 적합하지 아니하다고 인정하면 허가사용자 및 신고사용자에게 해당 시설의 수리ㆍ개선ㆍ이전 또는 생산ㆍ사용의 정지, 취급방법의 변경과 그 밖의 안전에 필요한 조치를 명할 수 있다.

③ 허가사용자 및 그 종업원은 제53조제3항에 따른 안전관리규정을 준수하여야 하며, 업무대행자와 그 종업원은 제54조제3항에 따른 업무대행규정을 준수하여야 한다.
:::

### 제59조의2(발주자의 안전조치 의무)

::: {.callout-note title="제59조의2(발주자의 안전조치 의무)" collapse="open" appearance="minimal"}
① 방사선투과검사를 위하여 제53조에 따라 방사성동위원소등을 이동사용하는 경우 방사선투과검사를 의뢰한 발주자(이하 “발주자”라 한다)는 발주자의 사업장에서 방사성동위원소등을 이동사용하는 방사선작업종사자가 과도한 방사선에 노출되지 아니하도록 위원회규칙으로 정하는 바에 따라 안전한 작업환경을 제공하여야 한다.

② 위원회는 발주자에게 다음 각 호의 안전설비의 설치 또는 보완을 명할 수 있다.

1.  제91조에 따른 방사선장해방지조치에 적합한 전용작업장

2.  방사선방호를 위한 차폐시설 또는 차폐물

③ 위원회는 다음 각 호의 어느 하나에 해당하는 사유로 인하여 방사선작업종사자의 안전이 위협받을 때에는 위원회규칙으로 정하는 바에 따라 방사선투과검사 작업의 중지를 명할 수 있다.
\<개정 2021.
4.
20.\>

1.  발주자가 제1항에 따른 안전한 작업환경을 제공하지 아니한 경우

2.  위원회가 제2항에 따라 발주자에게 안전설비의 설치 또는 보완을 명하였음에도 발주자가 이를 이행하지 아니한 경우

④ 제3항에 따라 작업이 중지된 작업장에서는 방사선투과검사를 실시하여서는 아니 된다.

⑤ 제3항에 따라 작업이 중지된 작업장에 대하여 발주자 및 허가사용자 또는 신고사용자가 작업을 재개하기 위한 이행사항ㆍ절차ㆍ방법 및 그 밖에 필요한 사항은 대통령령으로 정한다.

⑥ 발주자는 안전한 작업환경 조성을 위하여 방사선작업종사자의 실제 일일작업량을 위원회에 보고하여야 한다.
이 경우 보고 대상ㆍ방법 및 절차 등에 필요한 사항은 위원회규칙으로 정한다.

⑦ 방사성동위원소등을 이동사용하여 방사선투과검사를 실시할 때 방사선안전관리자가 안전한 방사선투과검사의 수행을 위하여 발주자에게 필요한 조치나 협력을 요청할 경우 발주자는 이에 따라야 한다.

⑧ 제2항에 따른 안전설비의 세부기준 등에 필요한 사항은 위원회규칙으로 정한다.

\[본조신설 2014.5.21.\]
:::

### 제60조(방사선발생장치 등의 설계승인 등)

::: {.callout-note title="제60조(방사선발생장치 등의 설계승인 등)" collapse="open" appearance="minimal"}
① 방사선발생장치 또는 방사성동위원소가 내장된 기기(이하 “방사선기기”라 한다)를 제작하려는 자 또는 외국에서 제작된 방사선기기를 수입하려는 자는 방사선기기의 형식별로 설계에 대하여 총리령으로 정하는 바에 따라 위원회의 승인을 받아야 한다.
이를 변경하려는 때에도 또한 같다.
다만, 총리령으로 정하는 경미한 사항을 변경하려는 때에는 이를 위원회에 신고하여야 한다.
\<개정 2013.
3.
23., 2017.
12.
19.\>

② 제1항에도 불구하고 다음 각 호의 어느 하나에 해당하는 경우에는 위원회의 승인을 받지 아니하고 방사선기기를 제작하거나 수입할 수 있다.
\<신설 2017.
12.
19.\>

1.  제1항에 따라 승인을 받은 방사선기기와 동일한 형식의 방사선기기를 제작하거나 수입하려는 경우

2.  시험용으로 시제품을 개발하거나 비영리 단체의 학술연구를 위한 경우로서 위원회가 정하여 고시하는 기준에 적합한 경우

3.  수출전용으로 방사선기기를 제작하는 경우로서 위원회가 정하여 고시하는 기준에 적합한 경우

4.  그 밖에 대통령령으로 정하는 경우

③ 제1항에 따른 승인을 받으려는 자는 방사선기기의 설계자료, 안전성평가자료, 품질보증계획서(방사선기기를 제작하려는 경우만 해당한다)와 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다.
\<개정 2013.
3.
23., 2017.
12.
19.\>

④ 제1항에 따른 방사선기기의 형식별 설계승인의 기준은 대통령령으로 정한다.
\<신설 2017.
12.
19.\>

⑤ 위원회는 제1항 단서에 따른 신고를 받은 경우 그 내용을 검토하여 이 법에 적합하면 신고를 수리하여야 한다.
\<신설 2022.
6.
10.\>
:::

### 제61조(검사)

::: {.callout-note title="제61조(검사)" collapse="open" appearance="minimal"}
① 제60조제1항에 따라 승인을 받은 자는 제작 또는 수입한 방사선기기를 승인받은 방사선기기의 형식별로 총리령으로 정하는 바에 따라 위원회의 검사를 받아야 한다.
다만, 다음 각 호의 어느 하나에 해당하는 경우에는 그러하지 아니하다.
\<개정 2017.
12.
19.\>

1.  검사에 합격한 방사선기기와 동일한 형식의 방사선기기를 제작하거나 수입하는 경우

2.  제작국의 인허가 절차를 완료한 방사선기기를 수입하는 경우로서 위원회가 정하여 고시하는 기준에 적합한 경우

② 제1항에 따른 검사의 기준에 필요한 사항은 위원회가 정하여 고시한다.
\<신설 2017.
12.
19.\>

③ 허가사용자 및 신고사용자는 다음 각 호의 어느 하나에 해당하는 방사선기기를 사용하여야 한다.
\<개정 2017.
12.
19.\>

1.  제1항 본문에 따른 검사에 합격되거나 제1항 단서에 따라 검사가 면제된 방사선기기

2.  제60조제2항에 따라 설계에 대한 승인이 면제된 방사선기기
:::

### 제62조(준용)

::: {.callout-note title="제62조(준용)" collapse="open" appearance="minimal"}
허가사용자ㆍ신고사용자 및 업무대행자의 사업 승계와 신고에 관하여는 제19조 및 제43조를 준용한다.
이 경우 “발전용원자로설치자” 또는 “핵연료주기사업자”는 “허가사용자ㆍ신고사용자 및 업무대행자”로 본다.
:::

### 제62조(준용) \[시행일: 2025. 10. 23.\]

::: {.callout-note title="제62조(준용) [시행일: 2025. 10. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[허가사용자ㆍ신고사용자 및 업무대행자의 사업 승계와 신고에 관하여는 제19조 및 제43조를 준용한다. 이 경우 “발전용원자로설치자” 또는 “핵연료주기시설운영자”는 “허가사용자ㆍ신고사용자 및 업무대행자”로 본다.]{style="color:red;"}
\<개정 2024.10.22.\>

\[시행일: 2025.10.23.\] 제62조
:::

# 제6장 폐기 및 운반

### 제70조(방사성폐기물의 처분제한)

::: {.callout-note title="제70조(방사성폐기물의 처분제한)" collapse="open" appearance="minimal"}
① 누구든지 방사성폐기물을 해양에 투기(投棄)하는 방법으로 처분할 수 없다.

② 방사성폐기물처분시설등건설ㆍ운영자가 아닌 자는 총리령으로 정하는 종류 및 수량의 방사성폐기물을 땅속에 천층(淺層)처분(동굴처분을 포함한다) 또는 심층(深層)처분 등의 방법으로 처분할 수 없다.
\<개정 2013.
3.
23., 2015.
1.
20., 2020.
12.
22.\>

③ 제2항에 따른 방사성폐기물 외의 방사성폐기물의 처분은 대통령령으로 정하는 방법 및 절차에 적합하게 하여야 한다.

④ 제2항에 따른 방사성폐기물의 처분을 방사성폐기물관리시설등건설ㆍ운영자에게 위탁하려는 자는 총리령으로 정하는 인도(引渡)기준에 적합하게 하여야 한다.
\<개정 2013.
3.
23., 2015.
1.
20.\>
:::

# 제9장 규제ㆍ감독

### 제91조(방사선장해방지조치)

::: {.callout-note title="제91조(방사선장해방지조치)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

4.  방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치

② 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.

③ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.
:::

### 제91조(방사선장해방지조치) \[시행일: 2025. 4. 23.\]

::: {.callout-note title="제91조(방사선장해방지조치) [시행일: 2025. 4. 23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[① 원자력관계사업자(신고사용자는 제외한다)는 방사선장해를 방지하기 위하여 대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다.]{style="color:red;"}
\<개정 2024.
10.
22.\>

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

<p style="text-indent: 20px;">

[4. 삭제]{style="color:red;"} \<2024.
10.
22.\>

</p>

[② 원자력관계사업자는 대통령령으로 정하는 바에 따라 방사성물질의 방출량 및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한 조치를 하여야 한다.]{style="color:red;"}
\<신설 2024.
10.
22.\>

[③ 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는 수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지 아니하도록 필요한 조치를 하여야 한다.]{style="color:red;"}
\<개정 2024.
10.
22.\>

[④ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은 것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상 필요한 조치를 하여야 한다.]{style="color:red;"}
\<개정 2024.
10.
22.\>

\[시행일: 2025.
4.
23.\] 제91조
:::

### 제98조(보고ㆍ검사 등)

::: {.callout-note title="제98조(보고ㆍ검사 등)" collapse="open" appearance="minimal"}
① 위원회는 이 법의 시행을 위하여 필요하다고 인정하면 원자력관계사업자ㆍ판독업무자와 원자로 및 관계시설의 건설 또는 운영에 참여하는 사업자와 국제규제물자를 취급하거나 관련 연구를 수행하는 자로서 대통령령으로 정하는 자에게 그 업무에 관한 보고 또는 서류의 제출 및 제출된 서류의 보완을 명할 수 있다.

② 위원회는 제1항에 따라 보고받은 내용 및 제출된 서류의 현장 확인을 위하여 필요한 경우, 원자력이용시설의 안전을 위하여 특히 필요하다고 인정하는 경우 또는 이 법에 따른 각종 검사를 수행하기 위하여 필요하면 소속 공무원으로 하여금 그 사업소ㆍ공장ㆍ선박ㆍ연구시설 또는 부지 등에 출입하여 장부ㆍ서류ㆍ시설과 그 밖의 필요한 물건을 검사하게 하거나 관계인에게 질문하게 할 수 있으며, 시험을 위하여 필요한 최소량의 시료를 수거하게 할 수 있다.

③ 위원회는 제2항에 따라 검사 등을 실시한 결과 이 법과 국제약속을 위반한 사항이 있으면 그 시정 또는 보완을 명할 수 있다.

④ 국제약속에 따라 국제원자력기구가 지정하는 자 또는 국제규제물자공급 당사국 정부가 지정하는 자는 위원회가 지정하는 소속 공무원의 감독하에 국제약속으로 정한 범위에서 국제규제물자를 취급하거나 관련 연구를 수행하는 자의 사업소ㆍ공장ㆍ선박ㆍ연구시설 및 부지 등에 출입하여 장부ㆍ서류ㆍ시설과 그 밖의 필요한 물건을 검사하고, 관계인에게 질문하거나 시험을 위하여 필요한 최소량의 시료를 수거할 수 있다.

⑤ 국제원자력기구가 지정하는 자는 위원회가 지정하는 소속 공무원의 감독하에 국제약속으로 정한 범위에서 국제규제물자의 이동을 감시하기 위한 설비를 설치하거나 봉인을 할 수 있다.

⑥ 위원회는 대통령령으로 정하는 바에 따라 국제규제물자의 이동을 확인하거나 정보를 관리하기 위하여 필요한 조치를 할 수 있다.

⑦ 제2항 및 제4항부터 제6항까지의 규정에 따라 검사하거나 국제규제물자의 이동을 감시ㆍ확인하기 위하여 직무를 수행하는 자는 그 권한을 나타내는 증표를 관계인에게 내보여야 한다.
:::

# 제10장 보칙

### 제106조(교육훈련)

::: {.callout-note title="제106조(교육훈련)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 방사선작업종사자와 방사선 관리 구역에 출입하는 사람에게 대통령령으로 정하는 바에 따라 원자력이용에 따르는 안전성 확보 및 방사선장해방지에 필요한 교육 및 훈련을 실시하여야 한다.

② 제84조에 따라 면허를 받은 사람은 대통령령으로 정하는 바에 따라 위원회가 실시하는 보수교육을 받아야 한다.

③ 원자력관계사업자와 원자력관련 연구를 수행하는 기관은 대통령령으로 정하는 사람에게 총리령으로 정하는 바에 따라 위원회가 실시하는 원자력통제에 관한 교육을 받게 하여야 한다.
\<개정 2017.
12.
19.\>
:::

### 제106조(교육훈련) \[시행일: 2025.4.23.\]

::: {.callout-note title="제106조(교육훈련) [시행일: 2025.4.23.]" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[① 원자력관계사업자는 다음 각 호의 구분에 따른 사람에게 대통령령으로 정하는 바에 따라 원자력이용에 따르는 안전성 확보와 방사선장해방지에 필요한 교육 및 훈련을 실시하여야 한다.]{style="color:red;"}
\<개정 2024.
10.
22.\>

[1. 원자력관계사업자(신고사용자는 제외한다)의 경우: 방사선작업종사자 및 방사선관리구역에 출입하는 사람]{style="color:red;"}

[2. 신고사용자의 경우: 방사선안전관리자]{style="color:red;"}

② 제84조에 따라 면허를 받은 사람은 대통령령으로 정하는 바에 따라 위원회가 실시하는 보수교육을 받아야 한다.

③ 원자력관계사업자와 원자력관련 연구를 수행하는 기관은 대통령령으로 정하는 사람에게 총리령으로 정하는 바에 따라 위원회가 실시하는 원자력통제에 관한 교육을 받게 하여야 한다.
\<개정 2017.
12.
19.\>

\[시행일: 2025.
4.
23.\] 제106조
:::
