---
title: "방사선안전보고서 관리"
description: "안전관리자의 업무로써 방사선안전보고서 작성에 대한 설명입니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-11-27"
date-modified: "2025-01-13"
categories: [방사선안전관리자, 업무, 안전보고서]
---

### 방사선안전보고서 주요사항

-   <a href="../../law/nuclear_safety_enforcement_rule.qmd#제58조" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기">시행규칙 제58조(방사성동위원소등의 생산허가 신청 등) </a> 제4항에 따르면 아래의 각 사항들이 기술되어야 합니다.

::: {.callout-important title="규칙에 따라 방사선안전보고서에 적어야할 사항" collapse="open"}
1.  시설 개요

2.  시설주변의 환경

3.  운영계획 개요

4.  방사선원의 특성ㆍ위치 및 제원

5.  안전시설 개요

6.  방사선취급방법 및 방사선안전관리계획

7.  예상피폭선량의 평가에 관한 절차ㆍ방법 및 결과

8.  주변환경에 대한 방사선 영향

9.  사고의 위험 및 그 대책

10. 방사성폐기물의 발생 및 처리계획

11. 방사선안전보고서의 작성자의 인적사항 및 자격
:::

### 방사선안전보고서 작성지침

-   <a href="../../law/rsr_preperation_regulation.qmd#제5조" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기">방사선안전보고서 작성지침 \[시행 2023. 3. 11.\] \[원자력안전위원회고시 제2023-4호, 2023. 3. 6., 일부개정\]제5조 </a> 에 기술된 세부작성지침에 따라 작성하여야 합니다.

::: {.callout-important title="제5조(세부 작성지침)" collapse="open"}
① 보고서는 다음 각 호에서 정하는 바에 따라 별표의 세부 작성지침에 따라 작성하여야 한다. 다만, 「원자력안전법 시행규칙」 제68조의2제1항에 따른 사전검토 신청서에 첨부하는 서류를 작성하는 경우 제1호부터 제5호까지의 항목에 대하여 작성한다.

1.  시설 개요 방사선을 취급하는 사업 및 시설의 주체ㆍ위치ㆍ취급목적 및 방사선원에 대한 기본정보를 기술한다.

2.  시설주변의 환경 방사선취급에 영향을 미치거나 방사선취급으로 영향을 받을 수 있는 주변환경의 특성에 대하여 기술한다.

3.  운영계획 개요 방사선시설의 설치, 방사선원의 도입, 방사선의 취급, 인력 확보 등 사업추진계획에 대하여 기술한다.

4.  방사선원의 특성ㆍ위치 및 제원 방사선원의 종류ㆍ수량ㆍ용량ㆍ특성 및 고유 안전기능과 선원이 취급되는 위치에 대하여 기술한다.

5.  안전시설 개요 안전시설 및 계통의 종류ㆍ제원ㆍ특성 및 사용관리 방안에 대하여 기술한다.

6.  방사선 취급방법 및 방사선안전관리 계획 방사선원을 취급하는 공정 및 절차에 대하여 설명하고, 방사선안전관리 계획을 구체적으로 기술한다.

7.  예상 피폭선량의 평가에 관한 절차ㆍ방법 및 결과 방사선작업종사자 등 시설내부에서 근무하는 인원의 예상피폭선량을 평가하고, 시설외부에 방사선영향을 미치는 경우에는 일반인의 예상피폭선량으로 안전성을 평가하여 기술한다.

8.  주변 환경에 대한 방사선 영향 직접 방사선에 의한 영향 및 방사능방출에 따른 영향과 그로 인한 환경 영향을 기술한다.

9.  사고의 위험 및 그 대책 예상되는 사고의 내용, 발생 가능성, 영향을 평가하고 이에 따른 대책을 기술한다.

10. 방사성폐기물의 발생 및 처리계획 방사성폐기물을 발생원별로 수량ㆍ특성 등을 평가하고 관리 및 처리ㆍ처분방법에 대하여 기술한다.

11. 종합 결론 안전관리 확보를 위한 제반조치의 타당성을 기술한다.

12. 보고서 작성자의 인적사항 및 자격 보고서 작성자의 인적사항 및 보유하고 있는 자격ㆍ경력 및 학력을 기술한다.

13. 참고문헌 보고서 작성에 이용된 참고자료를 기재한다.
:::

### \[별표\] 방사성동위원소등 취급에 관한 방사선안전보고서 세부 작성지침(제5조 관련)

-   [방사성동위원소등 취급에 관한 방사선안전보고서 세부 작성지침](/archive/%5B별표%5D%20방사성동위원소등%20취급에%20관한%20방사선안전보고서%20세부%20작성지침(제5조%20관련)(방사선안전보고서%20작성지침).pdf)
