---
title: "원자력안전법 시행규칙"
description: |
  [시행 2024. 12. 24.] [총리령 제2000호, 2024. 12. 24., 타법개정]<br><br>
  <div style="text-align: right;">
  원자력안전위원회(안전정책과), 02-397-7264<br>  
  원자력안전위원회(안전기준과), 02-397-7315<br>  
  원자력안전위원회(생활방사선안전과), 02-397-7334<br>
  원자력안전위원회(방사선안전과), 02-397-7273</div>
date: "2024-12-24"
date-modified: "2024-12-24"
categories: [시행규칙]
---

# 제5장 방사성동위원소등, 방사성폐기물 및 방사성물질의 관리

### 제58조(방사성동위원소등의 생산허가 신청 등) {#제58조}

::: {.callout-note title="제58조(방사성동위원소등의 생산허가 신청 등)" collapse="open" appearance="minimal"}
① 영 제79조제1항, 제2항 및 제3항에 따른 방사성동위원소 또는 방사선발생장치(이하 “방사성동위원소등”이라 한다)의 생산허가신청은 별지 제41호서식 또는 별지 제42호서식의 신청서에 따른다. \<개정 2019. 12. 3.\>

② 법 제53조제3항에 따라 제1항의 신청서에는 다음 각 호의 서류를 첨부하여야 한다. \<개정 2014. 11. 24.\>

1.  안전성분석보고서

2.  품질보증계획서

3.  방사선안전보고서

4.  안전관리규정

5.  영 별표 2에 따른 장비의 구입을 증명하는 서류

6.  영 별표 3에 따른 인력의 재직을 입증하는 서류

7.  영 제152조제1호에 따른 보상기준

③ 제2항제1호에 따른 안전성분석보고서에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다.

1.  방사성동위원소등의 개요 및 제원

2.  방사성동위원소등의 재질ㆍ구조 및 안전성평가

3.  방사성동위원소등의 성능시험계획서

④ 제2항제3호에 따른 방사선안전보고서에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다. 다만, 허가대상과 관련이 없는 사항은 기재하지 아니할 수 있다.

1.  시설 개요

2.  시설주변의 환경

3.  운영계획 개요

4.  방사선원의 특성ㆍ위치 및 제원

5.  안전시설 개요

6.  방사선취급방법 및 방사선안전관리계획

7.  예상피폭선량의 평가에 관한 절차ㆍ방법 및 결과

8.  주변환경에 대한 방사선 영향

9.  사고의 위험 및 그 대책

10. 방사성폐기물의 발생 및 처리계획

11. 방사선안전보고서의 작성자의 인적사항 및 자격

⑤ 제2항제4호에 따른 안전관리규정에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다. 다만, 허가대상과 관련이 없는 사항은 적지 아니할 수 있다. \<개정 2016. 8. 8.\>

1.  방사성동위원소등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항

2.  방사성동위원소등의 구매ㆍ사용 및 판매에 관한 사항

3.  방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항

4.  방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질(이하 “방사성물질등”이라 한다)에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항

5.  방사선안전관리 장비의 보관ㆍ관리 및 교정에 관한 사항

6.  방사선작업종사자 및 수시출입자에 대한 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항

7.  방사선작업종사자 및 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항

8.  방사선장해 발생 여부를 발견하기 위하여 필요한 조치에 관한 사항

9.  방사선장해를 받았거나 받을 우려가 있는 사람에 대하여 필요한 보건상 조치에 관한 사항

10. 법 제58조에 따른 기록과 그 비치에 관한 사항

11. 위험 시 조치에 관한 사항

12. 방사성동위원소등의 분실ㆍ도난 등 사고 시의 조치 및 사고예방에 관한 사항

13. 방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항

14. 그 밖에 방사선장해의 방어에 필요한 사항

⑥ 영 제79조에 따른 신청서를 제출받은 위원회는 「전자정부법」 제36조제1항에 따른 행정정보의 공동이용을 통하여 신청인의 사업자등록증을 확인하여야 한다. 다만, 신청인이 확인에 동의하지 아니하는 경우에는 사업자등록증 사본을 첨부하도록 하여야 한다.

⑦ 위원회는 법 제53조제1항 본문에 따른 방사성동위원소등의 생산허가를 하였을 때에는 별지 제43호서식 또는 별지 제44호서식의 허가증을 신청인에게 발급하여야 한다. 이 경우 생산허가의 대상이 특수형방사성물질인 경우에는 별지 제45호서식의 특수형방사성물질설계승인서를 함께 발급하여야 한다.
:::

### 제63조 경미한 사항의 변경신고

::: {.callout-note title="제63조(경미한 사항의 변경신고)" collapse="open" appearance="minimal"}
① 법 제53조제1항 단서에서 “총리령으로 정하는 일시적인 사용장소의 변경과 그 밖의 경미한 사항을 변경하려는 때”란 다음 각 호의 어느 하나에 해당하는 경우를 말한다. \<개정 2013. 8. 16., 2024. 4. 25.\>

1.  다음 각 목의 어느 하나에 해당하는 일시적인 사용장소의 변경

가. 방사성동위원소등을 사업소 외에서 검정 또는 교정을 목적으로 사용하기 위하여 그 사용장소를 변경하는 것

나. 방사성동위원소등을 사업소 외에서 방사선투과검사를 목적으로 이동사용하기 위하여 작업장(방사성동위원소등을 사용하는 장소를 말한다. 이하 같다)을 개설하는 것

다. 방사선발생장치 또는 방사성동위원소가 내장된 기기(이하 “방사선기기”라 한다)를 사업소 외에서 검문ㆍ검색 또는 보안을 목적으로 사용하기 위하여 그 사용장소를 변경하는 것

라. 방사선기기를 사업소 외에서 제품의 홍보를 목적으로 진열ㆍ전시ㆍ시연하기 위하여 그 사용장소를 변경하는 것

2.  다음 각 목의 어느 하나에 해당하는 사항의 변경

가. 사용시설등의 변경을 요하지 아니하는 방사성동위원소등의 종류 또는 수량의 감소에 관한 사항

나. 허가를 받은 사람(이하 “허가사용자”라 한다)의 성명 및 주소(법인인 경우에는 명칭 및 주소와 그 대표자의 성명)

다. 삭제 \<2014. 11. 24.\>

라. 허가사용자가 제65조에 따른 사용신고대상 방사성동위원소 또는 제66조에 따른 사용신고대상 방사선발생장치를 추가 또는 변경하는 것에 관한 사항

마. 안전관리규정의 변경에 관한 사항

② 법 제53조제1항 단서에 따라 제1항제2호의 사항에 대한 변경신고를 하려는 자는 변경 후 30일 이내에 별지 제4호서식의 신고서를 위원회에 제출하여야 한다. 다만, 제1항제2호라목의 사항에 대한 변경신고는 변경 전에 제출하여야 한다.

③ 제2항의 신고서에는 다음 각 호의 서류를 첨부하여야 한다.

1.  변경사항에 관한 서류

2.  허가증
:::

# 제6장 방사성폐기물의 관리ㆍ운영

### 제89조(경미한 사항의 변경신고)

::: {.callout-note title="제89조(경미한 사항의 변경신고)" collapse="open" appearance="minimal"}
① 법 제63조제1항 단서에서 “총리령으로 정하는 경미한 사항”이란 다음 각 호의 어느 하나에 해당하는 사항을 말한다. \<개정 2015. 7. 21., 2016. 8. 8.\>

1.  허가를 받은 사람의 성명 및 주소(법인인 경우에는 그 명칭ㆍ주소 및 그 대표자의 성명)

2.  방사성폐기물관리시설등을 설치하는 사업소의 명칭

3.  방사성폐기물관리시설등의 공사일정

4.  제87조제3항에 따른 안전성분석보고서의 기재사항 중 같은 항 제1호ㆍ제4호 또는 제7호에 관한 사항

5.  제87조제5항에 따른 건설 및 운영에 관한 품질보증계획서의 기재사항 중 제4조제4항제2호부터 제18호까지에 관한 사항

6.  안전성분석보고서, 안전관리규정, 건설 및 운영에 관한 품질보증계획서, 방사성폐기물관리시설등의 건설ㆍ운영계획에 관한 서류 및 방사성폐기물관리시설등의 건설ㆍ운영에 관한 기술능력에 관한 설명서의 내용 중 품질보증체제의 조직이 아닌 일반조직 변경에 관한 사항

7.  오기(誤記), 누락 또는 그 밖에 이에 준하는 사유로서 그 변경 근거가 분명한 사항

② 법 제63조제1항 단서에 따라 변경신고를 하려는 자는 변경 후 20일 이내에 별지 제4호서식의 신고서에 다음 각 호의 서류를 첨부하여 위원회에 제출하여야 한다. \<개정 2016. 8. 8.\>

1.  변경사항을 증명하는 서류

2.  허가증
:::

### 제95조 자체처분계획서 및 사전검토 신청서 등

::: {.callout-note title="제95조(자체처분계획서 및 사전검토 신청서 등)" collapse="open" appearance="minimal"}
① 영 제107조제2항에 따른 자체처분계획서는 별지 제84호서식과 같다.

② 제1항의 계획서에는 위원회가 정하여 고시하는 지침에 따라 작성된 다음 각 호의 사항에 관한 서류를 첨부하여야 한다. \<개정 2023. 8. 1.\>

1.  자체처분 대상 방사성폐기물의 종류 및 수량

2.  자체처분 대상 방사성폐기물의 발생원과 발생일시 또는 발생기간

3.  자체처분 대상 방사성폐기물의 종류별 표면방사선량률과 핵종별 농도 및 그 산출근거

4.  자체처분 방법 및 예정 목적지

5.  자체처분으로 인하여 부수적으로 발생하는 폐기물의 수량 및 관리방법

6.  자체처분에 따른 예상 피폭방사선량이 위원회가 정하여 고시하는 자체처분 허용선량을 만족함을 입증하는 자료

7.  자체처분절차

③ 영 제107조제7항에 따른 사전검토 신청서는 별지 제84호의2서식과 같다. \<신설 2023. 8. 1.\>

④ 제3항의 사전검토 신청서에는 위원회가 정하여 고시하는 지침에 따라 작성된 다음 각 호의 사항에 관한 서류를 첨부해야 한다. \<신설 2023. 8. 1.\>

1.  자체처분 대상 방사성폐기물의 종류 및 수량

2.  자체처분 대상 방사성폐기물의 발생원과 발생일시 또는 발생기간

3.  자체처분 대상 방사성폐기물의 핵종별 농도 측정 및 평가 방법

⑤ 한국원자력안전기술원은 영 제107조제2항 또는 제3항에 따라 자체처분계획서를 제출받은 날부터 20일 이내에, 영 제107조제7항에 따라 사전검토를 신청받은 날부터 30일 이내에 그 검토 결과를 원자력관계사업자에게 통지해야 한다. \<신설 2023. 8. 1.\>

\[제목개정 2023. 8. 1.\]
:::

# 제10장 규제ㆍ감독 등

### 제120조 즉정장소 및 측정대상

::: {.callout-note title="제120조(측정장소 및 측정대상)" collapse="open" appearance="minimal"}
① 영 제131조제1항에서 “총리령으로 정하는 방사선장해우려가 있는 장소”란 다음 각 호의 장소를 말한다. \<개정 2014. 11. 24.\>

1.  방사선량의 경우

가. 사용ㆍ분배ㆍ저장 및 폐기시설

나. 고정된 방사선차폐시설 안에 있는 밀봉된 방사성동위원소 또는 방사선발생장치

다. 방사성폐기물의 저장ㆍ처리 및 처분시설

라. 방사선관리구역

마. 비정상적으로 방사성물질이 누출된 장소

2.  방사성물질등에 따른 오염상황의 경우

가. 방사선관리구역에 있어서 공기 중의 방사성물질농도와 오염되거나 오염의 우려가 있는 물체의 표면

나. 방사선관리구역으로부터 반출하는 물품의 표면

다. 배기구 또는 배수구

라. 비정상적으로 방사성물질이 누출된 장소

② 영 제131조제2항에 따른 피폭방사선량 및 방사성물질등에 따른 오염상황의 측정대상은 다음 각 호와 같다. \<개정 2014. 11. 24.\>

1.  피폭방사선량의 경우

가. 방사선작업종사자

나. 수시출입자

다. 방사선관리시설에 일시적으로 출입하는 자로서 선량한도를 초과하여 피폭될 우려가 있는 자

2.  방사성물질에 따른 오염상황의 경우

가. 방사선작업종사자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는 부위의 표면

나. 수시출입자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는 부위의 표면

③ 제1항 및 제2항에 따른 측정장소 및 측정대상에 대한 측정방법은 다음 각 호와 같다.

1.  방사선량 및 오염상황은 방사선측정에 가장 적합한 장소에서 측정할 것

2.  방사선에 따른 인체내부의 피폭은 공기 중 또는 음료수 중의 방사성물질의 농도 및 양을 측정하거나 필요한 정밀검사를 통하여 산출할 것
:::

### 제121조 건강진단

::: {.callout-note title="제121조(건강진단)" collapse="open" appearance="minimal"}
① 영 제132조제1항에 따라 실시하는 건강진단에서는 다음 각 호의 사항을 검사해야 한다. \<개정 2013. 8. 16., 2021. 10. 20.\>

1.  직업력 및 노출력

2.  방사선 취급과 관련된 병력

3.  임상검사 및 진찰

가. 임상검사: 말초혈액 중의 백혈구 수, 혈소판 수 및 혈색소의 양

나. 진찰: 눈, 피부, 신경계 및 조혈계(혈구형성계통) 등의 증상

4.  말초혈액도말검사와 세극등현미경검사(제1호부터 제3호까지의 규정에 따른 검사 결과 건강수준의 평가가 곤란하거나 질병이 의심되는 경우에만 해당한다)

② 영 제132조제1항에 따른 건강진단의 실시시기는 다음 각 호와 같다. \<개정 2013. 8. 16., 2016. 8. 8.\>

1.  방사선작업종사자 및 수시출입자가 최초로 해당 업무에 종사하기 전

2.  해당 업무에 종사 중인 방사선작업종사자 및 수시출입자에 대하여는 매년. 다만, 전년도 건강진단을 실시한 때부터 12개월간의 피폭방사선량이 영 별표 1 제3호에 따른 선량한도를 초과하지 아니하는 경우에는 그 해의 제1항제1호 및 제2호에 대한 검사를 생략할 수 있다.

3.  방사선작업종사자 및 수시출입자의 피폭방사선량이 영 별표 1에 따른 선량한도를 초과한 때

③ 제2항에도 불구하고 「산업안전보건법」 제130조제2항 본문에 따라 방사선 유해인자에 대한 배치전건강진단을 받은 경우에는 제2항제1호의 시기에 실시하는 건강진단을 받은 것으로 보고, 같은 조 제2항 각 호 외의 부분 본문에 따라 방사선 유해인자에 대한 특수건강진단을 받은 경우에는 제2항제2호의 시기에 실시하는 건강진단을 받은 것으로 본다. \<신설 2018. 5. 3., 2023. 3. 9.\>
:::

### 제122조(피폭방사선량 평가 및 관리)

::: {.callout-note title="제122조(피폭방사선량 평가 및 관리)" collapse="open" appearance="minimal"}
원자력관계사업자는 영 제133조제1항에 따라 방사선작업종사자 및 수시출입자에 대하여 다음 각 호에 따라 피폭방사선량을 평가하고 관리해야 한다. \<개정 2016. 8. 8., 2021. 3. 4.\>

1.  방사선작업종사자가 방사선관리구역에 출입하는 때에는 위원회가 정하여 고시하는 개인선량계를 착용하도록 할 것

2.  수시출입자가 방사선관리구역에 출입하는 때에는 위원회가 정하여 고시하는 개인선량계를 착용하도록 할 것

3.  제1호 및 제2호에 따른 개인선량계 중 판독이 필요한 개인선량계는 위원회가 정하여 고시하는 기간마다 교체하여 판독하도록 할 것

3의2. 방사선작업종사자가 제3호에 따른 기간 내에 「진단용 방사선발생장치의 안전관리에 관한 규칙」 제4조제5항 또는 「동물 진단용 방사선 발생장치의 안전관리에 관한 규칙」 제4조제6항에 따른 방사선 피폭선량 측정을 받은 경우에는 그 측정 내용을 포함하여 제3호에 따른 판독을 하도록 할 것

4.  제3호 및 제3호의2에 따른 개인선량계의 판독은 판독업무자가 수행하도록 할 것

5.  방사선작업종사자 또는 수시출입자 중 영 제2조제15호에 따른 판독특이자가 발생한 때에는 위원회가 정하여 고시하는 바에 따라 필요한 조치를 할 것
:::

### 제138조 방사선작업종사자 및 수시출입자 교육

::: {.callout-note title="제138조(방사선작업종사자 및 수시출입자 교육)" collapse="open" appearance="minimal"}
① 영 제148조제1항에 따른 신규교육과 정기교육은 각각 다음 각 호의 구분에 따른 사항을 포함하여 실시한다. 이 경우 교육대상자의 방사선안전 지식수준과 경험 등을 고려하여 교육의 내용과 방법을 다르게 할 수 있다. \<개정 2014. 11. 24., 2016. 8. 8.\>

1.  기본교육

가. 원자력시설 이용에 따른 안전관리

나. 방사성물질등의 취급

다. 방사선장해방어

라. 방사선안전 관계법령

마. 그 밖에 이용업체의 특성에 따른 교육

2.  직장교육

가. 이용업체의 방사선안전관리규정

나. 이용업체의 방사선원 및 방사선장비의 특성

다. 그 밖에 이용업체의 특성에 따른 교육

② 영 제148조제2항 및 제3항에 따른 기본교육은 방사선안전관리자, 방사선안전관리자 이외의 방사선작업종사자 및 수시출입자 교육으로 구분하여 실시하여야 한다. \<개정 2016. 8. 8.\>

③ 삭제 \<2016. 6. 30.\>

④ 영 제148조제1항에 따른 교육을 받은 사람에 대해서는 평가를 실시할 수 있다. \<개정 2014. 11. 24.\>

⑤ 영 제148조제4항에 따른 직장교육계획에는 다음 각 호의 사항이 포함되어야 한다.

1.  자체교육의 경우

가. 교육일정

나. 교육대상별 교재

다. 강사에 관한 사항

라. 교육시설에 관한 사항

마. 평가에 관한 사항

2.  위탁교육의 경우: 위탁의 내용 및 수탁기관

⑥ 영 제148조제1항부터 제3항까지의 규정에 따른 교육의 과정 및 시간은 별표 5의2와 같다. \<신설 2016. 8. 8.\>

\[전문개정 2013. 8. 16.\] \[제목개정 2016. 8. 8.\]
:::

# 제12장 보칙

### 제145조 기록과 비치

::: {.callout-note title="제145조 (기록과 비치)" collapse="open" appearance="minimal"}
법 제18조 · 제25조 · 제39조 · 제49조 · 제52조제4항 · 제58조 · 제67조 · 제82조, 영 제131조제3항 및 제132조제2항에 따라 기록 · 비치하여야 할 사항은 별표 7과 같다. 다만, 기록하여야 할 사항 중 측정이 필요한 경우로서 직접 측정하기가 곤란한 때에는 해당 사항을 간접적으로 추정하여 그 내용을 기록하되, 추정치임을 부기하여야 한다.
:::

### \[별표5의2\] 교육의 과정 및 시간(제138조제6항 관련)

-   [교육의 과정 및 시간](/archive/%5B별표%205의2%5D%20교육의%20과정%20및%20시간(제138조제6항%20관련)(원자력안전법%20시행규칙).pdf)

### \[별표7\] 기록비치하여야 할 사항(제145조 관련)

-   [기록비치하여야 할 사항](/archive/%5B별표%207%5D%20기록ㆍ비치하여야%20할%20사항(제145조%20관련)(원자력안전법%20시행규칙).pdf)

### \[별지 제84호서식\] 방사성폐기물 자체처분계획서

-   [방사성폐기물 자체처분계획서](/archive/%5B별지%20제84호서식%5D%20방사성폐기물%20자체처분계획서(원자력안전법%20시행규칙).pdf)
