---
title: "교육훈련"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 교육훈련]
---

교육훈련과 관련된 법령규칙고시은 아래와 같습니다.

## 원자력안전법

### 제106조 교육훈련

::: {.callout-note title="제106조(교육훈련)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 방사선작업종사자와 방사선 관리 구역에 출입하는 사람에게 대통령령으로 정하는 바에 따라 원자력이용에 따르는 안전성 확보 및 방사선장해방지에 필요한 교육 및 훈련을 실시하여야 한다.

② 제84조에 따라 면허를 받은 사람은 대통령령으로 정하는 바에 따라 위원회가 실시하는 보수교육을 받아야 한다.

③ 원자력관계사업자와 원자력관련 연구를 수행하는 기관은 대통령령으로 정하는 사람에게 총리령으로 정하는 바에 따라 위원회가 실시하는 원자력통제에 관한 교육을 받게 하여야 한다. \<개정 2017. 12. 19.\>
:::

### 제106조 교육훈련 \[시행일: 2025.4.23.\]

::: {.callout-note title="제106조(교육훈련)" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
[① 원자력관계사업자는 다음 각 호의 구분에 따른 사람에게 대통령령으로 정하는 바에 따라 원자력이용에 따르는 안전성 확보와 방사선장해방지에 필요한 교육 및 훈련을 실시하여야 한다.]{style="color:red;"} \<개정 2024. 10. 22.\>

[1. 원자력관계사업자(신고사용자는 제외한다)의 경우: 방사선작업종사자 및 방사선관리구역에 출입하는 사람]{style="color:red;"}

[2. 신고사용자의 경우: 방사선안전관리자]{style="color:red;"}

② 제84조에 따라 면허를 받은 사람은 대통령령으로 정하는 바에 따라 위원회가 실시하는 보수교육을 받아야 한다.

③ 원자력관계사업자와 원자력관련 연구를 수행하는 기관은 대통령령으로 정하는 사람에게 총리령으로 정하는 바에 따라 위원회가 실시하는 원자력통제에 관한 교육을 받게 하여야 한다. \<개정 2017. 12. 19.\>

\[시행일: 2025. 4. 23.\] 제106조
:::

## 원자력안전법 시행령

### 제148조 방사선작업종사자 및 수시출입자 교육

::: {.callout-note title="제148조(방사선작업종사자 및 수시출입자 교육)" collapse="open" appearance="minimal"}
① 원자력관계사업자는 법 제106조제1항에 따라 방사선작업종사자에 대해서는 신규교육과 정기교육을 실시하여야 한다. 이 경우 신규교육은 작업 종사 전에 실시하여야 한다.

② 제1항에 따른 교육은 기본교육과 직장교육으로 구분하여 실시한다. 이 경우 직장교육은 방사선안전관리자 외의 방사선작업종사자를 대상으로 한다. \<개정 2014. 11. 19.\>

③ 원자력관계사업자는 수시출입자에 대하여 기본교육 또는 직장교육을 실시할 수 있다. \<신설 2016. 4. 12.\>

④ 제2항 및 제3항에 따른 기본교육은 안전재단에서 받도록 하여야 하며, 직장교육은 해당 원자력관계사업자가 자체적으로 실시하되 위원회가 지정하여 고시하는 기관에 위탁하여 실시할 수 있다. \<개정 2014. 11. 19., 2016. 4. 12., 2016. 6. 21.\>

⑤ 제1항부터 제3항까지의 규정에 따른 교육의 과정 및 시간 등은 총리령으로 정한다. \<개정 2016. 4. 12.\>

⑥ 제149조제1항에 따른 보수교육을 받은 자는 제1항에 따른 해당 연도의 정기교육을 받은 것으로 본다. \<신설 2014. 11. 19., 2016. 4. 12.\>

\[전문개정 2013. 8. 16.\] \[제목개정 2016. 4. 12.\]
:::

## 원자력안전법 시행규칙

### 제138조 방사선작업종사자 및 수시출입자 교육

::: {.callout-note title="제138조(방사선작업종사자 및 수시출입자 교육)" collapse="open" appearance="minimal"}
① 영 제148조제1항에 따른 신규교육과 정기교육은 각각 다음 각 호의 구분에 따른 사항을 포함하여 실시한다. 이 경우 교육대상자의 방사선안전 지식수준과 경험 등을 고려하여 교육의 내용과 방법을 다르게 할 수 있다. <개정 2014. 11. 24., 2016. 8. 8.>

1. 기본교육

가. 원자력시설 이용에 따른 안전관리

나. 방사성물질등의 취급

다. 방사선장해방어

라. 방사선안전 관계법령

마. 그 밖에 이용업체의 특성에 따른 교육

2. 직장교육

가. 이용업체의 방사선안전관리규정

나. 이용업체의 방사선원 및 방사선장비의 특성

다. 그 밖에 이용업체의 특성에 따른 교육

② 영 제148조제2항 및 제3항에 따른 기본교육은 방사선안전관리자, 방사선안전관리자 이외의 방사선작업종사자 및 수시출입자 교육으로 구분하여 실시하여야 한다. <개정 2016. 8. 8.>

③ 삭제 <2016. 6. 30.>

④ 영 제148조제1항에 따른 교육을 받은 사람에 대해서는 평가를 실시할 수 있다. <개정 2014. 11. 24.>

⑤ 영 제148조제4항에 따른 직장교육계획에는 다음 각 호의 사항이 포함되어야 한다.

1. 자체교육의 경우

가. 교육일정

나. 교육대상별 교재

다. 강사에 관한 사항

라. 교육시설에 관한 사항

마. 평가에 관한 사항

2. 위탁교육의 경우: 위탁의 내용 및 수탁기관

⑥ 영 제148조제1항부터 제3항까지의 규정에 따른 교육의 과정 및 시간은 별표 5의2와 같다. <신설 2016. 8. 8.>

[전문개정 2013. 8. 16.]
[제목개정 2016. 8. 8.]
:::

### [별표5의2] 교육의 과정 및 시간(제138조제6항 관련)

-   [교육의 과정 및 시간](/archive/[별표 5의2] 교육의 과정 및 시간(제138조제6항 관련)(원자력안전법 시행규칙).pdf)
