---
title: "안전관리자업무"
description: "원자력안전 및 하위법에 따른 안전관리자의 업무에 대한 기술이 있습니다"
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-11-27"
date-modified: "2025-05-26"
categories: [방사선안전관리자, 업무]
---

-   이 페이지에서는 법령규칙고시에 근거한 방사선안전관리자의 업무를 정리하였습니다. 먼저 가장 상위법인 원자력안전법에 따른 방사선안전관리자의 업무를 정리하였습니다.

### 원자력안전법상 방사선안전관리자의 업무

원자력안전법\[시행 2025. 4. 23.\] \[법률 제20533호, 2024. 10. 22., 일부개정\] 제53조의3(방사선안전관리자)에 의하면 방사선안전관리자는 아래의 업무를 수행해야 합니다.

1.  `원자력안전법 제53조제3항의 안전관리규정 및 제59조제1항의 기술기준의 준수여부 점검`

2.  `방사선작업종사자 및 방사선관리구역 출입자에 대한 제91조에 따른 방사선장해방지조치`

3.  `허가사용자 및 신고사용자에 대한 방사선 안전관리에 관한 조치 권고`

4.  `그 밖에 방사선 안전관리를 위하여 필요한 조치`

-   상위법 답게 선언적인 내용이 주를 이루고 있습니다. 가장먼저 기술된 안전관리규정에 포함되는 사항들을 알아보기 위해 원자력안전법 시행규칙상 안전관리규정에 포함되어야할 사항들을 정리했습니다.

### 원자력안전법 시행규칙상 안전관리규정에 포함되어야할 사항들

원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령 제2000호, 2024. 12. 24., 타법개정\] 제58조(방사성동위원소등의 생산허가 신청 등)제5항에는 `안전관리규정에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다.`라고 규정하고 있습니다. 각 호의 사항은 아래와 같습니다.

1.  `방사성동위원소등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항`

2.  `방사성동위원소등의 구매ㆍ사용 및 판매에 관한 사항`

3.  `방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항`

4.  `방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질(이하 “방사성물질등”이라 한다)에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항`

5.  `방사선안전관리 장비의 보관ㆍ관리 및 교정에 관한 사항`

6.  `방사선작업종사자 및 수시출입자에 대한 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항`

7.  `방사선작업종사자 및 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항`

8.  `방사선장해 발생 여부를 발견하기 위하여 필요한 조치에 관한 사항`

9.  `방사선장해를 받았거나 받을 우려가 있는 사람에 대하여 필요한 보건상 조치에 관한 사항`

10. `법 제58조에 따른 기록과 그 비치에 관한 사항`

11. `위험 시 조치에 관한 사항`

12. `방사성동위원소등의 분실ㆍ도난 등 사고 시의 조치 및 사고예방에 관한 사항`

13. `방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항`

14. `그 밖에 방사선장해의 방어에 필요한 사항`

-   원자력안전법 시행규칙 제58조에서 언급한 위원회가 고시한 작성지침이라함은 원자력안전위원회 고시로써 안전관리규정 작성지침\[시행 2024. 12. 31.\] \[원자력안전위원회고시 제2024-13호, 2024. 12. 31., 타법개정\]입니다. 이 지침의 제3조(일반지침)에서는 작성에 대한 다음의 각호와 같은 일반지침을 규정하고 있습니다.

### 

### 하위법ㆍ지침상의 업무

안전관리규정 세부작성지침에 따르면 안전법보다는 세분화된 업무가 기술되어 있으며, 안전법과 함께 고려해서 저자가 분류해 보면 아래와 같습니다.

1.  안전관리규정 제ㆍ개정

2.  방사선안전보고서 제ㆍ개정

3.  방사선원 구매ㆍ사용ㆍ 판매에 관한 사항

4.  방사선원 및 오염물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항

5.  방사선관리구역의 외부방출선량률, 물체표면 오염도, 퇴실자 및 물품의 오염도, 비밀봉RI 사용시 오염상황측정

6.  방사선안전관리장비의 보관ㆍ관리 및 교정

7.  방사선작업종사자 및 수시출입자의 피폭방사선량평가 및 개인선량계 관리

8.  방사선작업종사자 및 수시출입자의 교육훈련

9.  방사선작업종사자 및 수시출입자의 건강진단

10. 방사선원의 분실ㆍ도난 등 사고시의 조치 및 사고예방 조치 - 방사선장해발생자 또는 우려자에 대한 보건상 조치

11. 허가사용자 및 신고사용자에 대한 방사선 안전관리에 관한 조치 권고

12. 그 밖의 방사선안전관리를 위하여 필요한 조치
