---
title: "방사선장해방지조치"
description: "방사선장해방지조치를 대한 내용을 정리하였습니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-11-27"
date-modified: last-modified
categories: [방사선안전관리자, 업무, 안전관리규정]
editor: 
  markdown: 
    wrap: 72
---

### 원자력안전법상 방사선장해방지조치

-   원자력안전법시행 2025. 4. 23.\] \[법률 제20533호, 2024. 10. 22.,
    일부개정\]제91조(방사선장해방지조치)에 조치사항이 기술되어 있습니다.

###### 제91조(방사선장해방지조치)

① 원자력관계사업자(신고사용자는 제외한다)는 방사선장해를 방지하기 위하여
대통령령으로 정하는 바에 따라 다음 각 호의 조치를 하여야 한다. \<개정
2024. 10. 22.\>

1.  방사선량 및 방사성오염의 측정

2.  건강진단

3.  피폭관리

4.  삭제 \<2024. 10. 22.\>

② 원자력관계사업자는 대통령령으로 정하는 바에 따라 방사성물질의 방출량
및 피폭방사선량을 가능한 한 합리적으로 낮게 유지하기 위하여 필요한
조치를 하여야 한다. \<신설 2024. 10. 22.\>

③ 원자력관계사업자는 방사선작업종사자 및 대통령령으로 정하는
수시출입자의 피폭방사선량이 대통령령으로 정하는 선량한도를 초과하지
아니하도록 필요한 조치를 하여야 한다. \<개정 2024. 10. 22.\>

④ 원자력관계사업자는 방사선장해를 받은 사람 또는 방사선장해를 받은
것으로 보이는 사람에게 원자력이용시설에의 출입제한과 그 밖의 보건상
필요한 조치를 하여야 한다. \<개정 2024. 10. 22.\>

#### 대통령령으로 정하는 바

-   원자력안전법 시행령\[시행 2025. 4. 23.\] \[대통령령
    제35473호, 2025. 4. 22., 일부개정\]에서는 방사선량 및 방사성물질에
    의한 오염상황 측정과, 건강진단, 피폭관리에 대한 규정이 있습니다.

###### 제131조(측정)

① 원자력관계사업자(신고사용자는 제외한다. 이하 이 조, 제132조,
제133조제1항 및 제148조의3에서 같다)는 법 제91조제1항제1호에 따라
총리령으로 정하는 방사선장해의 우려가 있는 장소에 대한 방사선량 및
방사성물질등에 의한 오염상황을 측정하여야 한다. \<개정 2013. 3. 23.,
2013. 8. 16., 2017. 3. 20., 2025. 4. 22.\>

② 법 제91조제1항제1호에 따라 원자력관계사업자는 총리령으로 정하는 바에
따라 원자력이용시설에 출입하는 사람의 피폭방사선량 및 방사성물질에 의한
오염상황을 측정하여야 한다. \<개정 2013. 3. 23., 2013. 8. 16.\>

③ 원자력관계사업자는 제1항 및 제2항의 측정 결과에 관하여 기록의 작성,
보존, 그 밖의 총리령으로 정하는 조치를 하여야 한다. \<개정 2013. 3.
23.\>

###### 제132조(건강진단)

① 법 제91조제1항제2호에 따라 원자력관계사업자는 총리령으로 정하는 바에
따라 원자력이용시설의 방사선작업종사자 및 수시출입자에 대하여 건강진단을
실시하여야 한다. \<개정 2013. 3. 23., 2013. 8. 16., 2016. 4. 12.\>

② 원자력관계사업자는 제1항의 건강진단의 결과에 관하여 기록의 작성ㆍ보존
그 밖에 총리령으로 정하는 조치를 하여야 한다. \<개정 2013. 3. 23.\>

###### 제133조(피폭관리)

① 원자력관계사업자는 법 제91조제1항제3호에 따라 방사선작업종사자 및
수시출입자의 개인피폭선량이 선량한도를 초과하지 아니하도록 총리령으로
정하는 바에 따라 피폭선량 평가 및 피폭관리를 하여야 한다. \<개정 2013.
3. 23., 2025. 4. 22.\>

② 원자력관계사업자는 법 제91조제2항에 따라 원자력이용시설의 정상운전 및
비정상상태(사고의 경우는 제외한다)에서 원자력이용시설에 종사하는
방사선작업종사자 및 수시출입자와 시설 주변 주민의 방사선피폭을
최소화하기 위하여 위원회가 정하는 바에 따라 다음 각 호의 조치를 하여야
한다. \<신설 2025. 4. 22.\>

1.  방사선 작업 특성에 부합하는 방호조치

2.  방사선차폐 및 시설의 적절한 배치

3.  선량 저감에 효과적인 재료 및 기기의 사용

4.  적절한 작업공간의 확보

③ 법 제91조제3항에서 “대통령령으로 정하는 수시출입자”란 제2조제8호에
따른 수시출입자를, “대통령령으로 정하는 선량한도”란 제2조제4호에 따른
선량한도를 각각 말한다. \<개정 2025. 4. 22.\>

#### 총리령으로 정하는 측정장소와 측정대상

-   원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령
    제2000호, 2024. 12. 24., 타법개정\]에 있습니다.

###### 제120조(측정장소 및 측정대상)

① 영 제131조제1항에서 “총리령으로 정하는 방사선장해우려가 있는 장소”란
다음 각 호의 장소를 말한다. \<개정 2014. 11. 24.\>

1.  방사선량의 경우

가. 사용ㆍ분배ㆍ저장 및 폐기시설

나. 고정된 방사선차폐시설 안에 있는 밀봉된 방사성동위원소 또는
방사선발생장치

다. 방사성폐기물의 저장ㆍ처리 및 처분시설

라. 방사선관리구역

마. 비정상적으로 방사성물질이 누출된 장소

2.  방사성물질등에 따른 오염상황의 경우

가. 방사선관리구역에 있어서 공기 중의 방사성물질농도와 오염되거나 오염의
우려가 있는 물체의 표면

나. 방사선관리구역으로부터 반출하는 물품의 표면

다. 배기구 또는 배수구

라. 비정상적으로 방사성물질이 누출된 장소

② 영 제131조제2항에 따른 피폭방사선량 및 방사성물질등에 따른 오염상황의
측정대상은 다음 각 호와 같다. \<개정 2014. 11. 24.\>

1.  피폭방사선량의 경우

가. 방사선작업종사자

나. 수시출입자

다. 방사선관리시설에 일시적으로 출입하는 자로서 선량한도를 초과하여
피폭될 우려가 있는 자

2.  방사성물질에 따른 오염상황의 경우

가. 방사선작업종사자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는
부위의 표면

나. 수시출입자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는
부위의 표면

③ 제1항 및 제2항에 따른 측정장소 및 측정대상에 대한 측정방법은 다음 각
호와 같다.

1.  방사선량 및 오염상황은 방사선측정에 가장 적합한 장소에서 측정할 것

2.  방사선에 따른 인체내부의 피폭은 공기 중 또는 음료수 중의
    방사성물질의 농도 및 양을 측정하거나 필요한 정밀검사를 통하여 산출할
    것

#### 총리령으로 정하는 기록의 작성과 보존

-   원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령
    제2000호, 2024. 12. 24., 타법개정\]에 있습니다.

###### 제145조(기록과 비치) 법 제18조ㆍ제25조ㆍ제39조ㆍ제49조ㆍ제52조제4항ㆍ제58조ㆍ제67조ㆍ제82조, 영 제131조제3항 및 제132조제2항에 따라 기록ㆍ비치하여야 할 사항은 별표 7과 같다. 다만, 기록하여야 할 사항 중 측정이 필요한 경우로서 직접 측정하기가 곤란한 때에는 해당 사항을 간접적으로 추정하여 그 내용을 기록하되, 추정치임을 부기하여야 한다.

###### 별표 7 중 의료부분 발췌

8.  방사성동위원소등의 생산 및 사용자(신고사용자는 제외한다)

| 기록사항 | 기록시기 | 보존기간 |
|----|----|----|
| 방사성동위원소의 생산 또는 사용기록 (생산·사용할 때마다: 장소, 방법, 목적, 종사자 명단, 총량 및 수량) | 생산 또는 사용할 때마다 | 5년 |
| 방사성동위원소 또는 방사성동위원소에 따른 보관·처리·저장 및 오염물의 보관·처리·저장 및 배출기록 (일 배출한 때마다: 시, 장소, 방법, 종사자, 성명, 종류 및 수량) | 일 배출할 때마다 | 5년 |
| 방사선안전관리의 기록 |  |  |
| 방사성동위원소의 생산, 사용, 분배, 저장, 폐기 시점의 방사선량 | 측정할 때마다 | 5년 |
| 민원방사성동위원소 또는 방사선발생장치 설치 시 방사선작업실에 입실한 최초의 방사선량 | 측정할 때마다 | 10년 |
| 폐기물 및 배수구에서의 방사성물질의 농도 | 폐기 및 배수할 때마다 | 10년 |
| 방사선작업종사자의 개인선량계 판독결과 | 월 1회 | 5년 |
| 방사선작업종사자의 교육훈련 실시 내용 | 연 1회 | 사용을 폐지할 때까지 |
| 방사선작업종사자에 대한 건강진단 결과 | 연 1회 | 5년 |
| 신규로 종사하게 된 방사선작업종사자에 대한 직무기초교육훈련 실시 내용 | 종사하게 된 때마다 | 사용을 폐지할 때까지 |
| 방사선작업종사자 중 업무의 종류가 바뀐 사람에 대한 직무기초교육훈련 실시 내용 | 종사하게 된 때마다 | 사용을 폐지할 때까지 |
| 방사선작업종사자 중 업무의 종류가 바뀐 사람에 대한 직무변경교육훈련 실시 내용 | 종사하게 된 때마다 | 사용을 폐지할 때까지 |
| 방사선작업종사자에 대한 수시교육훈련 실시 내용 | 수시교육 실시 시 | 5년 |
| 방사선사고 발생 시 조치결과, 사고종류 및 원인, 종사자 수, 방사선량, 작업분류 및 처리의견 | 사고 발생 시 | 5년 |

#### 총리령으로 정하는 건강진단

-   원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령
    제2000호, 2024. 12. 24., 타법개정\]에 있습니다.

###### 제121조(건강진단) ① 영 제132조제1항에 따라 실시하는 건강진단에서는 다음 각 호의 사항을 검사해야 한다. \<개정 2013. 8. 16., 2021. 10. 20.\>

1.  직업력 및 노출력

2.  방사선 취급과 관련된 병력

3.  임상검사 및 진찰

가. 임상검사: 말초혈액 중의 백혈구 수, 혈소판 수 및 혈색소의 양

나. 진찰: 눈, 피부, 신경계 및 조혈계(혈구형성계통) 등의 증상

4.  말초혈액도말검사와 세극등현미경검사(제1호부터 제3호까지의 규정에
    따른 검사 결과 건강수준의 평가가 곤란하거나 질병이 의심되는 경우에만
    해당한다)

② 영 제132조제1항에 따른 건강진단의 실시시기는 다음 각 호와 같다. \<개정
2013. 8. 16., 2016. 8. 8.\>

1.  방사선작업종사자 및 수시출입자가 최초로 해당 업무에 종사하기 전

2.  해당 업무에 종사 중인 방사선작업종사자 및 수시출입자에 대하여는
    매년. 다만, 전년도 건강진단을 실시한 때부터 12개월간의
    피폭방사선량이 영 별표 1 제3호에 따른 선량한도를 초과하지 아니하는
    경우에는 그 해의 제1항제1호 및 제2호에 대한 검사를 생략할 수 있다.

3.  방사선작업종사자 및 수시출입자의 피폭방사선량이 영 별표 1에 따른
    선량한도를 초과한 때

③ 제2항에도 불구하고 「산업안전보건법」 제130조제2항 본문에 따라 방사선
유해인자에 대한 배치전건강진단을 받은 경우에는 제2항제1호의 시기에
실시하는 건강진단을 받은 것으로 보고, 같은 조 제2항 각 호 외의 부분
본문에 따라 방사선 유해인자에 대한 특수건강진단을 받은 경우에는
제2항제2호의 시기에 실시하는 건강진단을 받은 것으로 본다. \<신설 2018.
5. 3., 2023. 3. 9.\>

#### 총리령으로 정하는 선량평가 및 피폭관리

-   원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령
    제2000호, 2024. 12. 24., 타법개정\]에 있습니다.

###### 제122조(피폭방사선량 평가 및 관리) 원자력관계사업자는 영 제133조제1항에 따라 방사선작업종사자 및 수시출입자에 대하여 다음 각 호에 따라 피폭방사선량을 평가하고 관리해야 한다. \<개정 2016. 8. 8., 2021. 3. 4.\>

1.  방사선작업종사자가 방사선관리구역에 출입하는 때에는 위원회가 정하여
    고시하는 개인선량계를 착용하도록 할 것

2.  수시출입자가 방사선관리구역에 출입하는 때에는 위원회가 정하여
    고시하는 개인선량계를 착용하도록 할 것

3.  제1호 및 제2호에 따른 개인선량계 중 판독이 필요한 개인선량계는
    위원회가 정하여 고시하는 기간마다 교체하여 판독하도록 할 것

3의2. 방사선작업종사자가 제3호에 따른 기간 내에 「진단용
방사선발생장치의 안전관리에 관한 규칙」 제4조제5항 또는 「동물 진단용
방사선 발생장치의 안전관리에 관한 규칙」 제4조제6항에 따른 방사선
피폭선량 측정을 받은 경우에는 그 측정 내용을 포함하여 제3호에 따른
판독을 하도록 할 것

4.  제3호 및 제3호의2에 따른 개인선량계의 판독은 판독업무자가 수행하도록
    할 것

5.  방사선작업종사자 또는 수시출입자 중 영 제2조제15호에 따른
    판독특이자가 발생한 때에는 위원회가 정하여 고시하는 바에 따라 필요한
    조치를 할 것
