---
title: "안전성분석보고서 관리"
description: "안전관리자의 업무로써 안전성분석보고서 작성에 대한 설명입니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2025-02-14"
date-modified: "2025-02-14"
categories: [방사선안전관리자, 업무, 안전성분석보고서]
---

### 방사선안전보고서 주요사항

-   <a href="../../law/nuclear_safety_enforcement_rule.qmd#제58조" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기">시행규칙 제58조(방사성동위원소등의 생산허가 신청 등) </a> 제4항에 따르면 아래의 각 사항들이 기술되어야 합니다.

::: {.callout-important title="규칙에 따라 안전성분석보고서에 적어야할 사항" collapse="open"}
1. 방사성동위원소등의 개요 및 제원

2. 방사성동위원소등의 재질ㆍ구조 및 안전성평가

3. 방사성동위원소등의 성능시험계획서
:::

### 안전성분석보고서 작성지침

-   <a href="../../law/sar_preperation_regulation.qmd#제4장" 
       target="_blank" 
       class="text-primary" 
       data-bs-toggle="tooltip" 
       data-bs-html="true" 
       data-bs-placement="bottom"
       title="새로운창으로 열기">방사성동위원소등의 생산에 관한 기준 \[시행 2017. 12. 26.] [원자력안전위원회고시 제2017-52호, 2017. 12. 26., 일부개정]제5장 </a> 에 기술된 작성에 관한 지침에 따라 작성하여야 합니다.

::: {.callout-important title="제5장 안정성분석보고서 작성" collapse="open"}
제27조(개요 및 제원) ① 방사성동위원소의 경우에는 다음 각 호에 관한 사항을 기재하여야 한다. 

1. 제품의 사용 용도에 대한 설명 

2. 밀봉 또는 개봉 여부 

3. 핵종 및 방사능량 

4. 물리적 및 화학적 상태 

5. 제품 생산 공정에 대한 설명 

② 방사선발생장치의 경우에는 다음 각 호에 관한 사항을 기재하여야 한다. 

1. 제품의 사용 용도에 대한 설명 

2. 방사선발생장치의 형식 및 성능 

3. 제품 생산 공정에 대한 설명 

 제28조(재질, 구조 및 안전성평가) ① 방사성동위원소등의 재질 및 구조에 대하여는 다음 각 호의 사항을 기재하여야 한다. 다만, 개봉선원의 경우는 이를 기재하지 않는다. 

1. 방사성동위원소등의 주요부품 종류별 재질 및 사양 

2. 방사성동위원소등의 생산제품별 조립도 

② 방사성동위원소등의 안전성 평가에 대하여는 다음 각 호의 사항을 기재한다. 

1. 안전기준(그 기준이 법적 규정인 경우에는 해당규정) 

2. 안전기준 요건에 적합함을 입증하는 평가내용 및 평가결과 

 제29조(성능시험계획서) ① 방사성동위원소등의 성능시험계획서에는 다음 각 호의 사항을 기재하여야 한다. 다만, 개봉선원의 경우는 이를 기재하지 않는다. 

1. 시험방법 

2. 시험 및 합격기준 

3. 시험물 사양 및 시험물 제작방법 

4. 시험시설 및 시험기기 

5. 시험결과 평가방법 

6. 시험일정 

② 방사성동위원소의 경우 제1항에 따른 성능시험계획서는 영 제91조에 따른 생산검사를 신청할 때에 생산검사신청서와 함께 제출할 수 있다. 
:::

