---
title: "안전관리규정 준수여부 점검"
description: "안전관리규정 준수여부의 점검을 위해 규정에 포함되어야 할 사항들과 작성지침에 대한 이해가 필요하여 정리하였습니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-11-27"
date-modified: last-modified
categories: [방사선안전관리자, 업무, 안전관리규정]
---

### 원자력안전법 시행규칙상 안전관리규정에 포함되어야할 사항들

-   원자력안전법 시행규칙\[시행 2024. 12. 24.\] \[총리령 제2000호, 2024. 12. 24., 타법개정\] 제58조(방사성동위원소등의 생산허가 신청 등)제5항에 "안전관리규정에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다."라고 규정하고 있습니다. 각 호의 사항은 아래와 같습니다.

1.  [방사성동위원소등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항]{style="color:blue;"}

2.  [방사성동위원소등의 구매ㆍ사용 및 판매에 관한 사항]{style="color:blue;"}

3.  [방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항]{style="color:blue;"}

4.  [방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질(이하 “방사성물질등”이라 한다)에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항]{style="color:blue;"}

5.  [방사선안전관리 장비의 보관ㆍ관리 및 교정에 관한 사항]{style="color:blue;"}

6.  [방사선작업종사자 및 수시출입자에 대한 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항]{style="color:blue;"}

7.  [방사선작업종사자 및 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항]{style="color:blue;"}

8.  [방사선장해 발생 여부를 발견하기 위하여 필요한 조치에 관한 사항]{style="color:blue;"}

9.  [방사선장해를 받았거나 받을 우려가 있는 사람에 대하여 필요한 보건상 조치에 관한 사항]{style="color:blue;"}

10. [법 제58조에 따른 기록과 그 비치에 관한 사항]{style="color:blue;"}

11. [위험 시 조치에 관한 사항]{style="color:blue;"}

12. [방사성동위원소등의 분실ㆍ도난 등 사고 시의 조치 및 사고예방에 관한 사항]{style="color:blue;"}

13. [방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항]{style="color:blue;"}

14. [그 밖에 방사선장해의 방어에 필요한 사항]{style="color:blue;"}<br><br><br>

### 관련 고시에 따른 안전관리규정 작성지침

-   안전관리규정 작성지지침 \[시행 2024. 12. 31.\] \[원자력안전위원회고시 제2024-13호, 2024. 12. 31., 타법개정\]에 기술된 아래의 일반지침/세부지침/세부작성지침에 따라 작성하여야 합니다.

제3조(일반지침) 안전관리규정의 작성에 따른 일반지침은 다음 각 호와 같다.\
1. [안전관리규정은 방사선원을 구성하고 있는 요소와 방사선작업 종사자, 일반인, 환경에 미치는 요인에 대하여 충분히 고려하여 작성하여야 한다.]{style="color:blue;"}

2.  [안전관리규정은 객관적이고 가능한 한 정량적인 방법에 의하되, 객관적인 평가방법이 확립되어 있지 않은 경우에는 기존의 사례 또는 자료를 이용하여 작성할 수 있다.]{style="color:blue;"}

3.  [안전관리규정은 사용현장을 충분히 확인하고 이해한 후 작성하여야 한다.]{style="color:blue;"}

4.  [안전관리규정의 내용 중 방사선안전보고서와 유사한 항목은 방사선안전보고서에 기술된 내용과 일치하도록 작성하여야 한다.]{style="color:blue;"}

5.  [안전관리규정 작성을 위한 방사선 안전성 평가에 사용된 방법 및 기술은 검증된 최신의 것이어야 하며, 검증되지 않은 경우에는 그 타당성을 별도로 입증하여야 한다. 이때에 인용된 자료는 출처를 명시하여야 한다.]{style="color:blue;"}

제4조(세부지침) 안전관리규정은 다음 각 호에서 정하는 바에 따라 별지의 세부 작성지침에 따라 작성하여야 한다.\
1. [방사성동위원소 등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항： 방사선안전관리를 위한 조직도와 함께 조직도에 명시된 관련자의 직무를 기술한다.]{style="color:blue;"}

2.  [방사성동위원소 등의 구매ㆍ사용 및 판매에 관한 사항： 방사성동위원소 등의 구매ㆍ사용 및 판매(생산하여 판매하는 경우에는 생산단계를 포함한다)하기 위한 절차 및 관리방법을 기술한다.]{style="color:blue;"}

3.  [방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항： 방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 절차 및 기준을 기술한다.]{style="color:blue;"}

4.  [방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항： 측정의 대상 또는 장소 및 주기와 그 결과의 기록사항 및 보존기간에 대하여 기술하고 관련 양식을 첨부한다.]{style="color:blue;"}

5.  [방사선안전관리장비의 보관ㆍ관리 및 교정에 관한 사항： 방사선안전관리장비의 보관 및 관리방법과 교정주기에 대하여 기술한다.]{style="color:blue;"}

6.  [방사선작업종사자 및 수시출입자 분류 대상을 각각 세부적으로 기술한다.]{style="color:blue;"}

6의2. [방사선작업종사자 및 수시출입자의 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항： 방사선작업종사자 및 수시출입자 피폭방사선량을 평가하기 위한 개인선량계의 패용방법 및 절차와 개인선량계의 관리 및 판독 또는 교정주기에 대하여 기술한다.]{style="color:blue;"}

7.  [방사선작업종사자 또는 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항：교육훈련의 대상, 주기 및 교과목의 내용과 교육훈련을 수행하는 절차 및 결과의 관리에 대하여 기술한다.]{style="color:blue;"}

8.  [방사선장해발생 여부를 발견하기 위하여 필요한 조치에 관한 사항： 방사선장해발생의 여부를 발견하기 위한 건강진단 등 조치사항에 대하여 기술한다.]{style="color:blue;"}

9.  [방사선장해를 받은 자 또는 그 우려가 있는 자에 대하여 취하여야 할 보건상 조치에 관한 사항：방사선장해발생자 또는 우려자에 대한 구체적인 조치사항에 대하여 기술한다.]{style="color:blue;"}

10. [「원자력안전법」 제58조에 따른 기록과 이의 비치에 관한 사항：원자력안전법령 및 관련 고시에서 규정하고 있는 각종 기록사항 및 보존기간을 기술하고 관련양식을 첨부한다.]{style="color:blue;"}

11. [위험시의 조치에 관한 사항： 생산 또는 사용하고자 하는 방사성동위원소 등과 관련하여 비상사태를 대비한 응급조치, 보고 및 조치사항에 대하여 기술한다.]{style="color:blue;"}

12. [방사성동위원소 등의 분실ㆍ도난 등 사고시의 조치 및 사고예방에 관한 사항： 방사성동위원소 등의 분실 또는 도난 등의 사고방지를 위한 구체적인 수행계획과 사고발생시의 조치사항에 대하여 기술한다.]{style="color:blue;"}

13. [방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항：방사선안전관리에 관한 방사선안전관리자의 권한, 책임 및 직무수행에 관하여 구체적으로 기술한다.]{style="color:blue;"}

14. [기타 방사선장해의 방어에 필요한 사항：사용하고자 하는 방사성동위원소 등의 특성에 따라 별도로 안전관리가 요구되는 사항이 있는 경우에는 이에 관하여 기술한다.]{style="color:blue;"}

### 세부작성지침에 따른 안전관리규정 작성

1.  방사성동위원소 등 또는 방사성동위원소에 의하여 오염된 물질을 취급 하는 조직 및 그 기능에 관한 사항
    -   조직도
        -   [대표자를 정점으로 한 방사선원 및 사용시설 등의 이용과 관련된 안 전관리업무를 수행하는 조직을 조직도의 형태로 도시한다.]{style="color:blue;"}
    -   직무
        -   [대표이사, 부서장, 방사선안전관리자 및 방사선작업종사자의 직무에 관한 사항을 기술한다. 다만, 방사선안전관리자가 2인 이상인 경우에는 각각의 직무를 분리하여 기술한다.]{style="color:blue;"}
2.  방사성동위원소 등의 구매ㆍ사용 및 판매에 관한 사항
    -   구매
        -   [방사선원의 구매ㆍ인수ㆍ인계ㆍ저장절차를 기술한다.]{style="color:blue;"}
        -   [구매요구서를 사용하는 경우에는 구매요구서 양식, 작성방법 및 승인 절차를 기술한다.]{style="color:blue;"}
    -   사용
        -   [방사선원의 반입ㆍ반출ㆍ인수ㆍ인계ㆍ승인절차를 기술한다.]{style="color:blue;"}
        -   [방사선원을 사용할 때에 준수하여야 하는 기술기준을 기술한다.]{style="color:blue;"}
        -   [밀봉선원을 사용하는 경우에는 선원의 누설점검 방법 및 절차에 대하 여 기술한다.]{style="color:blue;"}
    -   판매
        -   [방사성동위원소 등의 판매허가자의 경우에는 운반을 포함한 방사선원 의 판매 및 승인절차를 기술한다.]{style="color:blue;"}
        -   [방사선원을 판매 및 운반할 때에 준수하여야 하는 기술기준을 기술한다.]{style="color:blue;"}
        -   [구매자에게 공급하고자 하는 사용ㆍ운영ㆍ보수 및 관리방법이 포함된 설명서의 내용에 대하여 기술한다.]{style="color:blue;"}
        -   [판매한 방사선원의 사후관리 내용 및 방법에 대하여 기술한다.]{style="color:blue;"}
    -   생산
        -   [방사성동위원소 등의 생산허가자의 경우에는 생산단계마다의 관리절 차를 기술한다.]{style="color:blue;"}
3.  방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보 관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항
    -   절차
        -   [분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도의 각각에 대 한 취급 및 승인절차를 기술한다.]{style="color:blue;"}
    -   기술기준
        -   [분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도의 각각에 대 한 취급기준을 기술한다.]{style="color:blue;"}
4.  방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물 질에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항
    -   측정
        -   [방사선량률의 측정방법, 절차 및 주기에 대하여 기술한다.]{style="color:blue;"}
        -   [방사능오염의 측정방법, 절차 및 주기에 대하여 기술한다.]{style="color:blue;"}
        -   [피폭방사선량의 측정방법, 절차 및 주기에 대하여 기술한다.]{style="color:blue;"}
    -   기록 및 보존
        -   [측정결과의 기록사항 및 그 보존기간에 대하여 기술한다.]{style="color:blue;"}
        -   [기록양식을 첨부한다.]{style="color:blue;"}
5.  방사선안전관리장비의 보관ㆍ관리 및 교정에 관한 사항
    -   보관 및 관리
        -   [방사선안전관리장비의 보관장소 및 비치장소를 기술한다.]{style="color:blue;"}
        -   [방사선안전관리장비의 점검방법, 절차 및 주기에 대하여 기술한다.]{style="color:blue;"}
    -   교정
        -   [방사선안전관리장비의 검ㆍ교정주기에 대하여 기술한다.]{style="color:blue;"}
6.  「원자력안전법」 제2조제21호 및 「원자력안전법 시행령」 제2조제8호 에 따른 방사선작업종사자 및 수시출입자의 정의에 부합하도록 방사선작 업종사자 및 수시출입자 분류대상을 각각 세부적으로 기술한다.
    -   6의2. 방사선작업종사자 및 수시출입자의 피폭방사선량의 평가 및 개인선량 계의 관리에 관한 사항
        -   피폭방사선량의 평가
            -   [피폭방사선량의 평가방법에 대하여 기술한다.]{style="color:blue;"}
            -   [개인선량계의 분실 등 판독 특이자에 대한 후속조치와 평가방법에 대 하여 기술한다.]{style="color:blue;"}
        -   개인선량계의 관리
            -   [개인선량계의 지급 및 회수 등 관리절차를 기술한다.]{style="color:blue;"}
            -   [보조선량계의 경우에는 비치장소와 점검절차 및 교정주기에 대하여 기술한다.]{style="color:blue;"}
7.  방사선작업종사자 또는 수시출입자의 방사선장해발생을 방지하기 위하 여 필요한 교육훈련에 관한 사항
    -   [교육훈련계획의 수립 및 승인절차에 대하여 기술한다.]{style="color:blue;"}
    -   [교육훈련의 시기, 과목 및 시간에 대하여 기술한다.]{style="color:blue;"}
    -   [교육훈련을 위한 시설 및 장비에 대하여 기술한다.]{style="color:blue;"}
    -   [교육훈련의 평가방법 및 그 결과의 기록사항에 대하여 기술한다.]{style="color:blue;"}
8.  방사선장해발생 여부를 발견하기 위하여 필요한 조치에 관한 사항
    -   [방사선관리구역의 설정기준 및 관리절차에 대하여 기술한다.]{style="color:blue;"}
    -   [방사선작업종사자 및 수시출입자에 대한 건강진단의 시기, 방법 및 주 기에 대하여 기술한다.]{style="color:blue;"}
    -   [가능하다면, 전담의료기관의 명칭, 위치 및 담당의의 신상명세를 기술 한다.]{style="color:blue;"}
    -   [방사선장해를 유발할 수 있는 시설의 점검에 대하여 기술한다.]{style="color:blue;"}
9.  방사선장해를 받은 자 또는 그 우려가 있는 자에 대하여 취하여야 할 보건상 필요한 조치에 관한 사항
    -   [건강진단 결과 특이자에 대한 조치사항에 대하여 기술한다.]{style="color:blue;"}
    -   [조치결과에 대한 보고내용 및 절차에 대하여 기술한다.]{style="color:blue;"}
10. 「원자력안전법」 제58조에 따른 기록과 이의 비치에 관한 사항
    -   기록
        -   [기록사항을 기술하고 관련양식을 첨부한다.]{style="color:blue;"}
    -   비치
        -   [기록장부의 비치장소 및 보존장소ㆍ기간을 기술한다.]{style="color:blue;"}
11. 위험시의 조치에 관한 사항
    -   [사용하고자 하는 방사성동위원소 등과 관련한 비상사태를 고려하여 이에 대비한 응급조치, 보고 및 조치사항에 대하여 기술한다.]{style="color:blue;"}
    -   [비상대응을 위한 방사선작업의 승인절차 및 방법을 기술한다.]{style="color:blue;"}
    -   [조치결과에 대한 보고내용 및 절차에 대하여 기술한다.]{style="color:blue;"}
12. 방사성동위원소 등의 분실ㆍ도난 등 사고시의 조치 및 사고예방에 관 한 사항
    -   [분실ㆍ도난을 방지하기 위한 점검계획에 대하여 기술한다.]{style="color:blue;"}
    -   [분실ㆍ도난 등의 사고에 따른 후속조치 절차 및 방법에 대하여 기술 한다.]{style="color:blue;"}
    -   [사고발생시 보고내용 및 방법 대하여 기술한다.]{style="color:blue;"}
13. 방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항
    -   [방사선안전관리자의 권한 및 책임을 명확하게 기술한다.]{style="color:blue;"}
    -   [방사선안전관리자의 권한 및 책임을 수행하기 위한 구체적인 직무의 내용을 기술한다.]{style="color:blue;"}
14. 기타 방사선장해의 방어에 필요한 사항
    -   진료를 목적으로 방사선기기를 인체에 사용하는 사업소에서는 다음의 사항을 기술한다.
        -   [품질관리절차서를 수립하고 이행하는 절차에 관한 사항]{style="color:blue;"}
        -   [취급절차서를 구비하여 이행하는 절차에 관한 사항]{style="color:blue;"}
    -   사용하고자 하는 방사성동위원소 등의 특성에 따라 별도로 안전관리 가 요구되는 사항이 있는 경우에는 이에 관하여 기술한다.
    -   「원자력안전법」에서 규정하고 있는 기술기준이외에 별도로 적용하 고자 하는 국내ㆍ외의 기술기준이 있는 경우에는 이를 기술한다.
