---
title: "기술기준 준수여부 점검"
description: "기술기준 준수여부의 점검을 위해 알아야 할 관련법령규칙을 정리하였습니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-11-27"
date-modified: last-modified
categories: [방사선안전관리자, 업무, 안전관리규정]
---

### 원자력안전법상 기술기준에 대한 기술

-   원자력안전법시행 2025. 4. 23.\] \[법률 제20533호, 2024. 10. 22., 일부개정\]제59조(기준준수 의무 등)에 기술기준에 대한 의무 사항이 기술되어 있습니다.

제59조(기준준수의무 등) ① 허가사용자 및 신고사용자는 다음 사항에 관하여 위원회규칙으로 정하는 기술기준을 준수하여야 한다.

1.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비

2.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리 및 배출

3.  방사성동위원소등의 이동사용 및 판매

② 위원회는 사업소 안에서의 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설 또는 사용시설등의 위치ㆍ구조 및 설비, 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ처리 및 배출과 방사성동위원소등의 이동사용이나 판매가 제1항에 따른 기술기준에 적합하지 아니하다고 인정하면 허가사용자 및 신고사용자에게 해당 시설의 수리ㆍ개선ㆍ이전 또는 생산ㆍ사용의 정지, 취급방법의 변경과 그 밖의 안전에 필요한 조치를 명할 수 있다.

③ 허가사용자 및 그 종업원은 제53조제3항에 따른 안전관리규정을 준수하여야 하며, 업무대행자와 그 종업원은 제54조제3항에 따른 업무대행규정을 준수하여야 한다.

### 위원회규칙으로 정하는 기술기준

-   위원회규칙으로 정하는 기술기준은 크게 2가지가 있습니다.

#### 방사선 안전관리 등의 기술기준에 관한 규칙(원자력안전위원회규칙 제50호, 2023. 9. 25., 일부개정)

-   주요 부분만 발췌하면 아래와 같습니다.

##### 제1장 총 칙

###### 제1조 (목적)

이 규칙은 「원자력안전법」 및 동법시행령에서 위임된 사항중 방사선으로 인한 장애의 방지를 위하여 필요한 방사선안전관리 등의 기술기준에 관한 사항을 규정함을 목적으로 한다.

###### 제2조 (정의)

① 이 규칙에서 사용하는 용어의 정의는 다음과 같다.

1.  "작업실"이라 함은 밀봉되지 아니한 방사성동위원소 또는 방사성동위원소에 의하여 오염된 물건으로서 밀봉되지 아니한 것을 사용 또는 포장하는 곳을 말한다.

2.  "오염검사실"이라 함은 인체 또는 작업복ㆍ신발ㆍ보호구 등 인체에 착용하였던 물건의 표면이 방사성물질에 의하여 오염되었는지 여부를 검사하는 곳을 말한다.

3.  "배수설비"라 함은 액체상태의 방사성물질이나 그에 의하여 오염된 액체를 정화하거나 배출하는 설비로서 농축기ㆍ분리기ㆍ이온교환장치 등의 배출액처리장치 또는 저장탱크ㆍ희석탱크ㆍ여과탱크 등 배출액정화탱크의 배수관ㆍ배수구 등을 말한다.

4.  "고형화처리설비"라 함은 방사성물질 등을 콘크리트 기타의 고형화 재료에 의하여 고형화하는 설비로서 분쇄장치ㆍ압축장치ㆍ혼합장치 또는 재포장장치 등을 말한다.

5.  "외부방사선량률"이라 함은 인체 외부로부터 피폭되는 시간당방사선량(밀리시버트/시간)을 말한다.

6.  "저분산성방사성물질"이라 함은 분말형태가 아닌 고체이거나 밀봉된 캡슐에 내장되어 있어 분산성이 제한되는 방사성물질을 말한다.

7.  "운반지수"라 함은 운반물ㆍ덧포장ㆍ탱크 또는 화물컨테이너에 지정되는 등급으로서 방사선피폭에 대한 관리를 위하여 사용되는 수치를 말한다.

8.  "핵임계안전지수"라 함은 핵분열성물질이 들어 있는 운반물ㆍ덧포장ㆍ탱크 또는 화물컨테이너에 지정되는 등급으로서 운반물ㆍ덧포장ㆍ탱크 또는 화물컨테이너의 집적량을 관리하기 위하여 사용되는 수치를 말한다.

9.  "심층처분"이라 함은 지하 깊은 곳의 안정한 지층구조에 천연방벽 또는 공학적 방벽으로 방사성폐기물을 처분하는 것을 말한다.

10. "천층처분"이라 함은 다음 각 목의 어느 하나에 해당하는 것을 말한다.

가. 동굴처분 : 지하의 동굴 또는 암반 내에 천연방벽 또는 공학적 방벽으로 방사성폐기물을 처분하는 것

나. 표층처분 : 지표면과 가까이에 천연방벽 및 공학적 방벽으로 방사성폐기물을 처분하는 것

다. 매립형처분 : 지표면과 가까이에 천연방벽으로 방사성폐기물을 매립하여 처분하는 것

② 제1항외에 이 규칙에서 사용하는 용어의 정의는 「원자력안전법」(이하 "법"이라 한다), 동법 시행령(이하 "영"이라 한다) 또는 동법 시행규칙에서 정하는 바에 의한다.

###### 제3조 (방사선관리구역)

① 법 제2조제16호에서 "원자력안전위원회규칙으로 정하는 값"이라 함은 다음 각호와 같다.

1.  외부방사선량률 : 1주당 400마이크로시버트

2.  공기중의 방사성물질의 농도 : 유도공기중농도

3.  물체표면의 오염도 : 허용표면오염도

② 외부방사선량률 등이 제1항의 규정에 의한 값을 초과할 우려가 있는 곳에 대하여는 사람의 출입을 관리하고 출입자에 대한 방사선의 장해를 방지하기 위하여 다음 각호의 조치를 하여야 한다.

1.  방사선관리구역의 설정

2.  벽ㆍ울타리 등의 구획물로 구획하여 별표 1에 의한 표지를 부착함으로써 다른 장소와 구별하고 방사선작업종사자외의 사람이 당해 구역에 출입하는 경우에는 방사선작업종사자의 지시에 따르도록 할 것

3.  바닥ㆍ벽 기타 사람이 접촉할 우려가 있는 물체의 표면이 방사성물질에 오염된 경우 그 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  방사선관리구역으로부터 사람이 퇴거하거나 물품을 반출하는 경우에는 인체 및 의복ㆍ신발 등 인체에 착용하고 있는 물품과 반출하는 물품(그 물품이 용기에 들어있거나 포장한 경우에는 그 용기 또는 포장)표면의 방사성물질의 오염도가 허용표면오염도의 10분의 1을 초과하지 아니하도록 할 것

#### 제3장 방사성동위원소 및 방사선발생장치의 안전관리

##### 제1절 방사성동위원소 및 방사선발생장치의 시설기준

##### 제1관 개봉선원

###### 제16조 (적용범위)

법 제55조제1항제1호 및 법 제59조제1항제1호의 규정에 의한 방사성동위원소중 밀봉되지 아니한 것(이하 "개봉선원"이라 한다)에 관한 생산시설 및 사용시설 등의 위치ㆍ구조 및 설비에 관한 기술기준은 제17조부터 제23조까지, 제23조의2의 규정을 적용한다.

###### 제17조 (개봉선원의 생산시설)

① 개봉선원의 생산시설은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.

② 개봉선원 생산시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부는 내화구조로 하거나 불연재료를 사용할 것

2.  다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

가. 생산시설 안의 사람이 상시 출입하는 장소에서의 방사선량

나. 사업소의 경계에 인접하는 구역에서의 방사선량

3.  다음 각목의 기준에 따라 작업실을 설치할 것

가. 작업실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

나. 작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것

4.  다음 각목의 기준에 따라 오염검사실을 설치할 것

가. 오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

나. 오염검사실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분은 제3호 가목의 기술기준에 적합한 것으로 할 것

다. 오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 장비를 갖출 것

5.  개봉선원을 생산하기 위한 방사선 조사시설(조사시설)에는 다음 각목의 기준에 따라 시설을 설치할 것

가. 출입구에 방사선 조사중임을 자동적으로 표시하는 장치를 설치할 것

나. 방사선 조사 여부에 따라 출입구가 개폐되는 연동장치를 할 것

다. 내부를 상시 감시할 수 있는 장치를 할 것

라. 사람의 출입을 제한하는 장치를 할 것

6.  시설의 경계에는 울타리 그 밖에 사람의 출입을 제한하는 시설을 할 것. 다만, 제2호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7.  생산시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 그 밖에 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

###### 제18조 (사용시설등의 위치)

개봉선원(개봉선원)의 사용시설등은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.

###### 제19조 (사용시설 및 분배시설)

① 개봉선원의 사용시설 및 분배시설의 구조 및 설비에 관한 기술기준은 다음 각 호와 같다.

1.  주요구조부는 내화구조로 하거나 불연재료를 사용할 것. 다만, 원자력안전위원회가 정하여 고시하는 것은 그러하지 아니하다.

2.  사용시설은 개봉선원을 취급하기 위한 장비의 설치 및 작업 수행에 필요한 공간을 확보할 것

3.  다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

가. 사용시설안 및 분배시설안의 사람이 상시 출입하는 장소에서의 방사선량

나. 사업소의 경계에 인접하는 구역에서의 방사선량

4.  다음 각목과 같은 작업실을 설치할 것

가. 작업실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

나. 작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것. 다만, 원자력안전위원회가 정하는 것은 그러하지 아니하다.

5.  다음 각목의 1에 해당하는 오염검사실을 설치할 것. 다만, 인체 및 작업복ㆍ신발등 인체에 착용하는 물건의 표면이 방사성동위원소에 의하여 오염될 우려가 없도록 밀폐된 장치안에서 개봉선원을 사용 또는 분배하는 경우와 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

나. 오염검사실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분은 제4호 가목의 기술기준에 적합한 것으로 할 것

다. 오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 기재(기재)를 갖출 것

6.  경계에는 울타리 기타 사람의 출입을 제한하는 시설을 할 것. 다만, 제3호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7.  사용시설ㆍ분배시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

② 제1항의 규정은 누수의 조사, 곤충의 역학적 조사 또는 원료물질의 생산공정중 이동상황의 조사 등을 위하여 개봉선원을 광범위하게 분산ㆍ이동시키는 경우 또는 일시적으로 사용ㆍ분배하는 경우에는 이를 적용하지 아니한다.

###### 제20조 (저장시설)

개봉선원 저장시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  저장시설의 구조는 다음 각목과 같이 할 것

가. 저장실의 주요 구조부 및 출입문은 내화구조로 하거나 불연재료를 사용할 것

나. 저장함은 내화구조로 하거나 불연재료를 사용할 것

2.  저장시설에는 제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  저장시설에 비치하는 용기는 다음 각목의 기준에 적합할 것

가. 외부의 공기를 오염시킬 우려가 있는 개봉선원을 넣는 용기는 기밀구조일 것

나. 액체상의 개봉선원을 넣는 용기의 구조는 액체가 누출되지 아니하도록 하고, 그 재료는 액체가 침투할 수 없는 것으로 할 것

다. 액체상 또는 기체상의 개봉선원을 넣는 용기가 균열 또는 파손될 우려가 있는 때에는 밑받이ㆍ흡수재 기타 개봉선원에 의한 오염의 확산을 방지하기 위한 시설 또는 기구를 설치할 것

4.  저장시설의 문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 시설 또는 기구를 설치할 것

5.  저장시설의 경계에는 울타리 기타 사람의 출입을 제한하는 시설을 설치할 것

6.  저장실ㆍ저장함, 제3호의 용기 및 저장시설의 경계에 설치하는 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

###### 제21조 (보관시설)

개봉선원 및 그에 의하여 오염된 물질의 보관시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조로 하거나 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  다음 각목의 기준에 적합한 보관설비를 갖출 것

가. 외부와 구획된 구조로 할 것

나. 문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 설비 또는 기구를 설치할 것

다. 제20조제3호의 기술기준에 적합한 용기를 비치할 것. 다만, 방사성동위원소에 의하여 오염된 대형기계 등으로서 용기에 넣기가 곤란하여 오염확산을 방지하기 위한 조치를 취한 경우에는 그러하지 아니하다.

4.  보관설비, 제3호 다목의 용기 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

###### 제22조 (처리시설)

개봉선원 및 그에 의하여 오염된 물질의 처리시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조 또는 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  방사성동위원소 및 그에 의하여 오염된 물질을 소각하는 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 소각설비를 설치할 것

4.  방사성동위원소 및 그에 의하여 오염된 물질을 콘크리트 기타 고형화 재료에 의하여 고형화하는 경우에는 다음 각목에 정하는 바에 따라 고형화처리설비를 설치하는 외에 오염검사실 및 제23조제4호의 기준에 적합한 배기설비를 설치할 것

가. 고형화처리설비는 방사성동위원소 및 그에 의하여 오염된 물질이 누설되거나 넘쳐 흐르지 아니하고 분진이 확산되지 아니하는 구조로 할 것

나. 고형화처리설비는 액체가 침투하지 아니하고 부식에 강한 재료로 할 것

5.  소각로ㆍ오염검사실 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

###### 제23조 (배출시설)

개봉선원 및 그에 의하여 오염된 물질의 배출시설의 구조 및설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조 또는 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  액체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는바에 따라 배수설비를 설치할 것. 다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 배수설비는 배수구에서 채취한 배출액의 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖추도록 할 것. 다만, 배수구에서의 배수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배수중 방사성동위원소의 농도를 감시하기 위한 배수감시설비를 하고 사업소의 경계외부에서의 수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하는 경우에는 그러하지 아니하다.

나. 배수설비의 구조는 배출액이 누설되지 아니하도록 하고, 그 재료는 배출액이 침투할 수 없고 내식성이 강한 것으로 할 것

다. 배수정화조는 배출액을 채취하여 배출액의 방사성동위원소 농도를 쉽게 측정할 수 있도록 이를 설치하고, 그 주위에는 울타리 등 사람의 출입을 제한하는 시설을 설치할 것

4.  기체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는 바에 따라 배기설비를 설치할 것. 다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 배기설비는 작업실안의 사람이 상시 출입하는 장소에서의 공기중 방사성동위원소의 농도를 유도공기중농도 이하로 하는 능력을 갖출 것

나. 배기설비는 배기구의 배기중 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖출 것. 다만, 배기구에서의 배기중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배기중 방사성동위원소의 농도를 감시하기 위한 배기감시설비를 하고 사업소 등의 경계외부에서의 공기중 방사성동위원소 농도를 배출관리기준의 제한값이하로 하는 경우에는 그러하지 아니하다.

다. 배기설비의 구조는 배기구외로 기체가 누설되지 아니하도록 하고, 그 재료는 내식성이 강한 것으로 할 것

라. 배기설비에는 고장이 발생한 경우 방사성동위원소에 의하여 오염된 공기의 확산을 신속히 방지할 수 있는 장치를 할 것

5.  배수설비ㆍ배기설비와 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

###### 제23조의2 (개봉선원의 보안관리 시설등)

원자력안전위원회가 정하는 수량 이상의 개봉선원 생산시설 및 사용시설등에는 원자력안전위원회가 정하여 고시하는 바에 따라 보안관리 시설 또는 설비를 설치하여야 한다.

제2절 방사성동위원소 및 방사선발생장치의 취급기준

##### 제1관 개봉선원

###### 제35조 (적용범위)

법 제59조제1항제2호의 규정에 의한 방사성동위원소중 개봉선원의 생산 및 개봉선원 또는 그에 의하여 오염된 물질의 사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리 또는 배출에 관한 기술기준은 제36조부터 제40조까지, 제40조의2의 규정을 적용한다.

###### 제36조(생산)

개봉선원의 생산에 관한 기술기준은 다음 각호와 같다.

1.  다음 각목에 해당하는 조치를 함으로써 방사선작업종사자 또는 수시출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

가. 차폐벽이나 차폐물에 의하여 방사선을 차폐할 것

나. 원격조작장치ㆍ집게 등을 사용하여 개봉선원과 인체 사이에 적당한 거리를 확보하고 차폐물을 이용하도록 할 것

다. 면밀한 작업계획 및 숙달ㆍ훈련 등을 통하여 인체에 방사선이 피폭되는 시간을 단축할 것

2.  생산시설 안의 사람이 상시 출입하는 장소에서 사람이 호흡하는 공기중 방사성동위원소의 농도는 방사성동위원소에 의하여 오염된 공기를 정화하거나 배기함으로써 유도공기중농도를 초과하지 아니하도록 할 것

3.  생산시설 안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  생산시설 안에서는 작업복ㆍ신발ㆍ보호구 등을 착용하되, 이를 착용한채 작업실을 나가지 아니하도록 할 것

5.  생산시설을 나갈 때에는 인체에 착용하고 있는 물건표면에 대하여 방사성동위원소에 의한 오염상태를 검사하고 그 오염을 제거할 것

6.  생산시설에는 눈에 띄기 쉬운 장소에 방사선장해방지에 필요한 주의사항을 게시할 것

###### 제37조 (사용 및 분배)

개봉선원의 사용 또는 분배에 관한 기술기준은 다음 각호와 같다.

1.  사용시설 또는 작업실에서 사용ㆍ분배할 것

2.  다음 각목에 해당하는 조치를 함으로써 방사선작업종사자 또는 수시 출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

가. 차폐벽이나 차폐물에 의하여 방사선을 차폐할 것

나. 원격조작장치ㆍ집게 등을 사용하여 개봉선원과 인체 사이에 적당한 거리를 확보하고 차폐물을 이용하도록 할 것

다. 면밀한 작업계획 및 숙달ㆍ훈련 등을 통하여 인체에 방사선이 피폭되는 시간을 단축할 것

3.  작업실안의 사람이 상시 출입하는 장소에서 사람이 호흡하는 공기중 방사성동위원소의 농도는 방사성동위원소에 의하여 오염된 공기를 정화하거나 배기함으로써 유도공기중농도를 초과하지 아니하도록 할 것

4.  작업실 또는 오염검사실안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

5.  작업실안에서는 작업복ㆍ신발ㆍ보호구 등을 착용하되, 이를 착용한 채 작업실을 나가지 아니하도록 할 것

6.  작업실을 나갈 때에는 인체 및 작업복ㆍ신발ㆍ보호구 등 인체에 착용하고 있는 물건표면에 대하여 방사성동위원소에 의한 오염상태를 검사하고 그 오염을 제거할 것

7.  사용 또는 분배시설에는 눈에 띄기 쉬운 장소에 방사선장해방지에 필요한 주의사항을 게시할 것

제38조 (저장) 개봉선원의 저장에 관한 기술기준은 다음 각호와 같다.

1.  용기에 넣어 저장시설에 저장할 것

2.  저장시설의 저장능력을 초과하여 저장하지 아니할 것

3.  제37조제2호 각목의 조치를 함으로써 방사선작업종사자 또는 수시출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

4.  저장함은 개봉선원의 보관중에는 그 운반을 제한하도록 할 것

5.  저장시설안의 사람이 호흡하는 공기중 방사성동위원소의 농도가 유도공기중 농도를 초과하지 아니하도록 할 것

6.  저장시설안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 다음 각목의 조치를 할 것

가. 액체상의 방사성동위원소는 액체가 흘러넘치지 아니하는 구조 및 액체가 침투할 수 없는 재료로 된 용기에 넣을 것

나. 액체상의 방사성동위원소를 넣은 용기가 균열 또는 파손될 우려가 있는 경우에는 밑받이ㆍ흡수재 기타 시설 또는 기구를 사용하여 방사성동위원소에 의한 오염의 확산을 방지할 것

7.  방사선관리구역에는 사람의 출입을 제한하는 조치를 할 것

#### 제39조 (운반)

① 개봉선원 및 그에 의하여 오염된 물질을 사업소 안에서 운반하는 경우의 기술기준은 다음 각호와 같다.

1.  용기에 봉입하여 운반할 것. 다만, 다음 각목의 조치를 하는 경우에는 그러하지 아니하다.

가. 방사성동위원소에 의하여 오염된 것(당해 물질에 함유된 방사성동위원소의 농도가 허용표면오염도를 초과하지 아니하는 것에 한한다)으로서 방사성동위원소의 확산 또는 누설의 방지조치를 하거나 기타 원자력안전위원회가 정하여 고시하는 방사선장해방지를 위한 조치를 하여 운반하는 경우

나. 방사성동위원소에 의하여 오염된 것으로서 대형기계 등 용기에 넣어 운반하기 어려운 것을 원자력안전위원회의 승인을 얻어 운반하는 경우

2.  방사성동위원소 및 그에 의하여 오염된 물질을 넣은 용기(제1호 가목 또는 나목의 규정에 의한 방사성동위원소에 의하여 오염된 것을 포함하며, 이하 이 조에서 "운반물"이라 한다) 및 이를 적재하는 차량이나 방사성동위원소 및 그에 의하여 오염된 물질을 운반하는 기계ㆍ기구(이하 이 조에서 "차량등"이라 한다)의 표면으로부터 10센티미터 및 차량의 외부표면으로부터 2미터 떨어진 위치의 방사선량률이 각각 원자력안전위원회가 정하여 고시하는 방사선량률을 초과하지 아니하도록 하고 운반물표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

3.  운반물을 차량등에 실을 때에는 운반중에 이동ㆍ전도 또는 전락 등에 의하여 운반물의 안전성이 손상되지 아니하도록 할 것

4.  동일한 차량등에 제98조의 규정에 의한 위험물과 운반물을 혼재하지 아니하도록 할 것

5.  운반물의 운반경로에는 표지를 설치하거나 감시인을 배치하는 등의 방법으로 운반에 종사하지 아니하는 자와 운반에 사용되지 아니하는 차량등의 출입을 제한할 것

6.  운반물을 운반하는 차량등은 서행하도록 할 것

7.  방사성동위원소의 취급에 관하여 지식과 경험을 갖춘 자를 동행하게 하거나 방사선장해방지를 위하여 필요한 감독을 하도록 할 것

8.  운반물 및 차량등에는 눈에 띄기 쉬운 곳에 별표 2에 의한 표지를 부착할 것

9.  방사선작업종사자외의 사람이 운반물의 운반에 종사하는 경우에는 그의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

10. 용기 밖의 운반물 등을 오염시킬 우려가 있는 방사성동위원소 및 그에 의하여 오염된 물질은 기밀구조의 용기에 넣어 운반할 것

11. 액체상태의 방사성동위원소 및 그에 의하여 오염된 물질은 그 액체의 침투나 부식이 잘 되지 아니하는 재료로 만들어지고 전복되기 어려운 구조로 된 용기에 넣어 운반할 것

② 제1항제3호의 조치의 전부 또는 일부를 하기가 곤란한 경우에는 원자력안전위원회의 승인을 얻은 조치로 이를 갈음할 수 있다. 이 경우 당해 운반물의 표면으로부터 10센티미터 및 2미터 떨어진 위치의 방사선량률은 각각 원자력안전위원회가 정하여 고시하는 방사선량률을 초과하여서는 아니된다.

③ 제1항제1호ㆍ제2호 및 제5호부터 제8호까지는 방사선관리구역안에서의 운반에 관하여는 이를 적용하지 아니한다.

④ 제1항의 규정은 방사성동위원소 및 그에 의하여 오염된 물질을 사용시설등의 안에서 운반하는 경우와 운반시간이 짧고 방사선장해의 우려가 없는 경우에는 이를 적용하지 아니한다.

###### 제40조 (보관ㆍ처리 및 배출)

사업소안에서 방사성동위원소 또는 그에 의하여 오염된 물질을 보관ㆍ처리 및 배출하는 경우에는 다음 각호의 기술기준에 따르는 외에 제37조 각호(제1호를 제외한다)의 규정을 준용한다. 이 경우 동조제7호중 "사용 또는 분배시설"은 "보관ㆍ처리 및 배출시설"로 본다.

1.  기체상의 방사성동위원소 또는 그에 의하여 오염된 물질은 이를 배기설비로 정화하거나 배출할 것

2.  제1호의 방법으로 배출하는 경우에는 배기설비의 배기구에서의 배기중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 할 것. 다만, 제23조제4호 나목 단서에 해당하는 경우에는 그러하지 아니하다.

3.  배기설비에 부착한 방사성동위원소를 제거하는 때에는 깔개ㆍ밑받이 또는 흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설ㆍ기구 및 보호구를 사용할 것

4.  액체상의 방사성동위원소 또는 그에 의하여 오염된 물질은 다음 각목의 1의 방법으로 보관ㆍ처리 또는 배출할 것

가. 배수설비로 정화하거나 배출할 것

나. 용기에 넣거나 고형화처리설비안에서 콘크리트 기타 고형화재료로 고형화하여 보관할 것

다. 방사선장해방지를 위하여 원자력안전위원회가 정하여 고시하는 기준에 따라 소각할 것

5.  제4호 가목의 방법으로 배출하는 경우에는 배수설비의 배수구에 있어서의 배출액중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 할 것. 다만, 제23조제3호 가목 단서에 해당하는 경우에는 그러하지 아니하다.

6.  제4호 가목의 방법으로 배출하는 경우 배출액을 처리하는 때 또는 동목의 배수설비의 부착물 또는 침전물 등의 방사성동위원소를 제거하는 때에는 깔개ㆍ밑받이 또는 흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설ㆍ기구 또는 보호구를 사용할 것

7.  제4호 나목의 방법으로 보관하는 경우 액체상의 방사성동위원소 및 그에 의하여 오염된 물질을 넣는 용기는 액체가 흘러 넘치지 아니하는 구조 및 액체가 침투할 수 없는 재료로 된 용기에 넣을 것

8.  제4호 나목의 방법중 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질을 용기에 넣어 보관하는 경우 당해 용기가 균열 또는 파손될 우려가 있는 때에는 밑받이ㆍ흡수재 기타 방사성동위원소에 의한 오염의 확산을 방지하기 위한 시설 또는 기구를 사용하여 방사성동위원소의 오염의 확산을 방지할 것

9.  제4호 나목의 방법중 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질을 고형화하는 경우에는 액체상의 방사성동위원소 또는 그에 의하여 오염된 물질의 확산 또는 누설을 방지할 수 있을 것

###### 제40조의2 (개봉선원의 보안관리등)

원자력안전위원회가 정하는 수량 이상의 개봉선원을 생산ㆍ사용ㆍ분배ㆍ보관ㆍ저장 또는 운반하는 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 보안관리 및 그에 관련된 계획 등을 수립하여 이행하여야 한다.

##### 제3절 의료분야의 안전관리

###### 제49조 (적용범위)

법 제55조제1항제1호 및 법 제59조제1항제1호ㆍ제2호의 규정에 의한 의료기관에서의 사용시설등의 시설기준 및 취급기준에 관하여는 제16조부터 제23조까지, 제23조의2, 제24조부터 제29조까지, 제29조의2, 제30조부터 제40조까지, 제40조의2, 제41조부터 제46조까지, 제46조의2, 제47조 및 제48조를 적용하는 외에 제50조부터 제54조까지를 적용한다.

###### 제50조 (의료방사선 방호 및 관리)

① 방사성동위원소등을 인체에 사용함에 따른 방사선피폭(이하 "의료피폭"이라 한다)의 관리 대상 및 범위는 다음 각 호와 같다.

1.  진료 목적으로 받는 개인의 피폭

2.  진료를 받은 임산부의 태내 배태아 또는 모유 수유하는 환자의 유아가 받는 피폭

3.  진료 환자를 간병하는 가족이나 친지가 받는 피폭

4.  방사선을 이용한 의생명 연구 대상으로 참여하는 연구 자원자가 받는 피폭

② 방사성동위원소등을 인체에 사용하는 자는 방사선피폭으로 인한 해로움보다 이로움이 크도록 하여야 한다.

③ 제2항에 따른 사용자는 방사선 피폭이 경제적, 사회적 인자를 고려해 합리적으로 달성할 수 있는 범위에서 낮게 유지되도록 하여야 한다.

###### 제51조 (사용자의 책임)

① 방사성동위원소등을 인체에 사용하는 자는 의료방사선 방호에 충분한 전문성을 가진 의사가 의료방사선을 사용하도록 하여야 한다.

② 방사성동위원소등을 인체에 사용하는 자는 의사의 의뢰와 함께 방사선방호 대책 수립을 확인하고 원자력안전위원회가 정하여 고시하는 바에 따라 의료피폭을 받는 사람 또는 법적 보호자가 적절하게 이해하고 동의한 경우가 아니면 의료피폭을 받지 않도록 하여야 한다.

③ 제1항에 따른 사용자는 의도되지 아니한 또는 사고에 의한 의료피폭 가능성을 최소화하기 위한 모든 가용한 수단을 강구해야 하며, 이러한 의료피폭이 있는 경우 즉시 조사를 수행하고 시정조치를 하여야 한다.

④ 제1항에 따른 사용자는 방사선 사용시설에서 이행하는 의료피폭의 정당화와 최적화에 대하여 원자력안전위원회가 정하여 고시하는 바에 따라 주기적으로 검토하여야 하며 의료피폭 기록을 유지하여야 한다.

###### 제52조 (의료방사선 품질관리)

① 진료의 목적으로 방사성동위원소등을 인체에 사용하는 자는 환자의 피폭방사선량 또는 투여 방사능량을 의사의 처방대로 유지하여야 한다.

② 제1항에 따른 사용자는 원자력안전위원회가 고시하는 바에 따라 방사선 진료장비를 유지ㆍ관리하여야 하며, 방사선안전관리자와 별도로 의료방사선 품질관리를 위한 전문인력을 두어야 한다.

###### 제53조 (방사성동위원소 투여환자 안전관리)

① 진료의 목적으로 방사성동위원소를 인체에 사용하는 자는 체내에 잔류하는 방사능 또는 인체표면 1m 거리에서의 방사선량률이 원자력안전위원회가 정하여 고시하는 수량을 초과하는 환자를 일반환자와 격리하여 입원시켜야 한다.

② 제1항에 따른 사용자는 환자의 입원실에 전용 화장실을 설치하여야 한다.

③ 제1항에 따른 사용자가 진료환자의 배설물을 배출하는 경우에는 원자력안전위원회가 정하여 고시하는 방법에 따라야 한다.

###### 제54조 (임신 또는 모유 수유중인 여성)

진료의 목적으로 방사성동위원소등을 인체에 사용하는 자는 방사선 진료를 받는 여성 환자가 임신했거나 임신 했을 가능성이 있는 경우, 또는 모유 수유중인 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 적합한 방사선방호 절차를 수립하여 이행하여야 한다.

#### 의료분야의 방사선안전관리에 관한 기술기준

\[시행 2024. 12. 31.\] \[원자력안전위원회고시 제2024-13호, 2024. 12. 31., 타법개정\]

###### 제1조(목적)

이 기준은 「원자력안전법」 제55조제1항제1호 및 「원자력안전법」 제59조제1항제1호ㆍ제2호, 「방사선 안전관리 등의 기술기준에 관한 규칙」 제50조부터 제54조까지의 규정에 따른 의료분야의 방사선안전관리에 필요한 사항을 규정함을 목적으로 한다.

###### 제2조(적용범위)

이 기준은 의료분야에서 다음 각 호의 어느 하나에 해당하는 방사성동위원소등의 취급과 이와 관련된 장비 및 시설에 대하여 적용한다.

1.  방사선발생장치

2.  밀봉된 방사성동위원소(이하 "밀봉선원"이라 한다)

3.  밀봉선원이 내장된 기기

4.  밀봉되지 아니한 방사성동위원소(이하 "개봉선원"이라 한다)

###### 제3조(정의)

이 기준에서 사용하는 용어의 뜻은 다음과 같다.

1.  "방사선 진료장비"란 방사선을 이용하여 질병을 치료하는 데에 사용하는 방사선기기(이하 ‘치료용 방사선기기’라 한다)로서 다음 각 목의 어느 하나에 해당하는 장치를 말한다.

가. 의료용 가속장치

나. 의료용 방사성동위원소 치료장치

2.  "의료용 가속장치"란 가속된 전자선 또는 이 전자가 금속 표적과 충돌할 때 방출하는 고에너지 X선이나 가속된 입자빔을 치료목적으로 사용하는 기기로서 다음 각 목의 어느 하나에 해당하는 장치를 말한다.

가. 선형가속기

나. 사이버나이프

다. 토모테라피

라. 양성자 치료장치

마. 중입자 치료장치

3.  "의료용 방사성동위원소 치료장치"란 방사성동위원소에서 발생되는 방사선을 이용하여 종양을 치료하는 장치로서 다음 각 목의 어느 하나에 해당하는 장치를 말한다.

가. Co-60 치료장치

나. Ir-192 치료장치

다. 감마나이프

###### 제4조(적용대상)

「방사선 안전관리 등의 기술기준에 관한 규칙」(이하 "방사선규칙"이라 한다) 제52조제2항에 따라 진료의 목적으로 방사성동위원소 및 방사선발생장치를 인체에 사용하는 시설ㆍ기기ㆍ방사성 의약품 등의 유지ㆍ관리에 관한 사항은 제5조부터 제15조까지의 규정을 적용한다.

###### 제5조(품질관리)

① 의료기관은 방사선규칙 제52조제1항에 따라 환자의 피폭선량이 의사의 처방대로 유지됨을 확인하기 위하여 문서화된 품질관리 절차를 수립하고, 이에 따른 품질관리를 수행하여야 한다.

② 제1항에 따른 품질관리 절차서는 다음 각 호의 사항이 포함되어야 한다.

1.  품질관리 조직 및 직무

2.  품질관리에 필요한 장비

3.  품질관리 항목에 대한 품질관리 방법, 주기, 관리오차 및 관리오차 초과 시 조치방법

4.  치료용 방사선기기의 선량 교정 및 평가

5.  방사선규칙 제52조제1항에 따른 환자의 피폭방사선량을 의사의 처방대로 유지하기 위한 치료계획 수립 및 점검방법

6.  방사선규칙 제52조제2항에 따른 의료방사선품질관리 전문인력(이하 "전문인력"이라 한다)의 교육 및 훈련

7.  외부기관에 의한 독립적인 품질감사

③ 제2항제3호의 규정에 의한 품질관리 항목, 관리 주기 및 관리 오차는 별표 1을 참조하여 수립한다.

④ 의료기관은 제1항에 따른 품질관리를 제2항제3호의 규정에 따라 수행하고 그 결과를 문서로 비치하여야 한다.

⑤ 의료기관은 제1항에 따른 품질관리 결과 관리오차를 초과하는 항목이 있을 경우 원인 파악 및 시정조치를 하여야 하며, 이를 기록 및 비치하여야 한다.

⑥ 의료기관은 제2항제7호의 규정에 따라 매3년 마다 외부기관에 의한 독립적인 품질감사를 수행하고 그 결과를 비치하여야 한다.

⑦ 원자력안전위원회는 필요한 경우 6인 이하로 별도의 품질감사팀을 구성하여 품질감사를 수행하게 할 수 있다.

⑧ 제7항에 따라 품질감사를 수행한 때마다 품질감사팀은 수행 결과를 원자력안전위원회에 보고하여야 한다.

⑨ 의료기관은 치료용 방사선기기별로 환자별 조사내역을 확인할 수 있는 기록체계를 갖추어야 한다.

###### 제6조(취급절차서)

의료기관은 치료용 방사선기기에 대한 국문 취급절차서를 구비하여야 한다.

###### 제7조(방사선기기 안전요건)

치료용 방사선기기 중 밀봉선원이 내장된 장비의 안전요건은 다음 각 호와 같다.

1.  전원의 공급이 중단되는 경우, 자동으로 방사선원이 차폐되고 제어판으로부터 빔 제어 기능이 재 작동될 때까지 차폐된 상태로 유지되어야 한다.

2.  비정상 상황 시 방사선 조사를 중단시키는 독립된 장치를 둘 이상 갖추어야 한다.

3.  밀봉선원이 장착된 치료실에는 연속적으로 방사선량을 감시하는 장치를 설치하여 종사자가 선원의 상태를 알 수 있도록 하여야 한다.

4.  삭제

5.  방사선 치료를 위해 치료실 내부에 치료받는 자 외의 사람이 남아 있는지를 외부에서 확인할 수 있도록 하여야 한다.

###### 제8조(방사선량 교정)

의료기관은 치료용 방사선기기에 대한 방사선량교정 및 평가를 다음 각 호에 따라 수행하여야 한다.

1.  해당 방사선 기기의 방사선량교정에 적합한 측정장비 및 방사성동위원소를 준비하여야 한다.

2.  국제원자력기구 기술보고서 또는 이와 동등한 기술기준 및 해당 방사선 기기의 제작사가 권고한 조건에 따라 방사선량을 교정하여야 한다.

3.  치료용 방사선기기에 대한 선량 교정 및 평가주기는 다음 각 목의 어느 하나와 같다.

가. 장비를 설치하고 처음으로 사용할 때

나. 처음으로 사용한 이후 매 1년마다

다. 삭제

라. 방사선원을 교체하거나 새로운 시설로 이전한 경우

마. 선량평가에 영향을 미칠 수 있는 보수를 한 경우

바. 1년 이상 사용을 중지 한 후 다시 사용하려는 경우

###### 제9조(의료방사선 품질관리 인력 등)

① 의료기관은 방사선규칙 제52조제2항에 따라 의료방사선 품질관리를 수행할 전문인력을 정하여 별지 제1호서식에 따라 위원회에 제출하여야 한다. 보고 한 사항을 변경한 때에는 변경 후 30일 이내에 별지 제1호서식에 따라 위원회에 제출하여야 한다.

② 제1항에서 정하는 전문인력은 제5조제1항의 규정에 따른 품질관리를 수행할 수 있는 역량을 지닌 자로서 방사선진료전문의의 지시ㆍ 감독을 받아 직무를 수행하되 다음과 같은 책임 및 권한을 갖는다.

1.  치료용 방사선기기의 품질관리

2.  치료용 방사선기기와 품질관리에 사용하는 방사선 측정장비의 교정

3.  환자의 피폭방사선량을 의사의 처방대로 유지하기 위한 치료계획 수립 및 확인

###### 제10조(교정장비)

① 제8조에 따른 교정에 사용하는 장비는 「국가표준기본법」에 의해 국가교정기관으로 지정된 기관에서 정하는 바에 따라 교정을 받아야 한다.

② 제1항에 따라 교정 받아야 하는 측정장비는 다음과 같다.

1.  전리함

2.  온도계 및 기압계

3.  그 외 교정이 필요한 장비

###### 제11조(환자방호)

① 방사선 규칙 제51조제2항에 따라 방사성동위원소 등을 인체에 사용하는 자는 치료 전에 해당 환자 또는 보호자에게 방사선치료의 개요와 예상 이득, 잠재적 위험 등을 설명하고 서면으로 이해동의를 받아야 한다.

② 제1항에 따른 사용자는 의사 및 전문인력의 교육훈련, 선량 상호 교차 평가, 치료용 방사선 기기 품질관리, 제5조제2항제7호에 따른 외부 독립적인 품질감사 등의 프로그램을 통해 환자 방호대책을 수립하여야 한다.

###### 제12조(진료환자의 격리 및 퇴원 기준)

① 방사선규칙 제53조제1항에서 원자력안전위원회가 정하여 고시하는 수량이란 다음 각 호의 하나와 같다.

1.  환자 체내에 잔류하는 방사성동위원소의 방사능은 별표 2의 1란

2.  환자 신체 표면으로부터 1m 거리에서 최대 방사선량률은 별표 2의 2란

3.  환자 퇴원 후 요양 계획 및 주변 환경을 면밀히 고려하여 환자의 가족이나 친지 등이 받는 개인의 유효선량이 5mSv를 초과하지 않도록 한다.

② 치료의 목적으로 방사성동위원소를 인체에 사용하는 자는 환자의 퇴원으로 인하여 방사선에 의해 영향을 받을 수 있는 다른 개인의 유효선량을 합리적으로 가능한 낮게 유지하도록 하기 위하여 퇴원 후 주의사항이 기재된 지침(이하 "지침서"라 한다)을 제공하여야 한다.

③ 제2항에 따른 지침서는 다음 각 호의 사항을 포함하여야 하며, 특히 가정 내에 수유중인 유아(乳兒) 또는 어린이가 있거나 치료를 받고 퇴원하는 환자가 가정 이외의 장소에 머무르는 경우, 퇴원한 환자 이외의 다른 개인의 유효선량이 시행령 별표 1의 일반인 선량한도를 초과할 가능성이 있을 때, 환자가 지켜야 할 사항을 강조한 특정 내용을 추가하여야 한다.

1.  방사성동위원소 투여량에 따른 환자와의 접촉 제한과 접촉시간 최소화

2.  방사성동위원소 투여 환자 특정 장소로의 군집 제한

3.  환자의 배설물 등으로 인한 오염의 최소화

4.  모유 수유 또는 임신 계획에 대한 주의사항 및 방사선에 의한 영향

5.  항공 이용 시 X-선 검색 주의사항

6.  전리방사선 영향에 대한 정보

7.  추가 질문이 있는 경우 연락 가능한 담당자의 성명 및 연락처

###### 제13조(진료환자의 배설물)

방사선규칙 제53조제3항에 따라 진료환자의 배설물을 배출하는 경우에는 배출액 중의 방사성동위원소의 농도가 원자력안전위원회고시 「방사선방호 등에 관한 기준」 제6조의 배출관리기준을 초과하여서는 아니 된다.

###### 제14조(임신 또는 모유 수유 중인 여성에 대한 방호 절차)

방사선규칙 제54조에 따라 의료기관은 다음 각 호의 사항을 포함하여 적합한 방사선 방호 절차를 수립하여 이행하여야 한다.

1.  배태아에게 영향을 줄 수 있는 방사선 치료를 수행하기 전 가임여성의 임신여부 확인

2.  방사성동위원소를 투여하는 치료를 수행하기 전 여성의 모유수유 확인

3.  임신 가능성이 있거나 임신 또는 모유 수유중인 환자가 의료진에게 이 사실을 알리도록 안내하는 절차

###### 제15조(기록의 유지)

방사선규칙 제51조제4항에 따라 의료기관은 별표 3에서 정하는 바에 따라 기록을 작성하고 비치하여야 한다.
