---
title: "사이트사용법"
description: "이 웹사이트 고유의 사용법이 설명되어 있습니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2024-12-20"
date-modified: last-modified
categories: [사용법]
---

### version 0.3.0 개정사항 (2025-05-28 release)

1.  정기검사 수검준비 하부의 수검가이드라인 메뉴
    -   정기검사 수검준비 하부의 수검가이드라인 메뉴에 목차를 추가했습니다.
    -   2022년 자료이므로 이후 관련 법령ㆍ규칙ㆍ고시가 개정된 경우는 개정된 내용을 반드시 참고해야 함을 명시했습니다.
2.  법령규칙고시를 삭제했습니다.
    -   웹사이트 운영과 관련하여 법령규칙고시가 개정될 때마다 이를 반영하는 것이 현재의 인력과 예산으로는 무리라는 자체 판단으로 이번 개정부터는 삭제하였습니다.
3.  안전관리자 업무를 원자력안전법에 따른 수행업무로 구분하고 안전관리규정 작성지침과 기술기준 중 의료와 관련된 부분을 참고하도록 하였습니다.
4.  안전관리자의 업무요약을 새로이 만들었고, 여기에 방사선안전관리규정 예시로 일단은 질병관리청 예시를 첨부하였고 향후 회원병원들 중에서 바람직한 예시가 첨부가능하다면 첨부하고자 합니다. 웹

### version 0.2.0 개정사항 (2025-05-07 release)

-   [https://radiationsafetynm.github.io/website_v0.2.0_2025.05.07/](https://radiationsafetynm.github.io/webiste_v0.2.0_2025.05.07/){target="_blank"}

1.  웹페이지 우측 상단에 버전이 표시되도록 하여 지난 버전과 비교시 약간 용이하도록 하였습니다.

    1)  클릭하면 웹페이지 폴더가 보이나 현재는 필요없는 기능이므로 무시하시면 됩니다.

2.  사이트사용법에서 이번버전에 대한 링크가 있습니다.

    1)  자세히 비교하기를 원하는 경우에는 이전버전과 현재버전을 동시에 띄우고 비교하면 편리합니다.

3.  법령규칙고시

    1)  원자력안전법 시행일이 2025.4.23으로 변경되었습니다.

    -   원자력안전법 사이드메뉴에서 선택 시 시행일 표시를 2025.4.23으로 변경했습니다.
    -   PUBLISHED 2025.1.24 -\> 2025.4.23 으로 변경했습니다. (PUBLISHED는 메뉴마다 의미가 다른데 여기서는 시행일로 약속한다고 사이트사용법에 설명되어 있습니다.)
    -   MODIFIED 2025.1.24 -\> 2025.4.23 으로 변경했습니다. (MODIFIED는 메뉴마다 의미가 다른데 여기서는 시행일로 약속한다고 사이트사용법에 설명되어 있습니다.)
    -   제91조(방사선장해바지조치) 및 제106조 (교육훈련)은 지나번에는 시행일이 2025.4.23일이었기 때문에 그때 당시로는 예정이었지만 이제는 발효가 되었습니다. 따라서 시행예정이었을 때는 파란색배경에 수정사항이 붉은글씨였는데 이제는 다른 조와 같은 배경이면서 수정사항도 일반적인 검은색으로 표시되었습니다.

    2)  원자력안전법 시행령 시행일 2025.4.23으로 변경되었습니다. PUBLISHED/MODIFIED 이하 동문

    -   법령웹사이트 신구법비교 기능을 이용해보면 개정내용을 쉽게 비교할 수 있는데, 우리웹사이트에 올려둔 조항은 아래와 같으며, 개정된 내용을 반영함. 나머지들은 이전에도 아직 웹사이트에 올려두지 않았고 이번에도 시간이 부족해서 올리지 못햇음, 다음 기회에 올릴 때, 개정된 내용을 올릴 예정임.
    -   제131조(측정)
    -   제133조(피폭관리) - 제148조(방사선작업종사자 및 수시출입자 교육)

    3)  의료분야의 방사선안전관리에 관한 기술기준

    -   시행일이 2024.12.31로 변경되었음. PUBLISHED/MODIFIED 이하 동문
    -   신구법비교를 해보면 아래의 개정이 있어 반영함 - 제7조(방사선기기 안전요건)
    -   제8조(방사선량 교정) - 제10조(교정장비) (이상하게도 이미 수정이 되어 있었음)

    4)  방사선방호 등에 관한 기준

    -   시행일이 2025.4.23로 변경되었음. PUBLISHED/MODIFIED 이하 동문
    -   이전버전에 올린 내용이 별로 없고 개정이 없어 추가 수정은 없는 상태

    5)  질병관리청 방사선안전관리규정

    -   시행일이 2025.3.19로 변경되었음. PUBLISHED/MODIFIED 이하 동문
    -   신구법비교를 해보면 아래의 개정이 있어 반영함 - 제11조(폐기기준)

### 이전버전

-   교육팀에서 웹페이지를 검토를 할 때 이전 버전과 비교할 때를 대비하여 이전 버전의 웹사이트를 만들었습니다. 아래의 링크를 이용하시면 됩니다.

    -   version 0.1.0 (2025년2월24일 release) [https://radiationsafetynm.github.io/website_v0.1.0_2025.02.24/](https://radiationsafetynm.github.io/website_v0.1.0_2025.02.24/){target="_blank"}

### 날짜의 의미

-   각 웹페이지는 두 가지 날짜가 있으며 이 웹사이트에서는 구별되어 사용되고 있습니다.
    -   PUBLISHED는 최초작성일에 해당하는 개념입니다.
        -   블로그에서 Date-Oldest, Date-Newest 정렬(Order By)할 때 기준으로 사용됩니다.
    -   MODIFIED는 최종수정일에 해당하는 개념입니다.
        -   블로그에서 Default로 정렬할 때 기준으로 사용됩니다.
        -   Default로 정렬할 때 내부적으로 MODIFIED 날짜의 최신순으로 되지만, 정렬된 페이지목록에서 각 페이지의 왼쪽의 보여지는 날짜는 MODIFIED가 아닌 PUBLISHED를 보여줍니다. 이로인해 Defalut 정렬에서 각 페이지의 날짜와 정렬이 맞지 않는 것처럼 착각될 수 있으므로 주의를 요합니다.
-   법령·규칙·고시의 경우는 PUBLISHED 및 MODIFIED 모두 해당법령의 시행일로 설정해 두었습니다.
-   규제개선 제안사항에서처럼 공문발송일이 있는 경우는 PUBLISHED 및 MODIFIED 모두 공문발송일로 설정해 두었습니다.

### 링크

-   웹페이지에서 어떤 단어들은 파란색이며 밑줄이 있습니다. 마우스로 클릭하면 해당되는 웹페이지 특정목차로 새로운창이 열립니다.

### 툴팁

-   웹페이지에서 어떤 단어들은 파란색이며 밑줄이 있습니다. 마우스를 위치하면 해당되는 웹페이지 특정내용이 말풍선창으로 보입니다.
-   웹페이지에서 어떤 단어들은 검정색배경에 흰 글씨입니다. 마우스를 위치하면 해당되는 웹페이지 특정내용이 말풍선창으로 보입니다.
-   툴팁기능이 확정되지 않아서 위 두가지 방법이 혼용되고 있는데 조만간 통일할 예정입니다.

### 법령ㆍ규칙ㆍ고시

-   모든 조문을 게시한 것은 아니며, 방사성동위원소 등에 관련된 사항들을 우선 게시하였습니다.
-   이 웹사이트가 모든 조문을 게시할지 아직 방침은 정해지지 않았습니다만, 국가법령사이트와 같이 상하위법이 팝업창이 열리도록 만드는 것은 너무 노동집약적으로 국가법령사이트를 직접 이용하는 것이 좋을 것이라 생각하고 있습니다.
-   그럼에도 불구하고 방사성동위원소 등에 관련된 사항들을 우선 게시한 것은 이 웹사이트 내에서 해당조문으로 링크를 만들수 있기 때문이며, 검색이 가능해지기 때문입니다.

### 댓글

-   댓글 기능은 guthub에 가입해야 가능합니다.
-   아직 개발중인 기능이라 웹페이지가 갱신될 때 기존 댓글이 사라질 수 있으니 알파/베타 테스터 분들의 양해를 바랍니다.
