---
title: "기술기준"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 기술기준]
---

기술기준과 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제59조 기준준수의무 등

::: {.callout-note title="제59조(기준준수의무 등)" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 다음 사항에 관하여 위원회규칙으로 정하는 기술기준을 준수하여야 한다.

1.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설ㆍ사용시설등의 위치ㆍ구조 및 설비

2.  방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ보관ㆍ처리 및 배출

3.  방사성동위원소등의 이동사용 및 판매

② 위원회는 사업소 안에서의 방사성동위원소 또는 그에 따라 오염된 물질이나 방사선발생장치의 생산시설 또는 사용시설등의 위치ㆍ구조 및 설비, 사업소 안에서의 생산ㆍ사용ㆍ분배ㆍ저장ㆍ운반ㆍ처리 및 배출과 방사성동위원소등의 이동사용이나 판매가 제1항에 따른 기술기준에 적합하지 아니하다고 인정하면 허가사용자 및 신고사용자에게 해당 시설의 수리ㆍ개선ㆍ이전 또는 생산ㆍ사용의 정지, 취급방법의 변경과 그 밖의 안전에 필요한 조치를 명할 수 있다.

③ 허가사용자 및 그 종업원은 제53조제3항에 따른 안전관리규정을 준수하여야 하며, 업무대행자와 그 종업원은 제54조제3항에 따른 업무대행규정을 준수하여야 한다.
:::

## 방사선 안전관리 등의 기술기준에 관한 규칙

### 제3조 방사선관리구역

::: {.callout-note title="제3조 (방사선관리구역)" collapse="open" appearance="minimal"}
① 법 제2조제16호에서 "원자력안전위원회규칙으로 정하는 값"이라 함은 다음 각호와 같다.

1.  외부방사선량률 : 1주당 400마이크로시버트

2.  공기중의 방사성물질의 농도 : 유도공기중농도

3.  물체표면의 오염도 : 허용표면오염도

② 외부방사선량률 등이 제1항의 규정에 의한 값을 초과할 우려가 있는 곳에 대하여는 사람의 출입을 관리하고 출입자에 대한 방사선의 장해를 방지하기 위하여 다음 각호의 조치를 하여야 한다.

1.  방사선관리구역의 설정

2.  벽ㆍ울타리 등의 구획물로 구획하여 별표 1에 의한 표지를 부착함으로써 다른 장소와 구별하고 방사선작업종사자외의 사람이 당해 구역에 출입하는 경우에는 방사선작업종사자의 지시에 따르도록 할 것

3.  바닥ㆍ벽 기타 사람이 접촉할 우려가 있는 물체의 표면이 방사성물질에 오염된 경우 그 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  방사선관리구역으로부터 사람이 퇴거하거나 물품을 반출하는 경우에는 인체 및 의복ㆍ신발 등 인체에 착용하고 있는 물품과 반출하는 물품(그 물품이 용기에 들어있거나 포장한 경우에는 그 용기 또는 포장)표면의 방사성물질의 오염도가 허용표면오염도의 10분의 1을 초과하지 아니하도록 할 것\
:::

### 제37조 사용 및 분배

::: {.callout-note title="제37조(사용 및 분배)" collapse="open" appearance="minimal"}
개봉선원의 사용 또는 분배에 관한 기술기준은 다음 각호와 같다.

1.  사용시설 또는 작업실에서 사용ㆍ분배할 것

2.  다음 각목에 해당하는 조치를 함으로써 방사선작업종사자 또는 수시 출입자의 피폭방사선량이 선량한도를 초과하지 아니하도록 할 것

           가.
차폐벽이나 차폐물에 의하여 방사선을 차폐할 것

           나.
원격조작장치ㆍ집게 등을 사용하여 개봉선원과 인체 사이에 적당한 거리를 확보하고 차폐물을 이용하도록 할 것

           다.
면밀한 작업계획 및 숙달ㆍ훈련 등을 통하여 인체에 방사선이 피폭되는 시간을 단축할 것

3.  작업실안의 사람이 상시 출입하는 장소에서 사람이 호흡하는 공기중 방사성동위원소의 농도는 방사성동위원소에 의하여 오염된 공기를 정화하거나 배기함으로써 유도공기중농도를 초과하지 아니하도록 할 것

4.  작업실 또는 오염검사실안의 사람이 접촉하는 물건표면의 방사성동위원소의 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

5.  작업실안에서는 작업복ㆍ신발ㆍ보호구 등을 착용하되, 이를 착용한 채 작업실을 나가지 아니하도록 할 것

6.  작업실을 나갈 때에는 인체 및 작업복ㆍ신발ㆍ보호구 등 인체에 착용하고 있는 물건표면에 대하여 방사성동위원소에 의한 오염상태를 검사하고 그 오염을 제거할 것

7.  사용 또는 분배시설에는 눈에 띄기 쉬운 장소에 방사선장해방지에 필요한 주의사항을 게시할 것
:::