---
title: "선량ㆍ오염측정"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 선량ㆍ오염측정]
---

선량ㆍ오염측정과 관련된 법령ㆍ규칙ㆍ고시는 아래와 같습니다.

## 원자력안전법

### 제131조 측정

::: {.callout-note title="제131조(측정)" collapse="open" appearance="minimal"}
① 원자력관계사업자(신고사용자는 제외한다. 이하 이 조, 제132조, 제133조, 제148조 및 제148조의3에서 같다)는 법 제91조제1항제1호에 따라 총리령으로 정하는 방사선장해의 우려가 있는 장소에 대한 방사선량 및 방사성물질등에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16., 2017. 3. 20.>

② 법 제91조제1항제1호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설에 출입하는 사람의 피폭방사선량 및 방사성물질에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16.>

③ 원자력관계사업자는 제1항 및 제2항의 측정 결과에 관하여 기록의 작성, 보존, 그 밖의 총리령으로 정하는 조치를 하여야 한다. <개정 2013. 3. 23.>
:::

## 원자력안전법 시행령

### 제131조 측정

::: {.callout-note title="제131조(측정)" collapse="open" appearance="minimal"}
① 원자력관계사업자(신고사용자는 제외한다. 이하 이 조, 제132조, 제133조, 제148조 및 제148조의3에서 같다)는 법 제91조제1항제1호에 따라 총리령으로 정하는 방사선장해의 우려가 있는 장소에 대한 방사선량 및 방사성물질등에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16., 2017. 3. 20.>

② 법 제91조제1항제1호에 따라 원자력관계사업자는 총리령으로 정하는 바에 따라 원자력이용시설에 출입하는 사람의 피폭방사선량 및 방사성물질에 의한 오염상황을 측정하여야 한다. <개정 2013. 3. 23., 2013. 8. 16.>

③ 원자력관계사업자는 제1항 및 제2항의 측정 결과에 관하여 기록의 작성, 보존, 그 밖의 총리령으로 정하는 조치를 하여야 한다. <개정 2013. 3. 23.>
:::

## 원자력안전법 시행규칙

### 제120조 즉정장소 및 측정대상

::: {.callout-note title="제120조(측정장소 및 측정대상)" collapse="open" appearance="minimal"}
① 영 제131조제1항에서 “총리령으로 정하는 방사선장해우려가 있는 장소”란 다음 각 호의 장소를 말한다. <개정 2014. 11. 24.>

1. 방사선량의 경우

가. 사용ㆍ분배ㆍ저장 및 폐기시설

나. 고정된 방사선차폐시설 안에 있는 밀봉된 방사성동위원소 또는 방사선발생장치

다. 방사성폐기물의 저장ㆍ처리 및 처분시설

라. 방사선관리구역

마. 비정상적으로 방사성물질이 누출된 장소

2. 방사성물질등에 따른 오염상황의 경우

가. 방사선관리구역에 있어서 공기 중의 방사성물질농도와 오염되거나 오염의 우려가 있는 물체의 표면

나. 방사선관리구역으로부터 반출하는 물품의 표면

다. 배기구 또는 배수구

라. 비정상적으로 방사성물질이 누출된 장소

② 영 제131조제2항에 따른 피폭방사선량 및 방사성물질등에 따른 오염상황의 측정대상은 다음 각 호와 같다. <개정 2014. 11. 24.>

1. 피폭방사선량의 경우

가. 방사선작업종사자

나. 수시출입자

다. 방사선관리시설에 일시적으로 출입하는 자로서 선량한도를 초과하여 피폭될 우려가 있는 자

2. 방사성물질에 따른 오염상황의 경우

가. 방사선작업종사자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는 부위의 표면

나. 수시출입자의 손ㆍ발ㆍ작업복ㆍ보호구 그 밖에 오염의 우려가 있는 부위의 표면

③ 제1항 및 제2항에 따른 측정장소 및 측정대상에 대한 측정방법은 다음 각 호와 같다.

1. 방사선량 및 오염상황은 방사선측정에 가장 적합한 장소에서 측정할 것

2. 방사선에 따른 인체내부의 피폭은 공기 중 또는 음료수 중의 방사성물질의 농도 및 양을 측정하거나 필요한 정밀검사를 통하여 산출할 것
:::