---
title: "영상품질·선량최적화"
description:  "핵의학 영상품질과 선량최적화를 위한 사이트입니다.<br> Consensus 및 정리가 필요하므로 최적화팀만 참고하시길 바랍니다."
author: "대한핵의학회<br>방사선안전위원회"
date: "2025-02-14"
date-modified: "2025-02-14"
categories: [영상품질, 선량, 최적화]
bibliography: references.bib
---

핵의학영상검사가 양질의 의료서비스를 제공하기 위해서는 진단목적으로 충분한 영상품질의 담보와 합리적선량저검화가 필요합니다.

방사선방호최적화를 위해서 진단참고수준을 사용함에 있어 DRL을 사용하고 있으나, DRL은 영상품질을 의미하는 지표는 아닙니다. DRL은 방사선양을 제한하는 것이 목적이며, 영상품질을 평가하는 것이 아니라고 ICRP도 분명하게 밝히고 있습니다. 영상품질이 부적절할 정도로 방사선양이 낮은 것은 방사선양 과잉과 마찬가지로 허용할 수 없습니다.

따라서 의료의질 측면에서는 DRL을 통해서 영상품질과 선량최적화를 반드시 동시에 고려해야 합니다. 국가의 장기계획으로써는 더욱 그러합니다 (국책사업의 경우 전문가들이 신뢰할 수 있도록 정책을 펼친다면 해당분야의 발전이 빨라질 것으로 기대하고, 전문가들이 납득하기 어려운 부분을 굳이 강행하면 실효성이 낮아질 것이다 우려됩니다).

### 기존의 문제점.

진단참고수준 이하의 투여율을 의료의질 평가지표로 선정하고 있습니다. 이는 다음과 같은 문제들이 파생될 것으로 우려되고 이러한 우려는 문헌에서 보고된 바 있습니다.

1\. 방사성의약품 투여량을 진단참고수준 바로 아래의 값으로 변경해 버리게 됩니다. (물론 바람직하게 최신 고가의 스캐너로 변경하는 병원도 있겠지만, 영상품질평가없이 영상품질의 저하는 미미할 것이라 판단하면서 간편하게 투여량은 진단참고수준 바로 아래의 값으로 변경해 버리게 됩니다. 왜냐하면 의료의질 평가 자체에는 영상의품질은 전혀 언급하지도 않았고 투여량만 조사하는데, 병원의 적자는 늘어어만 나는 현실에서는 품질이 더이상 1순위가 되지 않을 수 있습니다. 하지만 약간씩의 투여량 저하도 영상의 품질저하가 될 수 있고, 특히 반복되게 되면 반드시 영상품질저하로 이어지게 됩니다).

2\. 질 가산금이 지급되는 경우에는 더욱 그러하리라 예상됩니다.

### 대안

영상품질평가와 연계되어 방사성의약품 투여량 프로토콜이 개선되도록 해야 합니다.

1.  영상품질평가 시스템 운영

    -   영상품질 Reference image 제작: torso PET/CT 영상의 경우 List mode로 영상획득이 가능하며, 충분한 시간동안 획득한 양질의 영상을 원하는 영상획득시간으로 분할하면 영상을 재구성할 수 있습니다. @hu2022 여러 영상획득시간 중 임상적목적을 달성가능한 최소시간의 영상이 선택될 수 있고, 이러한 영상들로부터 영상품질의 반영하는 파라미터들이 파생되므로 실무적으로 이를 이용하도록 하면됩니다.

    -   이미 문헌에서 많이 보고되고 있는 지표들 중 가장 간편한 지표는 대표적으로 liver SNR이 있습니다.

    -   이러한 영상품질 reference image는 스캐너마다 존재해야 하며, 처음 스캐너 설치시에 샘플환자들을 대상으로 만들어지기도 합니다.

    -   만약에 없다면 언제든지 만들면 됩니다.

2.  영상획득 프로토콜의 관리

    -   영상획득 프로토콜별로 위의 영상품질 reference image와 비교하여 임상적인 목적달성이 가능한 영상인지 확인해야 합니다.

    -   예시로 digital PET/CT의 등장으로 영상의 품질이 향상될 수 있습니다만, 이를 방사성의약품 투여량을 줄이지 않고, 검사시간을 단축할 수도 있습니다. 기관별로 커스터마이징하여 검사 프로토콜을 결정하고 있기 때문입니다.

    -   영상획득 프로토콜을 관리한다는 것은 1번의 영상품질평가 시스템으로 만든 reference image의 임상적 목적달성에 충분한 영상품질단계 이상임을 확인해야 한다는 것입니다.

    -   또한 기록이 남아야 합니다.

3.  선량평가위원회

    -   검사프로토콜의 만들어지거나 변경이 될 때, 선량평가위원회에서 이를 평가하는 것이 타당합니다. 핵의학과 의사만이 아니라 PET/CT 검사를 많이 의뢰하는 임상의사가 포함되는 것이 바람직합니다.

따라서 요약하자면, 선량평가위원회에서 reference image (및 liver SNR과 같은 객관적 정량적 영상품질지표)를 통해서 해당 프로토콜의 영상품질이 임상적목적에 부합하는 것인지 승인되어야 하고, 승인된 프로토콜을 사용하여 획득된 기관의 값이 DRL 이하여야 합니다. 두가지 모두 만족하면 질가산금이 주어지도록 해야 합니다. (비록 어렵기는 하지만 ICRP에서 권고하는 방법이므로 장기적으로는 핵의학계의 발전에 도움이 된다고 생각됩니다).

예시에서는 digital PET/CT를 다루었지만, 구형 스캐너를 이용하는 경우에는 방사성의약품 투여량을 줄이고 스캔타임을 늘려서 최적화를 할 수도 있습니다. 이 경우는 영상품질이 보존되지만 검사시간이 길어져 병원수익은 감소하지만 질가산금이 당근책이 될 것입니다.

선량평가위원회의 활동은 대한핵의학회에서도 검토할 예정이므로 영상의 품질이 고려되지 않고, 단순히 투여량만 줄인다면 이는 영상품질을 적절히 평가한 후 투여량을 조정하도록 권고할 수 있다.

#### ICRP 135 인용이 필요한 부분들

(117) 표본조사에서 DRL값을 도출하기 위하여 선량계측 데이터를 단순히 한 통에 넣는 것은 더 이상 전혀 만족스럽지 않은데, 이는 진정한 최적화가 아니라 단지 DRL 바로 아래에 선량 표본조사 결과 값을 밀집시키는 것일 수도 있다(Sutton 등, 2014). 방사선방호의 최적화를 통해 요구하는 수준의 영상품질을 확보하기 위해서는 보다 적극적인 접근이 필요하다. 두 번째 단계 즉, DRL값을 결정하는 데 사용되는 분포의 중앙값은 최적화를 돕는 추가 도구로 사용할 수 있다. DRL값은 제3 사분위수이므로 최적화 작업이 계속 진행됨에 따라 중앙값이 모범관행을 판단할 수 있는 보다 좋은 지침을 제공할 수 있다. 중앙값은 DRL값과 함께 영상품질과 환자선량의 최적화를 돕는 데 사용될 수 있다.

2.7. 영상품질

(126) 방호최적화를 달성하는 방법에 대해 의학물리사, 영상의학자 및 방사선사의 논의에서 가장 빈번하게 사용되는 접근법은 검사의 DRL값을 준수하는 것이다. 그러나 DRL양은 영상품질의 서술자descriptor가 아니다. 한 보건센터에서 DRL양의 중앙값이 특정 값보다 높거나 낮은 것이 영상이 특정 임상목적에 적절하거나 부적 절하다는 것을 나타내지는 않는다. 영상품질 평가를 국가 DRL값의 준수로 대체하는 것은 적절하지 않다.

(127) 진단촬영 검사의 최우선 순위는 임상목적에 충분한 영상품질을 얻는 것이므로, 모든 절차의 영상이 필요한 모든 진단정보를 제공하고 임상목적이 위태롭게 되지 않도록 하는 것이다. 이것은 모든 영상이 고품질임을 의미하지는 않는다. 일부기기(예: 형광투시)에서는 개별적으로 낮은 품질을 가진 일련의 영상들도 합쳐서 필요한 임상 정보를 제공할 수 있다.

(128) 영상품질이 부적절할 정도로 방사선 양이 낮은 것은 방사선 양 과잉과 마찬가지로 허용할 수 없다. 영상품질이 임상목적에 적합하지 않은 경우, 방사선은 임상적 이득을 제공하지 않으므로 검사가 반복되고, 환자는 반복 검사로 추가 방사선을 받는다. 데이터가 임상 현장에서 환자 표본조사로 수집되므로 DRL양에 관한 데이터를 모으면 대부분 영상의학자가 임상목적에 충분한 영상을 생성하는 방사선양이라고 동의하는 방사선 양에 대한 정보를 얻을 수 있다고 가정하고 있다.

(129) 영상품질 기준 없이 DRL양에만 초점을 맞추면 영상품질이 손상되는 어떤 단계까지 DRL값이 계속 하향 조정될 수 있다. 촬영 프로토콜을 수정할 때는 진단목적에 적합한 영상품질이 확보되도록 하는 것이 중요하다. 따라서 최적화는 영상품질과 환자선량 사이 균형을 맞추어야 한다. 방사선 양이 감소하더라도 영상품질은 적절한 수준으로 유지되어야 한다.

(130) DRL 데이터를 수집하기 전에 표본조사자는 관심 선량계측량의 정확도에 특히 주의를 기울이면서 촬영장비가 적합하게 작동하고 있는지를 적절한 QC 프로그램을 통해 확인하고, 촬영장비가 임상업무에 적절한 품질의 임상 영상을 제공하는지 확인해야 한다. 가능하면 언제나 영상품질을 판단하는 증거기반 기준을 채택해 야 한다. 다양한 촬영업무에 필요한 영상품질 수준에 대한 지침은 한정되어 있다. 지금까지는 영상의학자 평가 형식의 객관적 척도만 사용되고 있다. 유럽위원회는 영상의 진단 잠재력을 판단할 때 영상을 채점하는 데 사용할 수 기준과 함께 지침을 작성했다(EC, 1996a,b, 1999a). 이 기준이나 유사한 기준이 영상품질에 영향을 미칠 수 있는 변경이 있을 때마다 영상품질을 평가하는 데 사용될 수 있다. 임상영상 기준을 사용하여 임상영상을 평가하려면 영상의학자 참여가 필요하다.

(131) 다양한 검사에 적합한 영상품질 변수에 대한 상당한 추가 데이터가 필요하다. 영상대비와 촬영시스템의 성능을 특성화하기 위해 다양한 측정량이 한동안 사용되었다. 이런 측정량은 전문적 측정기술을 필요로 하며 대부분 촬영시스템을 위해서는 제작사가 공급한다. 병원 의학물리사가 이러한 측정을 수행하는 데 사용할 수 있는 기술이 널리 보급되고 있다. 이러한 측정량에는 변조전달함수, 시스템 전달인자 및 잡음출력 스펙트럼이 포함된다(ICRU, 1995). 측정량은 장래의 디지털촬영시스템을 위한 최적화 과정의 일환으로 적절한 영상품질 수준을 선정할 수 있도록 유용한 정보를 의학물리사에게 제공해야 한다. 이러한 정량적 측정은 촬영 검출기의 고유성능은 잘 묘사하지만, 임상 영상품질(임상업무) 측면에서 시스템을 특성화하지는 않는다.

(132) 영상 평가의 객관적 측정에 대한 연구가 수행되었지만, 물리적 측정과 영상의학자 판단 사이의 관계는 아직까지 정립되지 않았다(De Crop 등, 2015). 이 프로세스를 지원하기 위해서는, 주요 변수가 선량만이 아니고 선량 당 영상품질이 되도록 CT 및 기타 전문분야의 허용 가능한 영상품질 수준에 대한 보다 자세한 분 석이 필요하다. 이 분야에 대한 추가 연구와 임상 촬영업무에 연계된 객관적 영상품질 변수의 크기에 대한 추가 데이터가 시급하게 필요하다.53)
