---
title: "보고"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 보고]
---

보고와 관련된 법령규칙고시는 아래와 같습니다.

## 원자력안전법

### 제98조(보고ㆍ검사 등)

::: {.callout-note title="제98조(보고ㆍ검사 등)" style="background-color: #f0f8ff" collapse="open" appearance="minimal"}
① 위원회는 이 법의 시행을 위하여 필요하다고 인정하면 원자력관계사업자ㆍ판독업무자와 원자로 및 관계시설의 건설 또는 운영에 참여하는 사업자와 국제규제물자를 취급하거나 관련 연구를 수행하는 자로서 대통령령으로 정하는 자에게 그 업무에 관한 보고 또는 서류의 제출 및 제출된 서류의 보완을 명할 수 있다.

② 위원회는 제1항에 따라 보고받은 내용 및 제출된 서류의 현장 확인을 위하여 필요한 경우, 원자력이용시설의 안전을 위하여 특히 필요하다고 인정하는 경우 또는 이 법에 따른 각종 검사를 수행하기 위하여 필요하면 소속 공무원으로 하여금 그 사업소ㆍ공장ㆍ선박ㆍ연구시설 또는 부지 등에 출입하여 장부ㆍ서류ㆍ시설과 그 밖의 필요한 물건을 검사하게 하거나 관계인에게 질문하게 할 수 있으며, 시험을 위하여 필요한 최소량의 시료를 수거하게 할 수 있다.

③ 위원회는 제2항에 따라 검사 등을 실시한 결과 이 법과 국제약속을 위반한 사항이 있으면 그 시정 또는 보완을 명할 수 있다.

④ 국제약속에 따라 국제원자력기구가 지정하는 자 또는 국제규제물자공급 당사국 정부가 지정하는 자는 위원회가 지정하는 소속 공무원의 감독하에 국제약속으로 정한 범위에서 국제규제물자를 취급하거나 관련 연구를 수행하는 자의 사업소ㆍ공장ㆍ선박ㆍ연구시설 및 부지 등에 출입하여 장부ㆍ서류ㆍ시설과 그 밖의 필요한 물건을 검사하고, 관계인에게 질문하거나 시험을 위하여 필요한 최소량의 시료를 수거할 수 있다.

⑤ 국제원자력기구가 지정하는 자는 위원회가 지정하는 소속 공무원의 감독하에 국제약속으로 정한 범위에서 국제규제물자의 이동을 감시하기 위한 설비를 설치하거나 봉인을 할 수 있다.

⑥ 위원회는 대통령령으로 정하는 바에 따라 국제규제물자의 이동을 확인하거나 정보를 관리하기 위하여 필요한 조치를 할 수 있다.

⑦ 제2항 및 제4항부터 제6항까지의 규정에 따라 검사하거나 국제규제물자의 이동을 감시ㆍ확인하기 위하여 직무를 수행하는 자는 그 권한을 나타내는 증표를 관계인에게 내보여야 한다.
:::
