---
title: "자체처분"
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-17"
date-modified: "2024-11-17"
categories: [정기검사, 지적사항, 자체처분]
---

자체처분과 관련된 법령규칙고시는 아래와 같음.

## 원자력안전법

### 제70조 방사성폐기물의 처분제한

::: {.callout-note title="제70조(방사성폐기물의 처분제한)" collapse="open" appearance="minimal"}
① 누구든지 방사성폐기물을 해양에 투기(投棄)하는 방법으로 처분할 수 없다.

② 방사성폐기물처분시설등건설ㆍ운영자가 아닌 자는 총리령으로 정하는 종류 및 수량의 방사성폐기물을 땅속에 천층(淺層)처분(동굴처분을 포함한다) 또는 심층(深層)처분 등의 방법으로 처분할 수 없다. <개정 2013. 3. 23., 2015. 1. 20., 2020. 12. 22.>

③ 제2항에 따른 방사성폐기물 외의 방사성폐기물의 처분은 대통령령으로 정하는 방법 및 절차에 적합하게 하여야 한다.

④ 제2항에 따른 방사성폐기물의 처분을 방사성폐기물관리시설등건설ㆍ운영자에게 위탁하려는 자는 총리령으로 정하는 인도(引渡)기준에 적합하게 하여야 한다. <개정 2013. 3. 23., 2015. 1. 20.>
:::

## 원자력안전법 시행령

### 제107조 방사성폐기물 자체처분의 절차 및 방법

::: {.callout-note title="제107조(방사성폐기물 자체처분의 절차 및 방법)" collapse="open" appearance="minimal"}
① 법 제71조에 따른 원자력관계사업자(이하 “원자력관계사업자”라 한다)는 법 제70조제3항에 따라 다음 각 호의 어느 하나에 해당하는 방사성폐기물로서 법 제70조제2항에 따른 방사성폐기물 외의 방사성폐기물임을 위원회로부터 확인을 받은 방사성폐기물을 소각, 매립 또는 재활용 등의 방법으로 처분(이하 “자체처분”이라 한다)할 수 있다. <개정 2014. 9. 11., 2015. 7. 20., 2023. 8. 1.>

1. 원자력관계사업자가 발생시킨 방사성폐기물

2. 원자력관계사업자(방사성폐기물관리시설등건설ㆍ운영자는 제외한다)로부터 처분을 위탁받아 관리하고 있는 방사성폐기물

② 제1항에 따라 자체처분을 하려는 원자력관계사업자는 방사성폐기물을 자체처분할 때마다 총리령으로 정하는 바에 따라 자체처분계획서에 관계 서류를 첨부하여 위원회에 제출하여야 한다. 이를 변경하려는 경우에도 또한 같다. <개정 2013. 3. 23., 2014. 9. 11.>

③ 제2항 전단에도 불구하고 다음 각 호의 기준을 모두 만족하는 방사성폐기물을 자체처분하려는 원자력관계사업자는 제2항에 따른 자체처분계획서를 5년마다 위원회에 제출할 수 있다. <개정 2014. 9. 11., 2020. 5. 26.>

1. 반감기(半減期)가 5일 미만인 핵종만을 포함할 것

2. 위원회가 정하여 고시하는 자체처분 허용기준에 적합할 것

④ 위원회는 제2항 또는 제3항에 따라 제출된 자체처분계획서가 위원회가 정하여 고시하는 자체처분의 방법 및 절차에 적합한지에 대하여 검토하고, 그 결과를 총리령으로 정하는 바에 따라 원자력관계사업자에게 통지해야 한다. <신설 2014. 9. 11., 2023. 8. 1.>

⑤ 제4항에 따라 자체처분계획서가 적합한 것으로 통지받은 원자력관계사업자는 해당 방사성폐기물을 자체처분할 수 있다. <신설 2014. 9. 11.>

⑥ 제5항에 따라 자체처분을 한 자는 자체처분에 관한 기록을 자체처분일부터 5년간 보존하여야 한다. <개정 2014. 9. 11.>

⑦ 원자력관계사업자는 제2항에 따라 자체처분계획서를 제출하기 전에 그 자체처분계획서의 내용 중 핵종별 농도 측정 및 평가 방법에 대하여 총리령으로 정하는 바에 따라 위원회에 사전검토를 신청할 수 있다. <신설 2023. 8. 1.>

⑧ 위원회는 제7항에 따른 신청 내용이 위원회가 정하여 고시하는 자체처분의 방법 및 절차에 적합한지 여부를 검토하고, 그 결과를 총리령으로 정하는 바에 따라 신청인에게 통지해야 한다. <신설 2023. 8. 1.>

⑨ 위원회는 제4항에 따라 자체처분계획서를 검토할 때에는 제8항에 따라 통지한 사전검토 결과를 고려해야 한다. <신설 2023. 8. 1.>
:::

## 원자력안전법 시행규칙

### 제95조 자체처분계획서 및 사전검토 신청서 등

::: {.callout-note title="제95조(자체처분계획서 및 사전검토 신청서 등)" collapse="open" appearance="minimal"}
① 영 제107조제2항에 따른 자체처분계획서는 별지 제84호서식과 같다.

② 제1항의 계획서에는 위원회가 정하여 고시하는 지침에 따라 작성된 다음 각 호의 사항에 관한 서류를 첨부하여야 한다. \<개정 2023. 8. 1.\>

1.  자체처분 대상 방사성폐기물의 종류 및 수량

2.  자체처분 대상 방사성폐기물의 발생원과 발생일시 또는 발생기간

3.  자체처분 대상 방사성폐기물의 종류별 표면방사선량률과 핵종별 농도 및 그 산출근거

4.  자체처분 방법 및 예정 목적지

5.  자체처분으로 인하여 부수적으로 발생하는 폐기물의 수량 및 관리방법

6.  자체처분에 따른 예상 피폭방사선량이 위원회가 정하여 고시하는 자체처분 허용선량을 만족함을 입증하는 자료

7.  자체처분절차

③ 영 제107조제7항에 따른 사전검토 신청서는 별지 제84호의2서식과 같다. \<신설 2023. 8. 1.\>

④ 제3항의 사전검토 신청서에는 위원회가 정하여 고시하는 지침에 따라 작성된 다음 각 호의 사항에 관한 서류를 첨부해야 한다. \<신설 2023. 8. 1.\>

1.  자체처분 대상 방사성폐기물의 종류 및 수량

2.  자체처분 대상 방사성폐기물의 발생원과 발생일시 또는 발생기간

3.  자체처분 대상 방사성폐기물의 핵종별 농도 측정 및 평가 방법

⑤ 한국원자력안전기술원은 영 제107조제2항 또는 제3항에 따라 자체처분계획서를 제출받은 날부터 20일 이내에, 영 제107조제7항에 따라 사전검토를 신청받은 날부터 30일 이내에 그 검토 결과를 원자력관계사업자에게 통지해야 한다. \<신설 2023. 8. 1.\>

\[제목개정 2023. 8. 1.\]
:::

## 방사성폐기물 분류 및 자체처분 기준에 관한 규정

### 제2조(정의)

::: {.callout-note title="제2조(정의)" collapse="open" appearance="minimal"}
이 규정에서 사용하는 용어의 뜻은 다음과 같다.  

1. "자체처분"이란 방사성폐기물 중에서 핵종별 농도가 자체처분 허용농도 미만임이 확인된 것을 「원자력안전법」의 적용대상에서 제외하여 방사성폐기물이 아닌 폐기물로 소각, 매립 또는 재활용 등의 방법으로 관리하는 것을 말한다. 

2. "자체처분 허용농도"란 「원자력안전법 시행규칙」(이하 "규칙"이라 한다) 제94조에 따른 핵종별 농도 미만으로 별표1의 허용농도 또는 자체처분 허용선량을 만족함이 입증되는 농도를 말한다. 

3. 규칙 제95조제2항제6호에서 "위원회가 정하여 고시하는 자체처분 허용선량" 이란 방사성폐기물의 자체처분에 따른 개인에 대한 연간 예상 피폭방사선량이 10 마이크로시버트(μSv) 미만이고 집단에 대한 연간 예상 총피폭방사선량이 1 맨ㆍ시버트(manㆍSv) 미만이 되는 값을 말한다. 

4. "검출목표치"란 방사성폐기물을 자체처분하고자 하는 원자력관계사업자(이하 "자체처분사업자"라 한다)가 자체적으로 설정하는 검출목표 방사능 농도를 말한다. 

5. "최소검출가능농도"란 방사능계측기, 시료량, 회수율, 계측시간 등의 계측조건에 따라 정해지는 검출가능한 최소 방사능 농도를 말한다. 
:::

###  [별표1] 방사성핵종별 자체처분 허용농도별(제2조제2호 관련)

-   [방사성핵종별 자체처분 허용농도별](/archive/[별표 1] 방사성핵종별 자체처분 허용농도(제2조제2호 관련)(방사성폐기물 분류 및 자체처분 기준에 관한 규정).pdf)
