---
title: "방사선안전관리자 업무"
author: "Radiation Safety Committee"
date: "2024-11-27"
modified-date: "2024-11-27"
categories: [방사선안전관리자, 법정업무]
---

## 원자력안전법상의 업무

-   방사선안전관리자의 업무로써 가장 상위법인 원자력안전법상의 기술은 아래와 같습니다.

::: {.callout-note title="원자력안전법 제53조의3(방사선안전관리자) [시행 2024.11.01]" collapse="open" appearance="minimal"}
① 허가사용자 및 신고사용자는 방사선 안전관리에 관한 다음 각 호의 업무를 수행하기 위하여 대통령령으로 정하는 바에 따라 방사선안전관리자를 선임하여 방사성동위원소등의 사용개시 전에 이를 위원회에 신고하여야 한다. 신고한 사항을 변경하려는 때에도 또한 같다.

1.  제53조제3항의 **`안전관리규정`** 및 제59조제1항의 **`기술기준의 준수여부 점검`**

2.  **`방사선작업종사자`** 또는 **`방사선관리구역에 출입하는 자`**에 대한 제91조에 따른 **`방사선장해방지조치`**

3.  **`허가사용자`** 및 **`신고사용자`**에 대한 **`방사선 안전관리에 관한 조치 권고`**

4.  **`그 밖에 방사선 안전관리를 위하여 필요한 조치`**

③ 제1항에 따른 허가를 받으려는 자는 허가신청서에 안전성분석보고서, 품질보증계획서, 방사선안전보고서 및 **`안전관리규정`**과 그 밖에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 하며, 제2항에 따른 신고를 하려는 자는 신고서에 총리령으로 정하는 서류를 첨부하여 위원회에 제출하여야 한다. 다만, 안전성분석보고서 및 품질보증계획서의 제출은 생산허가를 받으려는 자에 한한다. \<개정 2013. 3. 23.\>
:::

### 안전관리규정 내용

-   원자력안전법 제53조제3항에 기술된 안전관리규정에는 원자력안전법 시행규칙 제58조에 따라 다음의 내용들이 포함되어야 합니다.

::: {.callout-note title="원자력안전법 시행규칙 제58조(방사성동위원소등의 생산허가 신청 등) [시행 2024.11.01]" collapse="open" appearance="minimal"}
제58조(방사성동위원소등의 생산허가 신청 등) ⑤ 제2항제4호에 따른 안전관리규정에는 위원회가 정하여 고시하는 작성지침에 따라 다음 각 호의 사항을 적어야 한다. 다만, 허가대상과 관련이 없는 사항은 적지 아니할 수 있다. \<개정 2016. 8. 8.\>\

1.  방사성동위원소등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 **`조직`** 및 그 **`기능`**에 관한 사항\
2.  방사성동위원소등의 **`구매ㆍ사용 및 판매`**에 관한 사항\
3.  방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 **`분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도`**에 관한 사항\
4.  방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질(이하 “**`방사성물질등`**”이라 한다)에 따른 **`오염상황의 측정`** 및 그 측정결과의 **`기록과 보존`**에 관한 사항\
5.  **`방사선안전관리 장비의 보관ㆍ관리 및 교정`**에 관한 사항\
6.  방사선작업종사자 및 수시출입자에 대한 **`피폭방사선량의 평가`** 및 **`개인선량계의 관리`**에 관한 사항\
7.  방사선작업종사자 및 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 **`교육훈련`**에 관한 사항\
8.  방사선장해 **`발생 여부`**를 발견하기 위하여 **`필요한 조치`**에 관한 사항\
9.  방사선장해를 받았거나 받을 우려가 있는 사람에 대하여 필요한 **`보건상 조치`**에 관한 사항\
10. 법 제58조에 따른 기록과 그 비치에 관한 사항\
11. **`위험 시 조치`**에 관한 사항\
12. 방사성동위원소등의 분실ㆍ도난 등 **`사고 시의 조치 및 사고예방`**에 관한 사항\
13. 방사선안전관리자의 **`권한ㆍ책임 및 직무수행`**에 관한 사항\
14. 그 밖에 방사선장해의 방어에 필요한 사항
:::

### 안전관리규정 작성지침

-   원자력안전법 시행규칙 제58조제5항에 따른 작성지침은 원자력안전위원회고시에 제시되어 있습니다.

::: {.callout-note title="원자력안전위원회고시 제2019-11호 [시행 2019.05.10]" collapse="open" appearance="minimal"}
제1조(목적) 이 지침은 「원자력안전법 시행규칙」 제58조제5항에 따른 안전관리규정의 작성에 관한 사항을 규정함을 목적으로 한다.

제2조(적용범위) 이 지침은 방사성동위원소 및 방사선발생장치의 생산·사용·이동사용·판매허가신청에 따른 허가신청자의 안전관리규정 작성에 적용한다.

제3조(일반지침) 안전관리규정의 작성에 따른 일반지침은 다음 각 호와 같다.

1.  안전관리규정은 방사선원을 구성하고 있는 요소와 방사선작업 종사자, 일반인, 환경에 미치는 요인에 대하여 충분히 고려하여 작성하여야 한다.
2.  안전관리규정은 객관적이고 가능한 한 정량적인 방법에 의하되, 객관적인 평가방법이 확립되어 있지 않은 경우에는 기존의 사례 또는 자료를 이용하여 작성할 수 있다.
3.  안전관리규정은 사용현장을 충분히 확인하고 이해한 후 작성하여야 한다.
4.  안전관리규정의 내용 중 방사선안전보고서와 유사한 항목은 방사선안전보고서에 기술된 내용과 일치하도록 작성하여야 한다.
5.  안전관리규정 작성을 위한 방사선 안전성 평가에 사용된 방법 및 기술은 검증된 최신의 것이어야 하며, 검증되지 않은 경우에는 그 타당성을 별도로 입증하여야 한다. 이때에 인용된 자료는 출처를 명시하여야 한다.

제4조(세부지침) 안전관리규정은 다음 각 호에서 정하는 바에 따라 별지의 세부 작성지침에 따라 작성하여야 한다.

1.  방사성동위원소 등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항： 방사선안전관리를 위한 조직도와 함께 **`조직도에 명시된 관련자의 직무`**를 기술한다.

2.  방사성동위원소 등의 구매·사용 및 판매에 관한 사항： 방사성동위원소 등의 구매·사용 및 판매(생산하여 판매하는 경우에는 생산단계를 포함한다)하기 위한 **`절차 및 관리방법`**을 기술한다.

3.  방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배·보관·운반·처리·배출·저장·자체처분 및 인도에 관한 사항： 방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배·보관·운반·처리·배출·저장·자체처분 및 인도에 관한 **`절차 및 기준`**을 기술한다.

4.  방사선량률·피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항： **`측정의 대상 또는 장소 및 주기와 그 결과`**의 기록사항 및 보존기간에 대하여 기술하고 관련 양식을 첨부한다.

5.  방사선안전관리장비의 보관·관리 및 교정에 관한 사항： 방사선안전관리장비의 **`보관 및 관리방법과 교정주기`**에 대하여 기술한다.

6.  방사선작업종사자 및 수시출입자 분류 대상을 각각 세부적으로 기술한다.

    6의2. 방사선작업종사자 및 수시출입자의 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항： 방사선작업종사자 및 수시출입자 피폭방사선량을 평가하기 위한 **`개인선량계의 패용방법 및 절차와 개인선량계의 관리 및 판독 또는 교정주기`**에 대하여 기술한다.

7.  방사선작업종사자 또는 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항：**`교육훈련의 대상, 주기 및 교과목의 내용과 교육훈련을 수행하는 절차 및 결과의 관리`**에 대하여 기술한다.

8.  방사선장해발생 여부를 발견하기 위하여 필요한 조치에 관한 사항： 방사선장해발생의 여부를 발견하기 위한 **`건강진단 등 조치사항`**에 대하여 기술한다.

9.  방사선장해를 받은 자 또는 그 우려가 있는 자에 대하여 취하여야 할 보건상 조치에 관한 사항：방사선장해발생자 또는 우려자에 대한 **`구체적인 조치사항`**에 대하여 기술한다.

10. 「원자력안전법」 제58조에 따른 기록과 이의 비치에 관한 사항：원자력안전법령 및 관련 고시에서 규정하고 있는 각종 `기록사항 및 보존기간을 기술하고 관련양식을 첨부`한다.

11. 위험시의 조치에 관한 사항： 생산 또는 사용하고자 하는 방사성동위원소 등과 관련하여 **`비상사태를 대비한 응급조치, 보고 및 조치사항`**에 대하여 기술한다.

12. 방사성동위원소 등의 분실·도난 등 사고시의 조치 및 사고예방에 관한 사항： 방사성동위원소 등의 분실 또는 도난 등의 **`사고방지를 위한 구체적인 수행계획과 사고발생시의 조치사항`**에 대하여 기술한다.

13. 방사선안전관리자의 권한·책임 및 직무수행에 관한 사항：방사선안전관리에 관한 방사선안전관리자의 권한, 책임 및 직무수행에 관하여 구체적으로 기술한다.

14. 기타 방사선장해의 방어에 필요한 사항：사용하고자 하는 방사성동위원소 등의 특성에 따라 별도로 안전관리가 요구되는 사항이 있는 경우에는 이에 관하여 기술한다.
:::

안전관리규정 세부 작성지침

-   원자력안전위원회고시 제2019-11호 제4호 별지에서 언급하고 있는 세부 작성지침은 \[별지\] 안전관리규정 세부작성지침(제4조관련)은 아래와 같습니다.

::: {.callout-note title="원자력안전위원회고시 제2019-11호 [시행 2019.05.10] [별지] 안전관리규정 세부작성지침(제4조관련)" collapse="open" appearance="minimal"}
1.  방사성동위원소 등 또는 방사성동위원소에 의하여 오염된 물질을 취급하는 조직 및 그 기능에 관한 사항\
       가. 조직도\
          o 대표자를 정점으로 한 방사선원 및 사용시설 등의 이용과 관련된 안전관리업무를 수행하는 조직을 조직도의 형태로 도시한다.\
       나. 직무\
          o 대표이사, 부서장, 방사선안전관리자 및 방사선작업종사자의 직무에 관한 사항을 기술한다. 다만, 방사선안전관리자가 2인 이상인 경우에는 각각의 직무를 분리하여 기술한다.

2.  방사성동위원소 등의 구매ㆍ사용 및 판매에 관한 사항\
       가. 구매\
          o 방사선원의 구매ㆍ인수ㆍ인계ㆍ저장절차를 기술한다.\
          o 구매요구서를 사용하는 경우에는 구매요구서 양식, 작성방법 및 승인절차를 기술한다.\
       나. 사용\
          o 방사선원의 반입ㆍ반출ㆍ인수ㆍ인계ㆍ승인절차를 기술한다.\
          o 방사선원을 사용할 때에 준수하여야 하는 기술기준을 기술한다.\
          o 밀봉선원을 사용하는 경우에는 선원의 누설점검 방법 및 절차에 대하여 기술한다.\
       다. 판매\
          o 방사성동위원소 등의 판매허가자의 경우에는 운반을 포함한 방사선원의 판매 및 승인절차를 기술한다.\
          o 방사선원을 판매 및 운반할 때에 준수하여야 하는 기술기준을 기술한다.\
          o 구매자에게 공급하고자 하는 사용ㆍ운영ㆍ보수 및 관리방법이 포함된 설명서의 내용에 대하여 기술한다.\
          o 판매한 방사선원의 사후관리 내용 및 방법에 대하여 기술한다.\
       라. 생산\
          o 방사성동위원소 등의 생산허가자의 경우에는 생산단계마다의 관리절차를 기술한다.

3.  방사성동위원소 또는 방사성동위원소에 의하여 오염된 물질의 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도에 관한 사항\
       가. 절차\
          o 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도의 각각에 대한 취급 및 승인절차를 기술한다.\
       나. 기술기준\
          o 분배ㆍ보관ㆍ운반ㆍ처리ㆍ배출ㆍ저장ㆍ자체처분 및 인도의 각각에 대한 취급기준을 기술한다.

4.  방사선량률ㆍ피폭방사선량 및 방사성물질 또는 그에 의하여 오염된 물질에 따른 오염상황의 측정 및 그 측정결과의 기록과 보존에 관한 사항\
       가. 측정\
          o 방사선량률의 측정방법, 절차 및 주기에 대하여 기술한다.\
          o 방사능오염의 측정방법, 절차 및 주기에 대하여 기술한다.\
          o 피폭방사선량의 측정방법, 절차 및 주기에 대하여 기술한다.\
       나. 기록 및 보존\
          o 측정결과의 기록사항 및 그 보존기간에 대하여 기술한다.\
          o 기록양식을 첨부한다.

5.  방사선안전관리장비의 보관ㆍ관리 및 교정에 관한 사항\
       가. 보관 및 관리\
          o 방사선안전관리장비의 보관장소 및 비치장소를 기술한다.\
          o 방사선안전관리장비의 점검방법, 절차 및 주기에 대하여 기술한다.\
          나. 교정\
          o 방사선안전관리장비의 검ㆍ교정주기에 대하여 기술한다.

6.  「원자력안전법」 제2조제21호 및 「원자력안전법 시행령」 제2조제8호에 따른 방사선작업종사자 및 수시출입자의 정의에 부합하도록 방사선작업종사자 및 수시출입자 분류대상을 각각 세부적으로 기술한다.

6의2. 방사선작업종사자 및 수시출입자의 피폭방사선량의 평가 및 개인선량계의 관리에 관한 사항\
   가. 피폭방사선량의 평가\
      o 피폭방사선량의 평가방법에 대하여 기술한다.\
      o 개인선량계의 분실 등 판독 특이자에 대한 후속조치와 평가방법에 대하여 기술한다.\
   나. 개인선량계의 관리\
      o 개인선량계의 지급 및 회수 등 관리절차를 기술한다.\
      o 포켓도시메타의 경우에는 비치장소와 점검절차 및 교정주기에 대하여 기술한다.

7.  방사선작업종사자 또는 수시출입자의 방사선장해발생을 방지하기 위하여 필요한 교육훈련에 관한 사항\
          o 교육훈련계획의 수립 및 승인절차에 대하여 기술한다.\
          o 교육훈련의 시기, 과목 및 시간에 대하여 기술한다.\
          o 교육훈련을 위한 시설 및 장비에 대하여 기술한다.\
          o 교육훈련의 평가방법 및 그 결과의 기록사항에 대하여 기술한다.

8.  방사선장해발생 여부를 발견하기 위하여 필요한 조치에 관한 사항\
          o 방사선관리구역의 설정기준 및 관리절차에 대하여 기술한다.\
          o 방사선작업종사자 및 수시출입자에 대한 건강진단의 시기, 방법 및 주기에 대하여 기술한다.\
          o 가능하다면, 전담의료기관의 명칭, 위치 및 담당의의 신상명세를 기술한다.\
          o 방사선장해를 유발할 수 있는 시설의 점검에 대하여 기술한다.

9.  방사선장해를 받은 자 또는 그 우려가 있는 자에 대하여 취하여야 할 보건상 필요한 조치에 관한 사항\
          o 건강진단 결과 특이자에 대한 조치사항에 대하여 기술한다.\
          o 조치결과에 대한 보고내용 및 절차에 대하여 기술한다.

10. 「원자력안전법」 제58조에 따른 기록과 이의 비치에 관한 사항\
       가. 기록\
          o 기록사항을 기술하고 관련양식을 첨부한다.\
       나. 비치\
          o 기록장부의 비치장소 및 보존장소ㆍ기간을 기술한다.

11. 위험시의 조치에 관한 사항\
          o 사용하고자 하는 방사성동위원소 등과 관련한 비상사태를 고려하여 이에 대비한 응급조치, 보고 및 조치사항에 대하여 기술한다.\
          o 비상대응을 위한 방사선작업의 승인절차 및 방법을 기술한다.\
          o 조치결과에 대한 보고내용 및 절차에 대하여 기술한다.

12. 방사성동위원소 등의 분실ㆍ도난 등 사고시의 조치 및 사고예방에 관한 사항\
          o 분실ㆍ도난을 방지하기 위한 점검계획에 대하여 기술한다.\
          o 분실ㆍ도난 등의 사고에 따른 후속조치 절차 및 방법에 대하여 기술한다.\
          o 사고발생시 보고내용 및 방법 대하여 기술한다.

13. 방사선안전관리자의 권한ㆍ책임 및 직무수행에 관한 사항\
          o 방사선안전관리자의 권한 및 책임을 명확하게 기술한다.\
          o 방사선안전관리자의 권한 및 책임을 수행하기 위한 구체적인 직무의 내용을 기술한다.

14. 기타 방사선장해의 방어에 필요한 사항\
          o 진료를 목적으로 방사선기기를 인체에 사용하는 사업소에서는 다음의 사항을 기술한다.\
             - 품질관리절차서를 수립하고 이행하는 절차에 관한 사항\
             - 취급절차서를 구비하여 이행하는 절차에 관한 사항\
          o 사용하고자 하는 방사성동위원소 등의 특성에 따라 별도로 안전관리가 요구되는 사항이 있는 경우에는 이에 관하여 기술한다.\
          o 「원자력안전법」에서 규정하고 있는 기술기준이외에 별도로 적용하고자 하는 국내ㆍ외의 기술기준이 있는 경우에는 이를 기술한다.
:::

### 방사선안전관리자의 인력기준

-   원자력안전법 시행규칙 제68조의4제1항제1호 관련 별표1의2를 참고합니다.

제68조의4(방사선안전관리자의 자격요건 등) ① 영 제82조의4제3항에 따른 방사선안전관리자의 세부 자격요건은 다음 각 호와 같다. \<개정 2016. 8. 8., 2023. 3. 9.\>\
   1. 허가사용자가 선임하는 경우에는 별표 1의2에 따른 인력으로 다음 각 목의 구분에 따른 요건을 갖춘 사람\
      가. 면허를 소지한 경우: 선임일부터 최근 3년 이내에 면허를 취득하였거나 법 제106조제2항에 따른 보수교육을 받은 사람\
      나. 방사선관리기술사 자격을 소지한 경우: 「국가기술자격법」에 따라 방사선관리기술사자격을 취득하고 「기술사법」 제5조의7에 따른 기술사로 등록하거나 등록을 갱신한 사람\
   2. 신고사용자가 선임하는 경우에는 방사성동위원소등의 취급업무에 종사한 경력이 있는 사람으로서 선임일부터 최근 3년 이내에 제138조제2항에 따른 방사선안전관리자 교육을 받은 사람

② 방사선안전관리자가 2명 이상인 경우 각각의 방사선안전관리 업무를 명확하게 구분하여야 한다. \[본조신설 2014. 11. 24.\]\[제68조의3에서 이동, 종전 제68조의4는 제68조의5로 이동 \<2023. 3. 9.\>\]

|  |  |
|:-----------------------------------|:-----------------------------------|
| **1. 생산** | 방사선취급**`감독자면허`** 소지자 또는 방사선관리기술사 1명 이상 (「의료기기법」 제6조에 따른 의료기기 제조업 허가를 받은 자가 **방사선발생장치** 생산 허가를 받는 경우에는 방사성동위원소취급자**`일반면허`** 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상) |
| **2. 판매** |  |
| 가. 방사성동위원소를 판매하는 경우 | 방사선취급`**감독자면허**` 소지자 또는 방사선관리기술사 1명 이상 |
| 나. 방사선발생장치를 판매하는 경우 | 방사성동위원소취급자`**일반면허**` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| **3. 사용** |  |
| 가. 인체에 사용하는 경우 | 방사성동위원소취급자`특수면허` 소지자 1명 이상 및 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 나. 인체 외에 사용하는 경우 |  |
| 1\) 밀봉된 방사성동위원소 |  |
| 가) 기기에 장비되지 않은 것으로서 연간 사용량 1.85테라베크렐 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 기기에 장비되지 않은 것으로서 연간 사용량 1.85테라베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 다) 기기에 장비된 것으로서 연간 사용량 3.7테라베크렐 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 라) 기기에 장비된 것으로서 연간 사용량 3.7테라베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 2\) 밀봉되지 아니한 방사성동위원소 |  |
| 가) 연간 사용량 1.85기가베크렐 이상 | 방사성동위원소취급자`특수면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 연간 사용량 1.85기가베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사성동위원소취급자특수면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 3\) 방사선발생장치 |  |
| 가) 1메가전자볼트 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 최대 전압 350킬로볼트 이상으로서 용량이 350킬로볼트 5밀리암페어 1대 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 다) 최대 전압 350킬로볼트 미만으로서 용량이 250킬로볼트 5밀리암페어 2대 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 라) 가)부터 다)까지의 규정에 해당되지 않는 경우 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 4\) 이동사용 |  |
| 가. 방사선투과검사의 목적으로 이동사용하는 경우 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 2명 이상 |
| 나. 방사선투과검사 목적으로 이동사용하는 작업장의 경우 | 방사성동위원소취급자일반면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 다. 가목 또는 나목 이외의 경우 | 방사성동위원소취급자일반면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |

: 방사성동위원소등 허가사용자의 방사선안전관리자 인력기준 <br> (원자력안전법 시행규칙 \[별표 1의2\] \<개정 2023. 3. 9.\>) {#tbl-example}
