---
title: "원자력안전법"
author: "원자력안전위원회"
date: "2024-11-01"
categories: [원자력안전법]
---

# 원자력안전법 전문

## 제1장 총칙

### 제1조 (목적)

이 법은 원자력의 연구ㆍ개발ㆍ생산ㆍ이용 등에 따른 안전관리에 관한 사항을 규정하여 방사선에 의한 재해의 방지와 공공의 안전을 도모함을 목적으로 한다.

### 제2조 (정의)

이 법에서 사용하는 용어의 뜻은 다음과 같다. 1. "원자력"이란 원자핵 변화의 과정에서 원자핵으로부터 방출되는 모든 종류의 에너지를 말한다. 2. "핵물질"이란 핵연료물질 및 핵원료물질을 말한다. 3. "핵연료물질"이란 우라늄ㆍ토륨 등 원자력을 발생할 수 있는 물질로서 대통령령으로 정하는 것을 말한다. 4. "핵원료물질"이란 우라늄광ㆍ토륨광과 그 밖의 핵연료물질의 원료가 되는 물질로서 대통령령으로 정하는 것을 말한다. 5. "방사성물질"이란 핵연료물질ㆍ사용후핵연료ㆍ방사성동위원소 및 원자핵분열생성물을 말한다. 6. "방사성동위원소"란 방사선을 방출하는 동위원소와 그 화합물 중 대통령령으로 정하는 것을 말한다. 7. "방사선"이란 전자파 또는 입자선 중 직접 또는 간접으로 공기를 전리하는 능력을 가진 것으로서 대통령령으로 정하는 것을 말한다. 8. "원자로"란 핵연료물질을 연료로 사용하는 장치를 말한다. 다만, 대통령령으로 정하는 것은 제외한다. 9. "방사선발생장치"란 하전입자를 가속시켜 방사선을 발생시키는 장치로서 대통령령으로 정하는 것을 말한다. 10. "관계시설"이란 원자로의 안전에 관계되는 시설로서 대통령령으로 정하는 것을 말한다. 11. "정련"이란 핵원료물질에 포함된 우라늄 또는 토륨의 비율을 높이기 위하여 물리적ㆍ화학적 방법으로 핵원료물질을 처리하는 것을 말한다. 12. "변환"이란 핵연료물질을 화학적 방법으로 처리하여 가공에 적합한 형태로 만드는 것을 말한다. 13. "가공"이란 핵연료물질을 물리적ㆍ화학적 방법으로 처리하여 원자로의 연료로서 사용할 수 있는 형태로 만드는 것을 말한다. 14. "사용후핵연료처리"란 원자로의 연료로서 사용된 핵연료물질 또는 그 밖의 방법으로 원자핵분열을 시킨 핵연료물질을 연구 또는 시험을 목적으로 취급하거나, 물리적ㆍ화학적 방법으로 처리하여 핵연료물질과 그 밖의 물질로 분리하는 것을 말한다. 15. "핵연료주기사업"이란 정련ㆍ변환ㆍ가공 또는 사용후핵연료처리 사업을 말한다. 16. "방사선관리구역"이란 외부의 방사선량율, 공기 중의 방사성물질의 농도 또는 방사성물질에 따라 오염된 물질의 표면의 오염도가 원자력안전위원회규칙으로 정하는 값을 초과할 우려가 있는 곳으로서 방사선의 안전관리를 위하여 사람의 출입을 관리하고 출입자에 대하여 방사선의 장해를 방지하기 위한 조치가 필요한 구역을 말한다. 17. "국제규제물자"란 원자력의 연구ㆍ개발 및 이용에 관한 조약과 그 밖의 국제약속에 따라 보장조치의 적용대상이 되는 물자로서 총리령으로 정하는 것을 말한다. 18. "방사성폐기물"이란 방사성물질 또는 그에 따라 오염된 물질로서 폐기의 대상이 되는 물질을 말한다. 19. "피폭방사선량"이란 사람의 신체의 외부 또는 내부에 피폭하는 방사선량을 말한다. 다만, 진료를 위하여 피폭하는 방사선량과 인위적으로 증가시키지 아니하는 자연방사선량은 제외한다. 이 경우 방사선량의 종류 및 적용기준은 원자력안전위원회가 정하여 고시한다. 20. "원자력이용시설"이란 원자력의 연구ㆍ개발ㆍ생산ㆍ이용과 관련된 시설로서 대통령령으로 정하는 것을 말한다. 21. "방사선작업종사자"란 원자력이용시설의 운전ㆍ이용 또는 보전이나 방사성물질등의 사용ㆍ취급ㆍ저장ㆍ보관ㆍ처리ㆍ배출ㆍ처분ㆍ운반과 그 밖의 관리 또는 오염제거 등 방사선에 피폭하거나 그 염려가 있는 업무에 종사하는 자를 말한다. 22. "안전관련설비"란 원자로 및 관계시설 중에서 원자력안전위원회규칙으로 정하는 안전에 중요한 구조물ㆍ계통 및 기기로서 원자력안전위원회규칙으로 정하는 바에 따라 안전등급이 부여된 설비를 말한다. 23. "방사선투과검사"란 「비파괴검사기술의 진흥 및 관리에 관한 법률」 제2조에 따른 비파괴검사 중 방사선을 이용한 비파괴검사를 말한다. 24. "해체"란 제20조제1항에 따라 허가를 받은 자, 제30조의2제1항에 따라 허가를 받은 자, 제35조제1항 및 제2항에 따라 허가 또는 지정을 받은 자, 제63조제1항에 따라 건설ㆍ운영 허가를 받은 자가 이 법에 따라 허가 또는 지정을 받은 시설의 운영을 영구적으로 정지한 후, 해당 시설과 부지를 철거하거나 방사성오염을 제거함으로써 이 법의 적용대상에서 배제하기 위한 모든 활동을 말한다. 25. "폐쇄"란 제63조에 따라 방사성폐 ::contentReference[oaicite:0]{index="0"}
