---
title: "방사선안전관리 기술기준"
author: "Radiation Safety Committee"
description: "방사선안전관리자의 업무 중 원자력안전법제59조제1항의 기술기준의 준수여부 점검이 포함되므로 정리해 보았습니다."
date: "2024-12-06"
modified-date: "2024-12-06"
categories: [기술기준]
---

## 기술기준 위원회규칙

-   원자력안전법 제59조제1항에서 언급하는 위원회규칙인 \[방사선 안전관리 등의 기술기준에 관한 규칙\]\[시행 2023.9.25\]의 주요내용은 아래와 같습니다.

### 방사선관리구역

::: {.callout-note title="제3조 (방사선관리구역)" collapse="open" appearance="minimal"}
<p style="text-indent: -20px; margin-left: 20px;">

① 법 제2조제16호에서 "원자력안전위원회규칙으로 정하는 값"이라 함은 다음 각호와 같다.

</p>

1.  외부방사선량률 : 1주당 400마이크로시버트

2.  공기중의 방사성물질의 농도 : 유도공기중농도

3.  물체표면의 오염도 : 허용표면오염도

<p style="text-indent: -20px; margin-left: 20px;">

② 외부방사선량률 등이 제1항의 규정에 의한 값을 초과할 우려가 있는 곳에 대하여는 사람의 출입을 관리하고 출입자에 대한 방사선의 장해를 방지하기 위하여 다음 각호의 조치를 하여야 한다.

</p>

1.  방사선관리구역의 설정

2.  벽ㆍ울타리 등의 구획물로 구획하여 별표 1에 의한 표지를 부착함으로써 다른 장소와 구별하고 방사선작업종사자외의 사람이 당해 구역에 출입하는 경우에는 방사선작업종사자의 지시에 따르도록 할 것

3.  바닥ㆍ벽 기타 사람이 접촉할 우려가 있는 물체의 표면이 방사성물질에 오염된 경우 그 오염도가 허용표면오염도를 초과하지 아니하도록 할 것

4.  방사선관리구역으로부터 사람이 퇴거하거나 물품을 반출하는 경우에는 인체 및 의복ㆍ신발 등 인체에 착용하고 있는 물품과 반출하는 물품(그 물품이 용기에 들어있거나 포장한 경우에는 그 용기 또는 포장)표면의 방사성물질의 오염도가 허용표면오염도의 10분의 1을 초과하지 아니하도록 할 것\
:::

### 개봉선원의 생산시설

::: {.callout-note title="제17조 (개봉선원의 생산시설)" collapse="open" appearance="minimal"}
<p style="text-indent: -20px; margin-left: 20px;">

① 개봉선원의 생산시설은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.

</p>

<p style="text-indent: -20px; margin-left: 20px;">

② 개봉선원 생산시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

</p>

1.  주요 구조부는 내화구조로 하거나 불연재료를 사용할 것

2.  다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

            가. 생산시설 안의 사람이 상시 출입하는 장소에서의 방사선량

            나. 사업소의 경계에 인접하는 구역에서의 방사선량

3.  다음 각목의 기준에 따라 작업실을 설치할 것

            가. 작업실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

            나. 작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것

4\. 다음 각목의 기준에 따라 오염검사실을 설치할 것

            가. 오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

            나. 오염검사실 내부의 벽ㆍ바닥 그 밖에 개봉선원에 의하여 오염될 우려가 있는 부분은 제3호 가목의 기술기준에 적합한 것으로 할 것

            다. 오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 장비를 갖출 것

5\. 개봉선원을 생산하기 위한 방사선 조사시설(조사시설)에는 다음 각목의 기준에 따라 시설을 설치할 것

가. 출입구에 방사선 조사중임을 자동적으로 표시하는 장치를 설치할 것

나. 방사선 조사 여부에 따라 출입구가 개폐되는 연동장치를 할 것

다. 내부를 상시 감시할 수 있는 장치를 할 것

라. 사람의 출입을 제한하는 장치를 할 것

6\. 시설의 경계에는 울타리 그 밖에 사람의 출입을 제한하는 시설을 할 것. 다만, 제2호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7\. 생산시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 그 밖에 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 사용시설등의 위치

::: {.callout-note title="제18조 (사용시설등의 위치)" collapse="open" appearance="minimal"}
제18조 (사용시설등의 위치) 개봉선원(개봉선원)의 사용시설등은 지반이 견고하고 화재 또는 침수의 우려가 적은 장소에 이를 설치하여야 한다.
:::

### 사용시설 및 분배시설

::: {.callout-note title="제19조 (사용시설 및 분배시설)" collapse="open" appearance="minimal"}
제19조 (사용시설 및 분배시설) ① 개봉선원의 사용시설 및 분배시설의 구조 및 설비에 관한 기술기준은 다음 각 호와 같다.

1\. 주요구조부는 내화구조로 하거나 불연재료를 사용할 것. 다만, 원자력안전위원회가 정하여 고시하는 것은 그러하지 아니하다.

2\. 사용시설은 개봉선원을 취급하기 위한 장비의 설치 및 작업 수행에 필요한 공간을 확보할 것

3\. 다음 각목의 1에 해당하는 방사선량이 선량한도 이하가 되도록 필요한 차폐벽이나 차폐물을 설치할 것

가. 사용시설안 및 분배시설안의 사람이 상시 출입하는 장소에서의 방사선량

나. 사업소의 경계에 인접하는 구역에서의 방사선량

4\. 다음 각목과 같은 작업실을 설치할 것

가. 작업실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분의 표면은 평탄하고 매끄러우며 빈틈이나 구멍이 없도록 하고, 기체 또는 액체가 침투할 수 없는 내식성이 강한 재료로 할 것

나. 작업실에 설치한 후드ㆍ글로브박스 등 기체상의 방사성동위원소의 확산을 방지하는 장치는 배기설비에 연결시킬 것. 다만, 원자력안전위원회가 정하는 것은 그러하지 아니하다.

5\. 다음 각목의 1에 해당하는 오염검사실을 설치할 것. 다만, 인체 및 작업복ㆍ신발등 인체에 착용하는 물건의 표면이 방사성동위원소에 의하여 오염될 우려가 없도록 밀폐된 장치안에서 개봉선원을 사용 또는 분배하는 경우와 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 오염검사실은 사람이 상시 출입하는 출입구 부근 등 개봉선원에 의한 오염검사를 실시하기에 가장 적합한 장소에 설치할 것

나. 오염검사실 내부의 벽ㆍ바닥 기타 개봉선원에 의하여 오염될 우려가 있는 부분은 제4호 가목의 기술기준에 적합한 것으로 할 것

다. 오염검사실에는 세정ㆍ탈의설비, 오염검사를 위한 방사선측정기 및 오염제거에 필요한 기재(기재)를 갖출 것

6\. 경계에는 울타리 기타 사람의 출입을 제한하는 시설을 할 것. 다만, 제3호 가목에 해당하는 방사선량이 선량한도 이하가 되도록 차폐벽이나 차폐물이 설치되어 있는 경우에는 그러하지 아니하다.

7\. 사용시설ㆍ분배시설ㆍ작업실ㆍ오염검사실의 경계에 설치한 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것

② 제1항의 규정은 누수의 조사, 곤충의 역학적 조사 또는 원료물질의 생산공정중 이동상황의 조사 등을 위하여 개봉선원을 광범위하게 분산ㆍ이동시키는 경우 또는 일시적으로 사용ㆍ분배하는 경우에는 이를 적용하지 아니한다.
:::

### 저장시설

::: {.callout-note title="제20조 (저장시설)" collapse="open" appearance="minimal"}
개봉선원 저장시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1.  저장시설의 구조는 다음 각목과 같이 할 것

            가. 저장실의 주요 구조부 및 출입문은 내화구조로 하거나 불연재료를 사용할 것

            나. 저장함은 내화구조로 하거나 불연재료를 사용할 것

2.  저장시설에는 제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  저장시설에 비치하는 용기는 다음 각목의 기준에 적합할 것

            가. 외부의 공기를 오염시킬 우려가 있는 개봉선원을 넣는 용기는 기밀구조일 것

            나. 액체상의 개봉선원을 넣는 용기의 구조는 액체가 누출되지 아니하도록 하고, 그 재료는 액체가 침투할 수 없는 것으로 할 것

            다. 액체상 또는 기체상의 개봉선원을 넣는 용기가 균열 또는 파손될 우려가 있는 때에는 밑받이ㆍ흡수재 기타 개봉선원에 의한 오염의 확산을 방지하기 위한 시설 또는 기구를 설치할 것

4.  저장시설의 문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 시설 또는 기구를 설치할 것

5.  저장시설의 경계에는 울타리 기타 사람의 출입을 제한하는 시설을 설치할 것

6.  저장실ㆍ저장함, 제3호의 용기 및 저장시설의 경계에 설치하는 울타리 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것\
:::

### 보관시설

::: {.callout-note title="제21조 (보관시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 보관시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1\. 주요 구조부를 내화구조로 하거나 불연재료로 할 것

2\. 제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3\. 다음 각목의 기준에 적합한 보관설비를 갖출 것

가. 외부와 구획된 구조로 할 것

나. 문ㆍ덮개 등 외부로 통하는 부분에는 자물쇠 기타 도난 또는 분실을 방지하기 위한 설비 또는 기구를 설치할 것

다. 제20조제3호의 기술기준에 적합한 용기를 비치할 것. 다만, 방사성동위원소에 의하여 오염된 대형기계 등으로서 용기에 넣기가 곤란하여 오염확산을 방지하기 위한 조치를 취한 경우에는 그러하지 아니하다.

4\. 보관설비, 제3호 다목의 용기 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 처리시설

::: {.callout-note title="제22조 (처리시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 처리시설의 구조 및 설비에 관한 기술기준은 다음 각호와 같다.

1\. 주요 구조부를 내화구조 또는 불연재료로 할 것

2\. 제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3\. 방사성동위원소 및 그에 의하여 오염된 물질을 소각하는 경우에는 원자력안전위원회가 정하여 고시하는 바에 따라 소각설비를 설치할 것

4\. 방사성동위원소 및 그에 의하여 오염된 물질을 콘크리트 기타 고형화 재료에 의하여 고형화하는 경우에는 다음 각목에 정하는 바에 따라 고형화처리설비를 설치하는 외에 오염검사실 및 제23조제4호의 기준에 적합한 배기설비를 설치할 것

가. 고형화처리설비는 방사성동위원소 및 그에 의하여 오염된 물질이 누설되거나 넘쳐 흐르지 아니하고 분진이 확산되지 아니하는 구조로 할 것

나. 고형화처리설비는 액체가 침투하지 아니하고 부식에 강한 재료로 할 것

5\. 소각로ㆍ오염검사실 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 배출시설

::: {.callout-note title="제23조 (배출시설)" collapse="open" appearance="minimal"}
개봉선원 및 그에 의하여 오염된 물질의 배출시설의 구조 및설비에 관한 기술기준은 다음 각호와 같다.

1.  주요 구조부를 내화구조 또는 불연재료로 할 것

2.  제19조제1항제3호의 기술기준에 적합한 차폐벽이나 차폐물을 설치할 것

3.  액체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는바에 따라 배수설비를 설치할 것. 다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 배수설비는 배수구에서 채취한 배출액의 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖추도록 할 것. 다만, 배수구에서의 배수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배수중 방사성동위원소의 농도를 감시하기 위한 배수감시설비를 하고 사업소의 경계외부에서의 수중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하는 경우에는 그러하지 아니하다.

나. 배수설비의 구조는 배출액이 누설되지 아니하도록 하고, 그 재료는 배출액이 침투할 수 없고 내식성이 강한 것으로 할 것

다. 배수정화조는 배출액을 채취하여 배출액의 방사성동위원소 농도를 쉽게 측정할 수 있도록 이를 설치하고, 그 주위에는 울타리 등 사람의 출입을 제한하는 시설을 설치할 것

4.  기체상의 방사성동위원소를 정화하거나 배출하는 경우에는 다음 각목에 정하는 바에 따라 배기설비를 설치할 것. 다만, 원자력안전위원회가 정하여 고시하는 경우에는 그러하지 아니하다.

가. 배기설비는 작업실안의 사람이 상시 출입하는 장소에서의 공기중 방사성동위원소의 농도를 유도공기중농도 이하로 하는 능력을 갖출 것

나. 배기설비는 배기구의 배기중 방사성동위원소 농도를 배출관리기준의 제한값 이하로 하는 능력을 갖출 것. 다만, 배기구에서의 배기중 방사성동위원소의 농도를 배출관리기준의 제한값 이하로 하기가 곤란한 경우로서 배기중 방사성동위원소의 농도를 감시하기 위한 배기감시설비를 하고 사업소 등의 경계외부에서의 공기중 방사성동위원소 농도를 배출관리기준의 제한값이하로 하는 경우에는 그러하지 아니하다.

다. 배기설비의 구조는 배기구외로 기체가 누설되지 아니하도록 하고, 그 재료는 내식성이 강한 것으로 할 것

라. 배기설비에는 고장이 발생한 경우 방사성동위원소에 의하여 오염된 공기의 확산을 신속히 방지할 수 있는 장치를 할 것

5.  배수설비ㆍ배기설비와 기타 사람의 출입을 제한하는 시설에는 별표 1에 의한 표지를 부착할 것
:::

### 보안관리 시설등

::: {.callout-note title="제23조의2 (개봉선원의 보안관리 시설등)" collapse="open" appearance="minimal"}
원자력안전위원회가 정하는 수량 이상의 개봉선원 생산시설 및 사용시설등에는 원자력안전위원회가 정하여 고시하는 바에 따라 보안관리 시설 또는 설비를 설치하여야 한다.
:::
