---
title: "방사선안전관리자 인력"
description: "방사선안전관리자의 인력에 대해 정리한 것입니다."
author: "대한핵의학회 방사선안전위원회"
date: "2024-11-27"
date-modified: "2024-12-24"
categories: [방사선안전관리자, 인력]
---

### 방사선안전관리자의 인력기준

-   원자력안전법 시행규칙 제68조의4제1항제1호 관련 별표1의2를 참고합니다.

제68조의4(방사선안전관리자의 자격요건 등) ① 영 제82조의4제3항에 따른 방사선안전관리자의 세부 자격요건은 다음 각 호와 같다. \<개정 2016. 8. 8., 2023. 3. 9.\>\
   1. 허가사용자가 선임하는 경우에는 별표 1의2에 따른 인력으로 다음 각 목의 구분에 따른 요건을 갖춘 사람\
      가. 면허를 소지한 경우: 선임일부터 최근 3년 이내에 면허를 취득하였거나 법 제106조제2항에 따른 보수교육을 받은 사람\
      나. 방사선관리기술사 자격을 소지한 경우: 「국가기술자격법」에 따라 방사선관리기술사자격을 취득하고 「기술사법」 제5조의7에 따른 기술사로 등록하거나 등록을 갱신한 사람\
   2. 신고사용자가 선임하는 경우에는 방사성동위원소등의 취급업무에 종사한 경력이 있는 사람으로서 선임일부터 최근 3년 이내에 제138조제2항에 따른 방사선안전관리자 교육을 받은 사람

② 방사선안전관리자가 2명 이상인 경우 각각의 방사선안전관리 업무를 명확하게 구분하여야 한다. \[본조신설 2014. 11. 24.\]\[제68조의3에서 이동, 종전 제68조의4는 제68조의5로 이동 \<2023. 3. 9.\>\]

|  |  |
|:-----------------------------------|:-----------------------------------|
| **1. 생산** | 방사선취급**`감독자면허`** 소지자 또는 방사선관리기술사 1명 이상 (「의료기기법」 제6조에 따른 의료기기 제조업 허가를 받은 자가 **방사선발생장치** 생산 허가를 받는 경우에는 방사성동위원소취급자**`일반면허`** 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상) |
| **2. 판매** |  |
| 가. 방사성동위원소를 판매하는 경우 | 방사선취급`**감독자면허**` 소지자 또는 방사선관리기술사 1명 이상 |
| 나. 방사선발생장치를 판매하는 경우 | 방사성동위원소취급자`**일반면허**` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| **3. 사용** |  |
| 가. 인체에 사용하는 경우 | 방사성동위원소취급자`특수면허` 소지자 1명 이상 및 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 나. 인체 외에 사용하는 경우 |  |
| 1\) 밀봉된 방사성동위원소 |  |
| 가) 기기에 장비되지 않은 것으로서 연간 사용량 1.85테라베크렐 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 기기에 장비되지 않은 것으로서 연간 사용량 1.85테라베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 다) 기기에 장비된 것으로서 연간 사용량 3.7테라베크렐 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 라) 기기에 장비된 것으로서 연간 사용량 3.7테라베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 2\) 밀봉되지 아니한 방사성동위원소 |  |
| 가) 연간 사용량 1.85기가베크렐 이상 | 방사성동위원소취급자`특수면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 연간 사용량 1.85기가베크렐 미만 | 방사성동위원소취급자`일반면허` 소지자, 방사성동위원소취급자특수면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 3\) 방사선발생장치 |  |
| 가) 1메가전자볼트 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 나) 최대 전압 350킬로볼트 이상으로서 용량이 350킬로볼트 5밀리암페어 1대 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 다) 최대 전압 350킬로볼트 미만으로서 용량이 250킬로볼트 5밀리암페어 2대 이상 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 1명 이상 |
| 라) 가)부터 다)까지의 규정에 해당되지 않는 경우 | 방사성동위원소취급자`일반면허` 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 4\) 이동사용 |  |
| 가. 방사선투과검사의 목적으로 이동사용하는 경우 | 방사선취급`감독자면허` 소지자 또는 방사선관리기술사 2명 이상 |
| 나. 방사선투과검사 목적으로 이동사용하는 작업장의 경우 | 방사성동위원소취급자일반면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |
| 다. 가목 또는 나목 이외의 경우 | 방사성동위원소취급자일반면허 소지자, 방사선취급감독자면허 소지자 또는 방사선관리기술사 1명 이상 |

: 방사성동위원소등 허가사용자의 방사선안전관리자 인력기준 <br> (원자력안전법 시행규칙 \[별표 1의2\] \<개정 2023. 3. 9.\>) {#tbl-example}
